### ISSUE TITLE
Blurred overlay appears with no survey

### ISSUE THREAD

**Issue by phil-brown** [mixpanel/mixpanel-android#119]
**Version: MixPanel 4.3.0**
**Platform: Android 4.4**
**Device: Nexus 5**

## Steps to reproduce

1. Open app that uses MixPanel surveys
2. Click a notification from a different app, opening the other app.
3. Using the back button, go back to the first app.

*Here, a MixPanel survey attempts to show*

**Expected Result:** The screen blurs and the survey is shown.
**Actual Result:** The screen blurs, but no survey appears. Clicking the back button closes the blurred screen.

## Additional Details

I have only experienced this once, but did very recently update to 4.3.0 to incorporate App Links.

**Comment by yinfeiru** [comment]
Please re-open if you still have this issue.
