### ISSUE TITLE
Unset Device Tokens

### ISSUE THREAD

**Issue by mullen3** [mixpanel/mixpanel-android#125]
This is a clone of my feature request from the mixpanel-ios sdk.

I have a use case for "unsetting" device tokens via the sdk. We have log-in and log-out functionality in our app. It's possible for a user to log-in with account X, log-out of that account, and then log in with account Y (all on the same device).

I would like to be able to unregister the deviceToken for account X when they log-out.

**Comment by sayoojvalsan-demandmedia** [comment]
Any updates on this ? We have multiple users in the app. Looks like when old user logs out and new user login in, and when you send a notification to old user, the new user receives it. Can you please address this ?



Example

user xxx login in. 
user xxx logs out.
user yyy logs in.

Now if you send push to xxx, yyy will receives it. We tried using reset and it didnt help.

**Comment by joeatwork** [comment]
@sayoojvalsan-demandmedia - when user yyy logs in, are you calling getPeople().identify?

**Comment by ryanseams** [comment]
Hi @sayoojvalsan-demandmedia -- We have a method already called ```clearPushRegistrationId``` which will remove all device tokens from a profile. Does this work for your purposes?

In case it helps, we are also planning to add the ability to remove a single device token in https://github.com/mixpanel/mixpanel-android/pull/378.
