### ISSUE TITLE
Feature Request: Support ADM Notifications for Kindle Notifications

### ISSUE THREAD

**Issue by phil-brown** [mixpanel/mixpanel-android#140]
We have just added support for Kindle and the Amazon App Store to our apps. Android devices that use the Amazon App Store to download this app can still use GCM for surveys and notifications, but Kindle Fire does not support this.

Amazon has its own messaging system called [Amazon Device Messaging (ADM)](https://developer.amazon.com/appsandservices/apis/engage/device-messaging) that would work instead. Can you add support for this?

**Comment by tallior** [comment]
Any updates on this? is this planned to be added ?

**Comment by joeatwork** [comment]
We're aware of this, but I'm afraid we haven't gotten it into a release yet. As of now, we're not actively working on this feature (it'll require some new UX for folks sending pushes, and server side tooling in addition to library features, so it's a bit of a lift.)

 More comments and interest (either here, in this pull request, or via Mixpanel support) could help us get to that work sooner. We'd also have an easier time merging ways to plug your own infrastructure into the existing library (for example, tracking pushes that are fielded and registered for by your own listeners and servers, so you could send yourself a web hook from Mixpanel and push your own payloads into the pipeline.) - If that sort of thing would be acceptable to you, it'd be easier for us to get scheduled.
