### ISSUE TITLE
Last Seen Not Updating

### ISSUE THREAD

**Issue by eygraber** [mixpanel/mixpanel-android#156]
I'm using Mixpanel in an Android and iOS app. Neither sets any people properties (the server handles aliasing and people properties - first it aliases then it sets some properties and this only happens once). The issue is that while last seen is updating for iOS users, the Android users last seen is still set to the time when the server set the people properties. I'm not sure which one is the incorrect behavior, but I'd like the last seen to update when events come in for that user. Is that possible?

**Comment by joeatwork** [comment]
Thanks for reporting this (and sorry for the long delay in replying!) As things stand, last seen is only set when you update people analytics properties- if it is updated in iOS, then they're certainly setting people properties (possibly associated with push notifications, if you're not setting any properties explicitly in your app.) I'll get in touch with our iOS folks and see 1) what they may be updating in this case, and 2) whether the Android lib should be updating the same stuff.

For now, you'll need to update some people property in the Android lib to make changes to last seen. I'll post more information here when I get it.

**Comment by eygraber** [comment]
@joeatwork Thanks! Setting a people property did the trick. Adding `mixpanel.getPeople().set(new JSONObject())` is what did it.

**Comment by joeatwork** [comment]
Glad this helped!
