### ISSUE TITLE
Release 4.5.1 is not available in gradle yet?

### ISSUE THREAD

**Issue by kamoljan** [mixpanel/mixpanel-android#157]
I have included `mavenCentral()` in my `repositories`.
However, gradle still cannot download Release 4.5.1.

**Comment by joeatwork** [comment]
I'm sorry you're having trouble!

We've made some changes to how we package the artifact in 4.5.1- in particular, we no longer require that `@arr` is specified, so it's possible we introduced some issues here. I'm able to pull the artifact from Maven central with the following bit of gradle:

```
dependencies {
    ... // Your other dependencies here
    compile 'com.mixpanel.android:mixpanel-android:4.5.1'
}
```

Does this work for you? Would you mind posting the `dependencies` snippet of your build.gradle here?

Thanks!

**Comment by kamoljan** [comment]
Hi @joeatwork 

even with

    dependencies {
        ... // Your other dependencies here
        compile 'com.mixpanel.android:mixpanel-android:4.5.1'
    }
it still does not load.

Is your repository?

    repositories {
        mavenCentral()
    }

Best regards
Kamol

**Comment by joeatwork** [comment]
It is. Would you mind posting your gradle file here (or perhaps sending sending it to support@mixpanel.com)? I'm afraid I can't reproduce your issue.

**Comment by kamoljan** [comment]
hi @joeatwork 

My gradle configuration was wrong.
I am sorry, it was my fault.

It works now.
Thank you very much for your prompt responses.

Best regards
Kamol

**Comment by joeatwork** [comment]
Glad to hear it worked out!
