### ISSUE TITLE
Very uncommon AnalyticsMessages worker error on activity recreation

### ISSUE THREAD

**Issue by SleeplessByte** [mixpanel/mixpanel-android#161]
Seems like a check missing:

````
E/AndroidRuntime﹕ FATAL EXCEPTION: com.mixpanel.android.AnalyticsWorker
    Process: com.paystik.droid.debug.hb, PID: 7244
    java.lang.NullPointerException: Attempt to read from field 'com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.this$1' on a null object reference
            at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(AnalyticsMessages.java:297)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.os.HandlerThread.run(HandlerThread.java:62)
````

**Comment by joeatwork** [comment]
Very strange! Do you have any idea what circumstances might result in the bug? Also, can you confirm you're experiencing this in the latest stable version (or just let me know what version you're experiencing it with?)

If I'm reading the line numbers correctly, it looks like this error is in an exception handler, and something really terrible has already happened to the Mixpanel thread.

**Comment by joeatwork** [comment]
Are you seeing an error level log entry with "Worker threw an unhandled exception" in the logs surrounding this issue? If so, could you send the exception?

(If you can't get the info I'm asking about, don't worry- this is still on our radar- Most of all, thanks for the bug report!)

**Comment by SleeplessByte** [comment]
The unhandled exception is the NullPointerException :) There is no other error, here is the FATAL entry:

````
E/AndroidRuntime﹕ FATAL EXCEPTION: com.mixpanel.android.AnalyticsWorker
    Process: com.paystik.droid.debug.hb, PID: 7244
    java.lang.NullPointerException: Attempt to read from field 'com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.this$1' on a null object reference
            at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(AnalyticsMessages.java:297)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.os.HandlerThread.run(HandlerThread.java:62)
````

**Comment by SleeplessByte** [comment]
Running the latest Gradle supplied version.

**Comment by yinfeiru** [comment]
@SleeplessByte Do you still have this issue? Please re-open if so.

**Comment by SleeplessByte** [comment]
Haha. A year later? I don't have it any more for the mere reason that I don't work on that app any more.
