### ISSUE TITLE
How do InAppNotifications arrive when there are multiple triggers activated?

### ISSUE THREAD

**Issue by sirvon** [mixpanel/mixpanel-android#163]
burning question in regards to InAppNotifications.

So if there say 20 triggers activated around the same time, how will these 20 notifications come in.

pretty much they'll be queued up until I call getNotificationIfAvaliable() 20 times?

**Comment by yinfeiru** [comment]
@sirvon  Sorry for the late. They will be in the same decide response and you'll need to call `getNotificationIfAvaliable` 20 times to retrieve them all. Once a notification has been shown, our lib will update the user's profile so that the same notification won't be in the decide response again.
