### ISSUE TITLE
Regarding the eclipse library

### ISSUE THREAD

**Issue by chandu4ugandhi** [mixpanel/mixpanel-android#164]
Can you provide the eclipse library. I went over the Github but its providing library for the Android studio with gradle system. 
Please reply asap.

**Comment by joeatwork** [comment]
You can use the library in eclipse by downloading the source code. The instructions for using Mixpanel with Eclipse can be found here:  https://mixpanel.com/help/reference/android-eclipse/

Thanks for your interest!
