### ISSUE TITLE
Sharing SuperProperties over different instances?

### ISSUE THREAD

**Issue by sirvon** [mixpanel/mixpanel-android#166]
If I have a baseActivity and a few classes that both instantiate a mixpanel instance.

```java
mMixpanel = MixpanelAPI.getInstance(this, baseApp.MIXPANEL_TOKEN);
```

will both those instances share super properties or is instantiating a mixpanel instance basically creating a new one with a separate super properties?

**Comment by joeatwork** [comment]
Super-properties will be token - Each token will have it's own super properties.
