### ISSUE TITLE
In-App push notifications not working on large screens

### ISSUE THREAD

**Issue by mwlodarczyk** [mixpanel/mixpanel-android#184]
I found an issue with In-App push notifications:

On devices that have large screens (more than 720 px) in-app pushes do not work. I checked in code and you try to download image with @4x suffix, which is not available on the server. The FileNotFound exception is called and push is ignored. We pull'ed the codes and we are working on a fix (try to download 4x if exists, if not try to download 2x, if not try to download the original image). We will send a patch if we have one.

Looking forward for comments from you.

Michal Wlodarczyk

**Comment by jbwyme** [comment]
Thanks for this report. I was looking through our access logs the other day
(for an unrelated issue) and I noticed some @4x requests. I didn't realize
the Android lib was the guilty party! @joeatwork should be able to provide
you with more details.

On Mon, Mar 16, 2015 at 1:47 AM, Michał Włodarczyk <notifications@github.com

**Comment by mwlodarczyk** [comment]
I did some fixes in code to make in app pushes work correctly. As I said before: I try to download @4x image, if it fails I try @2x image. Are you able to review this code and add new 4.5.3 release? We are working with MixPanel and are not able to release new version of our app without this fix. It would be easier for us to put it here instead of supporting our own branch.

**Comment by mwlodarczyk** [comment]
The pull request is here: https://github.com/mixpanel/mixpanel-android/pull/186

**Comment by joeatwork** [comment]
Thanks so much for the report, AND for the fix! I've merged your changes in #186 into our release candidate branch, and it'll be in the next release of the library.

Thanks again!

**Comment by yinfeiru** [comment]
#186 has been merged in.
