### ISSUE TITLE
Make OnMixpanelUpdatesReceivedListener public for use with addOnMixpanelUpdatesReceivedListener

### ISSUE THREAD

**Issue by mwlodarczyk** [mixpanel/mixpanel-android#188]
I want to call showPushNotificationsIfAvaiable on my app's main screen once new notification arrived. I though about using OnUpdateListener, but it turned it can be accessed only through mixpanel's package. I think that this should be made public. Is it possible to make this public? Would'nt it break the code? Looking forward to hearing from you.

**Comment by joeatwork** [comment]
The good news is `OnMixpanelUpdatesReceivedListener` will be public in version 4.5.4 of the library. However, showing in-app notifications on callback might not be the best approach for notification management.

We don't make any guarantees about when in-app notifications arrive, and if you have multiple notifications they will all tend to arrive at once. We also may change when we check for notifications in future versions of the library, which could lead to inconsistent user experience if you're relying on the timing of checks to determine when to display notifications (for example, at this writing, the iOS library only checks for notifications when the application is first started.)

If you're not using the automatic notification timing, we recommend just calling  `showNotificationIfAvailable ` whenever the user experience for a Notification is appropriate. The call is very efficient, and doesn't involve a network request.

**Comment by yinfeiru** [comment]
This feature is available in the latest lib.
