### ISSUE TITLE
Show Bolts library log message exactly once

### ISSUE THREAD

**Issue by joeatwork** [mixpanel/mixpanel-android#195]
We probably need to see the "Please install the Bolts library >= 1.1.2 to track App Links: bolts.AppLinks" exactly once per run. Let's make that happen.

**Comment by danielgomezrico** [comment]
I´m using parse and 'compile 'com.parse.bolts:bolts-android:1.2.1' but the error continue

**Comment by yuhaocan** [comment]
how to reslove
