### ISSUE TITLE
Feature request: Event Properties calculated on demand

### ISSUE THREAD

**Issue by jfsso** [mixpanel/mixpanel-android#198]
A great addition to the default event properties would be the screen orientation at the time the event happened. This was a very important state for us to know in some analysis and I guess many more people would benefit from this one if it is available in the SDK from the beginning.

An even more nicer addition would be to let us developers set some sort of event interceptor that we could use to add needed properties for events as they happen. Perhaps an API like `MixpanelAPI.getInstance(this, MIXPANEL_API_TOKEN, new EventInterceptor())`.

**Comment by arittr** [comment]
@jfsso I agree that this would be killer, and I'm going to put in a request to get this added. for now you might want to try grabbing orientation with Activity.getResources().getConfiguration().orientation or something similar. you can then manually add this to the event:

JSONObject props = new JSONObject();
try {
     props.put("orientation", this.getResources().getConfiguration().orientation);
} catch (JSONException e) {
     e.printStackTrace();
}
mMixpanel.track("some event", props);

ORIENTATION_PORTRAIT=1 and ORIENTATION_LANDSCAPE=2 - you can parse these names out if you want more human-readable info. you can also infer the orientation by the default screen height and screen width properties - if width > height you know the device is in landscape mode. 

can you explain this EventInterceptor a bit more - I just want to make sure I understand the use case before I bring it to engineering. thanks for all the feedback here!

**Comment by jfsso** [comment]
Thanks @arittr !

Explaining about the "EventInterceptor" a bit more... in an app we're building, there are a few properties we want to add to events to know about the device's current state at the time the event happens. One example in our case is the speed a car is traveling when interacting with our app. This isn't something that can't be done using global properties, but it is just so inefficient to keep updating those properties every time there's a increase/decrease in speed and would be great to only care about querying our speed calculator module to grab the current speed when the event happens.

So a class implementing the EventInterceptor will receive all Events and there it has the opportunity to add more properties to them. I understand that this will make more sense only for edge cases and that the majority of Mixpanel SDK users wouldn't care, but will be great deal for apps like ours that need a few extra properties to analyse user behaviour. :)

**Comment by arittr** [comment]
oh i see - thanks for the detail @jfsso ! I think the best thing to do here would be to just wrap the .track call with some code that adds in the property before calling .track - it would look like the above code, just synchronized to the mixpanel object and called something a bit different (like TrackWithIntercept). that way you can just call your custom track without the JSON puts to keep the code clean. that being said I'm going to put this into our feedback tracker to see if i can get it added for a later release. thanks for all the info here!

**Comment by joeatwork** [comment]
@jfsso this actually sounds like a broadly useful tool- being able to install some sort of computed property sees like it would solve not only your case, but a number of advanced Mixpanel cases. There is a lot to think about to make it work, but I think this feature, or something like it, should probably go into the library!
