### ISSUE TITLE
Use Google Advertising ID for default distinct_id

### ISSUE THREAD

**Issue by robertott** [mixpanel/mixpanel-android#201]
There is curiosity around whether Mixpanel should use Google Advertising ID (https://developer.android.com/google/play-services/id.html) as a value for distinct_id as opposed to using a randomly generated hash string. 

Benefits may include persistence of ID if app is deleted and re-installed.

Thanks!

**Comment by joeatwork** [comment]
We should do this generally- it makes Android lib behavior more consistent with the iOS lib, and seems just generally useful. The first step will be to make sure we're familiar with Google's policy surrounding the id, what circumstances it is present or missing, etc.

**Comment by joeatwork** [comment]
Because the Google Advertising ID is part of play services, we may need to work around missing play services to provide this feature.

**Comment by bsjut** [comment]
Is there an update on this issue? Having stored the Google Analytics Advertising ID would probably also allow the Mixpanel Webhoooks feature to be used to get Mixpanel analytics segments back into other mobile advertising attriubtion solutions, i.e. adjust. Then the payload would include the required ID to match that back to a device in another mobile marketing attribution system

**Comment by jdsadow** [comment]
Ping on whether there are any updates, @joeatwork

**Comment by joeatwork** [comment]
@robertott, @ryanseams, or @patedit might have more insight about this - any thoughts?

**Comment by ryanseams** [comment]
Making Google Advertising ID the default distinct_id is not possible as it will break existing implementations which take advantage of a [random identifier as distinct id](https://mixpanel.com/help/questions/articles/how-do-mixpanels-libraries-assign-distinctid-by-default). Given it cannot be the default, the potential changes here for adding AID would be:

- Add a config option to choose if the Google AID should be the distinct ID or not
- Add the Google AID as a [default super property and people property](https://mixpanel.com/help/questions/articles/what-properties-do-mixpanels-libraries-store-by-default)

Both of these could be implemented for the sake of allowing this as a primary identifier and/or data which can be utilized in Mixpanel reporting/notifications.

Thoughts @patedit ?

**Comment by patedit** [comment]
We should use Google Ad ID as the default unique user identifier in Android (parity with iOS). Since there are cases where Google Ad ID may not be available, the random generated distinct id should be our fallback solution.
So we are backwards compatible, we need to check the existence of a mixpanel distinct id in the device. If we do have it, we should keep using that random generated string.
I do not have a timeline for this enhancement request but it's definitely on our radar and will update this ticket as soon as it's done. Thanks guys!

**Comment by evalenciano** [comment]
Have there been any updates? I'm wondering if Mixpanel uses the Google Ad ID for anything.
