### ISSUE TITLE
make miniNotificationPresentationTime easily configurable like iOS

### ISSUE THREAD

**Issue by arittr** [mixpanel/mixpanel-android#202]
In iOS this can be easily changed by modifying L152 ( https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/Mixpanel.m#L152 ), while changing this in Android requires forking the library and editing a variable deep in the in-app stack ( https://github.com/mixpanel/mixpanel-android/blob/master/src/main/java/com/mixpanel/android/mpmetrics/InAppFragment.java#L262 ). We should move this to MPConfig.java to make things easier.

**Comment by joeatwork** [comment]
This is already configurable on iOS, so allowing it would be parity.
