### ISSUE TITLE
Issue with tools:ignore="AllowBackup" in AndroidManifest.xml

### ISSUE THREAD

**Issue by fabiozo** [mixpanel/mixpanel-android#207]
Due to presence of tools:ignore="AllowBackup" in https://github.com/mixpanel/mixpanel-android/blob/v4.5.3/src/main/AndroidManifest.xml file I'm not able overwrite that attribute in my project.

The only solution was to copy "mixpanel-android" project to my project and get ride of tools:ignore="AllowBackup" from application node.

**Comment by joeatwork** [comment]
Thanks for this report! We definitely don't want to cause problems like this.

**Comment by jayeti** [comment]
I have the same problem. Any updates when it would be fixed?

**Comment by zawadz88** [comment]
+1

**Comment by yinfeiru** [comment]
Closing this and will track this issue at #314

**Comment by patedit** [comment]
@zawadz88 @jayeti @fabiozo Issue is fixed in the latest stable release [4.8.0](https://github.com/mixpanel/mixpanel-android/releases/tag/v4.8.0)
