### ISSUE TITLE
Fine grained dependency for Google Play Services

### ISSUE THREAD

**Issue by hvisser** [mixpanel/mixpanel-android#212]
The docs don't make it clear which part of Google Play Services is used by the Mixpanel SDK (I assume gcm?). Because Google Play Services is huge it would be better to specify the exact dependency like    `compile 'com.google.android.gms:play-services-gcm:7.0.0`. This helps for apps that would otherwise hit the dex limit.

**Comment by joeatwork** [comment]
That's true! This is bad enough of a docs issue to be a bug. Thanks for the report!

**Comment by pjq** [comment]
Yes has the same issue, the methods count is more than 65536, because of the Google Play Services. Refer to https://www.contentful.com/blog/2014/10/30/android-and-the-dex-64k-methods-limit/

**Comment by joeatwork** [comment]
We'll be including this information in the 4.5.4 docs (coming really soon now :)

For reference, here are all of the dependencies you'll need:

```
dependencies {
    compile 'com.google.android.gms:play-services-base:7.0.0+'
    compile 'com.google.android.gms:play-services-gcm:7.0.0+'
}
```
