### ISSUE TITLE
allow custom scheduling and flushing of events

### ISSUE THREAD

**Issue by dbachelder** [mixpanel/mixpanel-android#224]
I'd like to be able to use GCM Network Manager to pick an ideal time to send analytics events, so I'm not incurring radio start/wait penalty for just analytics. 

https://developers.google.com/cloud-messaging/network-manager

This would allow me to defer that work for a small amount of time in the hope that I can piggyback off another app, or my own app starting the radio for other user related work. 

maybe we could register a callback that is called when mixpanel decides it is ready to send events (based on the existing config, and behavior remains identical to today if there is no callback here)

``` java
MixpanelApi.registerFlushReadyListener(new FlushReadyListener() {
  // callback params could be used to help indicate an additional level of urgency 
  public void onFlushReady(int totalPendingEvents, long lastFlushTime) {
    // let the network manager attempt to find a window when the network is connected and active sometime in the next 120 seconds.
    OneoffTask oneoff = new OneoffTask.Builder()
                .setService(MixPanelFlushService.class)
                .setTag("mp flush")
                .setExecutionWindow(0, 120) // anytime in the next 120 seconds
                .setUpdateCurrent(true) // replace existing task  if it exists
                .setRequiredNetwork(com.google.android.gms.gcm.Task.NETWORK_STATE_CONNECTED)
                .setRequiresCharging(false)
                .build();
     GcmNetworkManager.get(MyApplication.this).schedule(oneoff);
  }
});
```

service that simply triggers the immediate flush of events when it is run by network manager

``` java
     class MixPanelFlushService extends GcmTaskService {
         @Override
         public int onRunTask(TaskParams params)  {
             MixpanelApi.flushImmediately();
             return GcmNetworkManager.RESULT_SUCCESS;
         }
     }
```

Thoughts?

**Comment by joeatwork** [comment]
This is really interesting! You may be able to fake it in the short term with `mixpanel.flush()` - It'll try to flush immediately in that case.

**Comment by dbachelder** [comment]
wont I run the risk of some buffer getting filled or MP trying to push events on its own schedule anyway?

**Comment by joeatwork** [comment]
The short answer is yes, you're right. Mixpanel will try to push events when some timeout has expired (by default, one minute) or when it has more than 40 events in the queue. The timeout can be disabled, the queue depth not so much - to make your scheme useful we'd need to provide a "wants to push" message. This also seems generally useful from a testing perspective!

**Comment by dbachelder** [comment]
yeah. the `registerFlushReadyListener` callback was my throwaway example for that message. 

Would love to see something that enables this usecase in a future version. Thanks for the consideration.
