### ISSUE TITLE
In-app notification styling

### ISSUE THREAD

**Issue by baolongnt** [mixpanel/mixpanel-android#230]
Feel free to close the issue if I am wrong but I could not  find anywhere in the docs how to style the in-app notification or implement my own screen. It looks a bit too iOS and it would be better if it uses our fonts and colors.

**Comment by joeatwork** [comment]
I'd like to leave this issue open - Android has it's own strong design language now, and it would be really nice to be consistent and natural (or even better, allow folks to provide their own branded styles if they wanted.)

**Comment by patedit** [comment]
We now have two different styles in both mobile platforms: light and dark. Hope that addresses this ticket. Thanks for your feedback @baolongnt !
