### ISSUE TITLE
Only using tweaks does not send an A/B test event to Mixpanel

### ISSUE THREAD

**Issue by ryanseams** [mixpanel/mixpanel-android#233]
If the only feature of A/B testing I use is tweaks, then there is no data sent to Mixpanel. The A/B testing dashboard is looking for an event called '$experiment_started' with a given 'experiment_id'.

In the library code, it appears this event is sent in the viewcrawler here:
https://github.com/mixpanel/mixpanel-android/blob/e93ed2edc0ffcd2c763d9e35655e9855970611fa/src/main/java/com/mixpanel/android/viewcrawler/ViewCrawler.java#L1021

The issue is that tweaks never calls this method. You can see the method handleEditorTweaksReceived below which is called upon a tweak being retrieved from Mixpanel:
https://github.com/mixpanel/mixpanel-android/blob/e93ed2edc0ffcd2c763d9e35655e9855970611fa/src/main/java/com/mixpanel/android/viewcrawler/ViewCrawler.java#L731-746

However, this method does not make a call to initializeChanges as the method for handleVariantsReceived does:
https://github.com/mixpanel/mixpanel-android/blob/e93ed2edc0ffcd2c763d9e35655e9855970611fa/src/main/java/com/mixpanel/android/viewcrawler/ViewCrawler.java#L748-758

If I make a UI change to my app it will send the $experiment_started event, but in some cases I prefer to run the entire test using ONLY tweaks. If this is the case, I will never see this information recorded in Mixpanel.

A workaround for now is changing the background slightly to force the event to send. A potential fix is to call $experiment_started either when a tweak is retrieved from the server or applied on the device.

**Comment by joeatwork** [comment]
Thanks, @ryanseams-mp ! This should be addressed in the next library release.

**Comment by yinfeiru** [comment]
Addressed in 4.6.2
