### ISSUE TITLE
Initial app open misses A/B test from Mixpanel?

### ISSUE THREAD

**Issue by ryanseams-mp** [mixpanel/mixpanel-android#234]
When I deploy an A/B test for all of my users, I would expect this is delivered on the immediate app open if this test is waiting. During my testing I have found this initial app open does not properly grab the experiment and apply it to the user.

Instead, on the next app background and then open, the test is then applied. This means if I am testing a signup flow on first app open then the test would not be delivered on time.

The culprit seems to be the call to look for a test, which is looking during the activity's onResume() method:
https://github.com/mixpanel/mixpanel-android/blob/e93ed2edc0ffcd2c763d9e35655e9855970611fa/src/main/java/com/mixpanel/android/mpmetrics/MixpanelActivityLifecycleCallbacks.java#L37-40

I fixed this by adding the below call to onCreate(), but it would be nice if the SDK picked up this test on the first app open for me instead of manually calling for it:
mMixpanel.getPeople().joinExperimentIfAvailable();

**Comment by joeatwork** [comment]
This is by design. Users can explicitly apply the test using calls to joinExperimentIfAvailable() if they prefer, but otherwise we avoid applying edits as soon as they arrive to prevent UIs from changing out from under the user.
