### ISSUE TITLE
Public listener to tweaks' updates

### ISSUE THREAD

**Issue by esdras-gb** [mixpanel/mixpanel-android#235]
Is there a way to keep listening tweaks' updates? Through  iOS SDK we can use MPTweakBind but I didnt find any class or method to do so using Android SDK. I only found addOnMixpanelUpdatesReceivedListener but it probably works only when I have a people object already setted. In my scenario I have to use Tweaks before the user provides any information and I want update the current view if the user receives a tweak update from Mixpanel A / B test settings.

**Comment by joeatwork** [comment]
I'm afraid we don't have a callback interface in this release other than addOnMixpanelUpdatesReceivedListener/joinExperimentIfAvailable- however, you can register a listener without calling people.identify - you should still get a callback when tweaks are received. We'll likely include a callback interface in a future version of the lib. (in fact, I'm going to promote this to an issue so we can track it for inclusion in the next release.)

**Comment by Syzygy2048** [comment]
Anyone working on this already with a solution on the horizon or do I need to fork the repo?

**Comment by Syzygy2048** [comment]
I forked and implemented this last week, but only committed it today since I didn't work since then. I'll create a pull request, in the meantime @esdras-gb feel free to use my fork. But I'll probably not maintain it anymore since I'm done with it.

**Comment by patedit** [comment]
In the latest release you can add listeners to tweak updates (https://github.com/mixpanel/mixpanel-android/releases/tag/v4.9.2) 👍
