### ISSUE TITLE
IntDef requires support-annotations library, can't be resolved in Eclipse

### ISSUE THREAD

**Issue by vinod1988** [mixpanel/mixpanel-android#237]
I have imported the mixpanel library successfully on  eclipse, after that i have added the google play services library and clean the project, its showing one error. below package error.

 android.support.annotation.IntDef;

android.support can not resolved error

**Comment by joeatwork** [comment]
Thanks for reporting this!

1) This is a bug in the library that we should fix! But

2) Here is a workaround- This is a dependency on the Android support-annotations library - if you add it, can you build?

Regardless, this dependency should be removed as long as we support Eclipse builds, but please let us know if you're able to add the support-annotations library and successfully build!

Thanks for your report!
