### ISSUE TITLE
Error building with mixpanel 4.6.+

### ISSUE THREAD

**Issue by yihuaqi** [mixpanel/mixpanel-android#245]
When I upgrade the mixpanel from 4.5.3 to 4.6.2, I got the following error message in proguard:

Warning:com.mixpanel.android.mpmetrics.Tweaks: can't find referenced class com.mixpanel.android.mpmetrics.Tweaks$TweakType
Warning:there were 1 unresolved references to classes or interfaces.
         You may need to add missing library jars or update their versions.
         If your code works fine without the missing classes, you can suppress
         the warnings with '-dontwarn' options.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)
:app:proguardRelease FAILED
Error:Execution failed for task ':app:proguardRelease'.
> java.io.IOException: Please correct the above warnings first.

This only happens when building with 4.6.+. I have to put -dontwarn to be able to build.

My question is that is there a way to solve this error without putting "-dontwarn", and whether putting "-dontwarn" will cause Tweak and A/B test not working properly.

Thanks

**Comment by patedit** [comment]
Hi @yihuaqi - sorry for the late response! Since this SDK is an open source one I would add
`-dontwarn com.mixpanel.**` on your proguard file to make sure codeless events and AB tests work properly. Let me know if you are concerned about code optimization and we can re-visit this.
