### ISSUE TITLE
Only include those google play services that are required

### ISSUE THREAD

**Issue by justincpollard** [mixpanel/mixpanel-android#248]
Right now you include the following in your `./mixpanel-android/build.gradle`:

```
// Note- *all* dependencies are marked as optional in our final
// pom! If you need a transitive dependency in the library, you'll
// have to change the bit in uploadArchives that marks all dependencies as optional.
dependencies {
    compile "com.google.android.gms:play-services:[3.1,)"
}
```

However, if Mixpanel does need to include some of Google Play Services, it can do so more granularly, for example:

```
compile 'com.google.android.gms:play-services-base:7.5.0'
compile 'com.google.android.gms:play-services-maps:7.5.0'
compile 'com.google.android.gms:play-services-location:7.5.0'
...
```

I'm not sure if using open ended versioning (i.e. [3.1,) ) affects your ability to do this, but it might be good to specify Mixpanel's requirements explicitly.

**Comment by jaydeep17** [comment]
+1

**Comment by rajuashok** [comment]
Yes please this would be great. In general I cant find any explanation as to what MixPanel is doing with gms (other than "improved push notification support"). What is MixPanel doing with pushes?

**Comment by martinvano** [comment]
@rajuashok check this: https://mixpanel.com/help/reference/android 
You should only need 
    compile 'com.google.android.gms:play-services-gcm:8.3.0'
    compile 'com.google.android.gms:play-services-base:8.3.0'

**Comment by yinfeiru** [comment]
Thanks guys! I have a pr for it!
#333

**Comment by justincpollard** [comment]
Sweet :-)

**Comment by eddieberklee** [comment]
Thank god this was clarified, trying to delay multidex in my apps as much as possible
