### ISSUE TITLE
Mixpanel user has received thousands of surveys

### ISSUE THREAD

**Issue by pkouretas** [mixpanel/mixpanel-android#258]
One of our users has received(?) 21K surveys, and has replied 19K times, according to the mixpanel dashboard. That obviously cannot be correct. What's happening here? 

Responses: 19429
SignUpDate: 1413483444
Surveys Received: 21663

**Comment by ryanseams** [comment]
hi @pkouretas thanks for bringing this up!

the numbers you are actually viewing here are the survey id and response group id for the user -- this is not the number of times the user has seen the survey or the number of responses they have provided.

if the user was sent another survey, you would also see the id for this survey and response group here. these properties are lists which will be appended to each time a new survey is shown to the user.

you can verify these are the survey id and response group id by going to the surveys tab and looking at the numbers which show in the URL within Mixpanel.

**Comment by yinfeiru** [comment]
Closing. Please re-open if you still have questions about this.
