### ISSUE TITLE
Detect package ID when using a build variant with different applicationId

### ISSUE THREAD

**Issue by bryant1410** [mixpanel/mixpanel-android#259]
I have a flavor (from "productFlavors") in Gradle which changes de applicationId. So I need to add this in `AndroidManifest.xml` in order to recognize R class:

```xml
<meta-data
    android:name="com.mixpanel.android.MPConfig.ResourcePackageName"
    android:value="ORIGINAL_PACKAGE_ID" />
```

I think it'd be better if the library can detect these cases.

**Comment by patedit** [comment]
@bryant1410 I feel your pain. I can't think of a way to know the original package name - do you have any suggestions?

**Comment by bryant1410** [comment]
Wow. Can't recall the problem exactly right now. But I have no suggestions.

**Comment by patedit** [comment]
If you modify the `applicationId` we haven't found a way to know the package name where `R` is located at runtime. Will close this - feel free to open it if you find something 👍

**Comment by abeemukthees** [comment]
I'm also using a different application id, not same as the package name. So in the manifest should I add the package name or applicationId ?
