### ISSUE TITLE
Updating MixPanel breaks negative padding in Toolbar

### ISSUE THREAD

**Issue by niftynei** [mixpanel/mixpanel-android#260]
I'm using a complex drawable type for the app icon in the toolbar.  Updating the mixpanel APK from `4.5.3` to `4.6.4` breaks the NavigationButtonStyle padding (it's set to a negative number).

Style for my navigation button:
```
<style name="ToolbarNavigationStyle" parent="@style/Widget.AppCompat.Toolbar.Button.Navigation">
        <item name="android:paddingStart">-72dp</item>
        <item name="android:scaleType">fitStart</item>
        <item name="android:gravity">start|center_vertical</item>
        <item name="android:layout_gravity">start|center_vertical</item>
    </style>
```

Drawable layout:
```
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@drawable/ic_arrow_left"
        android:right="108dp"
        android:top="48dp"
        android:bottom="32dp"
        android:left="12dp"
        />
    <item android:drawable="@drawable/ic_logo_padded"
        android:top="0dp"
        android:bottom="0dp"
        android:left="24dp"
        />
</layer-list>
```

With `4.5.3`
![screenshot_2015-09-09-21-20-30](https://cloud.githubusercontent.com/assets/1097769/9770539/a0ff4470-56fe-11e5-83e6-2e1a5b18b5f5.png)

Updated to `4.6.4`
![screenshot_2015-09-09-21-22-13](https://cloud.githubusercontent.com/assets/1097769/9770544/a984793a-56fe-11e5-84b6-9f3b324cdc33.png)

**Comment by yinfeiru** [comment]
@niftynei Can you please try this with the latest master? It might be related to #310 . If it's not fixed, can you please provide me your layout file? Or maybe create a project which is able to reproduce this issue? I was having trouble with reproducing it.

**Comment by yinfeiru** [comment]
I'll close this for now. Please re-open if you still have this issue.
