### ISSUE TITLE
Android M removes the Apache HTTP client in favor of HttpURLConnection

### ISSUE THREAD

**Issue by arittr** [mixpanel/mixpanel-android#268]
Android M (to be rolled out in the next few weeks) deprecates the Apache HTTP client (now org.apache.http.legacy) in favor of the HttpURLConnection class (which is supposedly more efficient anyway).  

http://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-apache-http-client
http://developer.android.com/reference/java/net/HttpURLConnection.html

We need to either 1) adjust our deps and gradle configs to import the legacy lib or 2) refactor to use the new class. @yinfeiru any opinions here?

**Comment by yinfeiru** [comment]
@arittr Thank you for being on top of this! I'm feeling really guilty that I didn't know Android M is coming out.
Fortunately, we don't have to do anything to this. We have a utility class called HttpService which does all the Http related stuff in the lib. And this class uses HttpURLConnection.
```
connection = (HttpURLConnection) url.openConnection();
```
@joeatwork great work (if you can see this)!

**Comment by tomxor** [comment]
@yinfeiru there are still some dependencies on the legacy package, specifically on `NameValuePair` and `BasicNameValuePair`.

example:
https://github.com/mixpanel/mixpanel-android/blob/ca5c0d9e74217c6d5ce5e9afa58397c5d1346a14/src/main/java/com/mixpanel/android/mpmetrics/AnalyticsMessages.java#L20-L21

**Comment by yinfeiru** [comment]
@tomxor you are right! I'll reopen and handle them. THANK YOU!

**Comment by joeatwork** [comment]
Thanks for the shout-out, @yinfeiru !

**Comment by arittr** [comment]
thanks @yinfeiru @joeatwork

**Comment by arittr** [comment]
@yinfeiru any status updates here?

**Comment by philippelaporte** [comment]
Guys it's been almost two weeks, this thing must come out by noon tomorrow!

**Comment by yinfeiru** [comment]
4.7-RC2 will support Android M

**Comment by yinfeiru** [comment]
Re-open this as the lib we added doesn't have a license..

**Comment by yinfeiru** [comment]
The master branch now supports Android M. Please check out the v4.7.0 release.
