### ISSUE TITLE
Notification.setLatestEventInfo is deprecated

### ISSUE THREAD

**Issue by arittr** [mixpanel/mixpanel-android#269]
We have some Notification-related methods for low API numbers that are deprecated ( https://github.com/mixpanel/mixpanel-android/blob/7f310bf93998f5932ebdfc717cbcdcf384677423/src/main/java/com/mixpanel/android/mpmetrics/GCMReceiver.java#L261 ) - we need to decide if we 1) want to drop support for API11 or 2) continue using the deprecated methods or 3) use alternative methods to get the job done.

**Comment by bricestacey** [comment]
This popped up for me today while upgrading play services to 8.1.0 from 7.8.0. It's blocking builds with an error. Do you know of any immediate workarounds or how timely a fix would be? I am on mixpanel 4.6.3.

**Comment by patedit** [comment]
@bricestacey this was fixed on the latest version (v4.7.0)(see https://github.com/mixpanel/mixpanel-android/commit/a32b31e0f5cb6c29113d4f0615c48a7f78e2c6fe). Sorry for getting back to you late!
