### ISSUE TITLE
Reserved/Special properties documentation incomplete

### ISSUE THREAD

**Issue by SleeplessByte** [mixpanel/mixpanel-android#270]
[Special/Reserved properties](https://mixpanel.com/help/questions/articles/special-or-reserved-properties)
[Default properties](https://mixpanel.com/help/questions/articles/what-properties-do-mixpanels-libraries-store-by-default)
[People JavaScript Setup](https://mixpanel.com/report/762961/setup/people/)
[People Android Setup](https://mixpanel.com/help/reference/android#creating_profiles)

Great inconsistency across the documentation. The `$created` and `$last_login` properties are only mentioned in the JavaScript documentation. The Special/Reserved documentation doesn't even mention either of them. 

There is no reference to the first two documents from the setup documentation; it can only be found if you search for it or know it exists.

**Comment by ryanseams** [comment]
hi @SleeplessByte thanks for writing this up!

in regards to the ```$created``` and ```$last_login``` people properties, the only list these would fall under is the [Special/Reserved properties](https://mixpanel.com/help/questions/articles/special-or-reserved-properties) as they are not defaultly sent by our libraries and are simply used for maximum readability and notification targeting within the UI.

i went ahead and made a change to document these properties and their purpose at the above link -- thanks for bringing this to our attention!

**Comment by SleeplessByte** [comment]
@ryanseams Great.

I also think you should link to those documents in the setup pages :)

**Comment by ryanseams** [comment]
thanks for the suggestion -- while this one is a larger change i cant guarantee will happen, it will certainly be taken into consideration by our product team!

**Comment by yinfeiru** [comment]
Closing. Please re-open if you still have questions
