### ISSUE TITLE
Incompatible Gradle wrapper.

### ISSUE THREAD

**Issue by yogurtearl** [mixpanel/mixpanel-android#272]
The gradle wrapper is version 2.4, but the Android plugin in version 1.1.0. 

You need at least android plugin version 1.2.0 if you are going to run gradle 2.4.

Please upgrade the Android plugin version to something newer ( e.g. 1.3.1 ).

**Comment by patedit** [comment]
Looks like it was already changed here https://github.com/mixpanel/mixpanel-android/commit/1af0f6af29dc8fa9b298be32c9025a5ef0c0d04d#diff-c197962302397baf3a4cc36463dce5ea

Thanks @yogurtearl for your help!
