### ISSUE TITLE
Drop support for building from Eclipse

### ISSUE THREAD

**Issue by yogurtearl** [mixpanel/mixpanel-android#275]
https://github.com/mixpanel/mixpanel-android/blob/ca5c0d9e74217c6d5ce5e9afa58397c5d1346a14/src/main/java/com/mixpanel/android/mpmetrics/MPConfig.java

```
// Unfortunately, as long as we support building from source in Eclipse,
    // we can't rely on BuildConfig.MIXPANEL_VERSION existing, so this must
    // be hard-coded both in our gradle files and here in code.
```

I suggest dropping support for building from Eclipse.

**Comment by yinfeiru** [comment]
Thanks for your suggestion! We've recently done an internal discussion about it as well. I wanted to get rid of Eclipse support as Google stopped maintaining ADT in June 2015. However, we believe there's a decent amount of Mixpanel users are still on Eclipse. As the next step, we'll find a way to figure out if that's the case and make a final call according to the result.
