### ISSUE TITLE
Add an option to disable ViewCrawler

### ISSUE THREAD

**Issue by yogurtearl** [mixpanel/mixpanel-android#276]
On Mixpanel 4.5+, there is a ViewCrawler the periodically processes messages on the main thread. 
ViewCrawler is needed for these features to work:
* Web Configuration
* A/B Testing
* Dynamic Tweaks.

But if you are not using those features, there is no reason to incur the performance hit of having extra things run on your main thread.

Please add the ability to disable ViewCrawler ( for those that don't need Web Configuration, A/B Testing, and Dynamic Tweaks )

**Comment by patedit** [comment]
Closing since it's already merged PR #313 

Thanks @yogurtearl !

**Comment by aneemtalukder** [comment]
is there a way to have tweaks without the viewcrawler? or perhaps any way to run A/B tests without having to use the viewcrawler? my use case is i would like to simply get my variant for the test and update the UI myself without mixpanel's UI tools (as cool as they are!)

**Comment by patedit** [comment]
Hi @aneemtalukder - sadly nope :(

**Comment by aneemtalukder** [comment]
ahh got it, thanks!
