### ISSUE TITLE
Context WeakReference

### ISSUE THREAD

**Issue by mbmc** [mixpanel/mixpanel-android#279]
Shouldn't context be stored as `WeakReference` in this [`Map`](https://github.com/mixpanel/mixpanel-android/blob/master/src/main/java/com/mixpanel/android/mpmetrics/MixpanelAPI.java#L2110)?

**Comment by patedit** [comment]
Hi @mbmc ! Thanks for reaching out and improving the SDK! Notice that `mContext` is an Application context and not an `Activity` context (https://github.com/mixpanel/mixpanel-android/blob/master/src/main/java/com/mixpanel/android/mpmetrics/MixpanelAPI.java#L300). For that reason I don't think it needs to be a `WeakReference`. What do you think? Would love to hear your thoughts. Thanks again!

**Comment by patedit** [comment]
Closing. Feel free to open it again.

**Comment by mbmc** [comment]
Correct, the applicationContext will go away with the app.
