### ISSUE TITLE
Setup up a Gitter chatroom for this repo

### ISSUE THREAD

**Issue by yogurtearl** [mixpanel/mixpanel-android#280]
If you login to https://gitter.im/ you can setup a chatroom, so we can discuss issues, PRs, etc

Chatroom should be here, after you create it.
https://gitter.im/mixpanel/mixpanel-android

**Comment by yinfeiru** [comment]
Thanks for the suggestion! However, we are not going to do it for now as Github is sufficient. I'll keep it in mind in case we do need something similar.
