### ISSUE TITLE
Not showing users in people->explore from android

### ISSUE THREAD

**Issue by darkovski88** [mixpanel/mixpanel-android#282]
Hello,
I'm trying to integrate mixpanel into my android app - but im having a small issue. It seems everything is added as it should. Events are tracked but I cannot see the users that login to my app. Its working from the ios app but android there are some troubles. Here is the code im using:
<code>
 public void mixpanelSendData(String eventName) {
        mixpanel = MixpanelAPI.getInstance(this, getString(R.string.mixpanel_apikey));
        User user = new User(this);
        try {
            PackageInfo pInfo = getPackageManager().getPackageInfo(getPackageName(), 0);
            JSONObject props = new JSONObject();

            props.put("Email", user.getUserData(User.USER_EMAIL));

            props.put("Android App release", pInfo.versionName);
            props.put("Android OS version", android.os.Build.VERSION.SDK_INT);
            props.put("Android device model", Devices.getDeviceName());
           Date now = new Date();
            props.put("$email", user.getUserData(User.USER_EMAIL));
            props.put("$created", now.toString());
            mixpanel.track("android " + eventName, props);
            mixpanel.flush();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
</code>

**Comment by cassiegamm** [comment]
Hi @darkovski88,

Solid question! Events and People are separate entities, which means you'll need to add additional code to create people profiles. 

You'll want to use the ```getPeople().identify()``` method in tandem with ```getPeople().set()``` to create people profiles for android users. Relevant documentation and examples can be found [here](https://mixpanel.com/help/reference/android#creating_profiles).

**Comment by yinfeiru** [comment]
@darkovski88 
Closing this. Please re-open if you still can't figure it out.

@cassiegamm thanks!
