### ISSUE TITLE
Crash when trying to display in-app as activity is stopped

### ISSUE THREAD

**Issue by ryanseams** [mixpanel/mixpanel-android#284]
In this scenario, the user is trying to display an in-app notification (specifically a mini version) and is experiencing a crash. This exception is occurring because the Mixpanel SDK attempts to render an in-app notification as the app goes to the background.

Due to the way Android manages activities, the activity is actually stopped before the in-app attempts to render, resulting in an [illegal state exception](http://www.androiddesignpatterns.com/2013/08/fragment-transaction-commit-state-loss.html).

To recreate this bug, you will need to target a user with an in-app and background the app as soon as the in-app notification attempts to render. While rare, there should be a check to prevent against the in-app rendering in this scenario.

Crash Log:
11-10 04:40:30.217 28127-28127/? V/MixpanelAPI.API: Attempting to show mini notification.
11-10 04:40:30.217 28127-28127/? D/AndroidRuntime: Shutting down VM
11-10 04:40:30.217 28127-28127/? W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41c19d58)
11-10 04:40:30.227 28127-28127/? E/AndroidRuntime: FATAL EXCEPTION: main
11-10 04:40:30.227 28127-28127/? E/AndroidRuntime: Process: com.ryanseams.mixpanel_playground, PID: 28127
11-10 04:40:30.227 28127-28127/? E/AndroidRuntime: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
11-10 04:40:30.227 28127-28127/? E/AndroidRuntime:     at android.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1323)
11-10 04:40:30.227 28127-28127/? E/AndroidRuntime:     at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1341)
11-10 04:40:30.227 28127-28127/? E/AndroidRuntime:     at android.app.BackStackRecord.commitInternal(BackStackRecord.java:597)
11-10 04:40:30.227 28127-28127/? E/AndroidRuntime:     at android.app.BackStackRecord.commit(BackStackRecord.java:575)
11-10 04:40:30.227 28127-28127/? E/AndroidRuntime:     at com.mixpanel.android.mpmetrics.MixpanelAPI$PeopleImpl$4.run(MixpanelAPI.java:1894)
11-10 04:40:30.227 28127-28127/? E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:733)
11-10 04:40:30.227 28127-28127/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
11-10 04:40:30.227 28127-28127/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:136)
11-10 04:40:30.227 28127-28127/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5091)
11-10 04:40:30.227 28127-28127/? E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
11-10 04:40:30.227 28127-28127/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515)
11-10 04:40:30.227 28127-28127/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
11-10 04:40:30.227 28127-28127/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
11-10 04:40:30.227 28127-28127/? E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
11-10 04:40:30.237 1247-1624/? W/ActivityManager:   Force finishing activity com.ryanseams.mixpanel_playground/.MainActivity

**Comment by fabiocarballo** [comment]
Any update on this issue? This is causing a huge number of crashes on our app.

**Comment by yinfeiru** [comment]
@fabiocarballo sorry about the late. I'm investigating this bug right now and will get back to you shortly.

**Comment by yinfeiru** [comment]
#300

**Comment by patedit** [comment]
@fabiocarballo You can update to the latest version [4.8.0](https://github.com/mixpanel/mixpanel-android/releases/tag/v4.8.0) that fixes this issue.
