### ISSUE TITLE
FlushInterval not working for release build

### ISSUE THREAD

**Issue by changxiangzhong** [mixpanel/mixpanel-android#285]
Thank you so much for making this project.

But we have experienced an issue. We have use the configuration option `com.mixpanel.android.MPConfig.FlushInterval` in the AndroidManifest.xml. We have set it to 1. 

It works fine for DEBUG build, but not RELEASE build - it seems like the value doesn't work for release build

**Comment by yinfeiru** [comment]
I don't think we support arbitrary flush interval in production. https://github.com/mixpanel/mixpanel-android/blob/master/src/main/java/com/mixpanel/android/mpmetrics/MPConfig.java#L264

Though there must be a good reason behind this, I don't know the full context. However, what I do know is that setting it to 1 sec (assuming you didn't mean 1 milliseconds which is really bad) will lead to a high power/data consumption.

**Comment by yinfeiru** [comment]
@changxiangzhong 
I'll close this ticket as the behavior is expected. Please let me know if you do need this feature and explain your usage case.

**Comment by patedit** [comment]
It works on debug builds because the default flush interval on debug is 1 second https://github.com/mixpanel/mixpanel-android/blob/master/src/main/java/com/mixpanel/android/mpmetrics/MPConfig.java#L171

And it should work on non debug builds as well since this parameter is customizable through `com.mixpanel.android.MPConfig.FlushInterval`. Re-opening.

**Comment by yinfeiru** [comment]
Well.. @patedit you are totally right (and I don't know what I was talking about).

@changxiangzhong I've tried it just now and it worked. If you add 
```
        <meta-data android:name="com.mixpanel.android.MPConfig.FlushInterval"
            android:value="1000" />
```
to your AndroidManifest under the `application` block, it will work. I don't exactly know what you did, but don't put an expression there (eg. 1 * 1000).
