### ISSUE TITLE
In-apps and Surveys delivered repeatedly with Adblocker enabled

### ISSUE THREAD

**Issue by ryanseams** [mixpanel/mixpanel-android#289]
When a user enables AdBlocker, it points Mixpanel URLs to localhosts, such as a mapping like the below for the AdBlocker 'AdAway':

127.0.0.1 mixpanel.com
127.0.0.1 www.mixpanel.com
127.0.0.1 api.mixpanel.com

That being said, this only blocks data going out to Mixpanel, not data being utilized by the SDK itself. In this scenario, the AdBlocker does not block decide.mixpanel.com, causing there to be a notification delivered to the device.

Then, because Mixpanel is blocked, the user is never marked as receiving the in-app or survey. The decide server will continue to serve the user this same notification over and over again since the $campaigns (in-app) or $responses (survey) property is not populated for the current user.

We may consider using some check where if the user has enabled AdBlock we choose not to show them an in-app or a survey.

**Comment by ryanjohns** [comment]
This is a real problem. We have received numerous complaints from pissed off users about notifications and surveys that continuously come back no matter how they dismiss them. All have been traced back to this exact issue. Ad blockers are increasingly more common on Android and whenever there is an intersection between a user with an ad blocker and a mixpanel notification/survey, it will result in annoyance for the user. Only the most dedicated users will reach out when stuff like this happens. Most will simply stop using the product and leave bad feedback in a public forum. This is extremely harmful to future user adoption and does real damage to a company's brand/image. I consider this to be an absolute show-stopper issue. Both of these products are essentially useless if they cannot be trusted to work as advertised.

**Comment by yinfeiru** [comment]
This sounds a serious problem. I'll make sure to look into it shortly.

**Comment by ryanseams** [comment]
@yinfeiru to add some additional color, this type of Ad Blocker requires that you root your device... So you will not be able to reproduce this on any Android device.

If we are not going to support issues like this on rooted devices, then this can likely be closed. If there is any way for this to happen without modifying the hosts file (which the rooted device does), we should definitely find a fix.

**Comment by ryanjohns** [comment]
I understand that it requires a rooted device. It is also very simple to detect when this happens and is an improvement to the current state of affairs. Resolve the host names of api.mixpanel.com and decide.mixpanel.com and if either returns `127.*` or `0.*`, consider the user to be offline. There is already a check in the SDK for online status where this could be incorporated and Android provides a method for doing DNS lookups, `InetAddress.getByName(String host)`. IMO it's lazy to not fix a known issue.

http://developer.android.com/reference/java/net/InetAddress.html#getByName(java.lang.String)

**Comment by ryanjohns** [comment]
I want to add that the proposed workarounds I've received from the mixpanel support engineers are not acceptable. They suggested 2 options which both have problems and both require customers like us to implement the same DNS check I just described.

1) Set the $ignore property on the user when DNS resolves to localhost. This doesn't really work directly and would require us to create an API to inform our servers when the situation arises and then we would update the user's MP profile to ignore the user. This stops all tracking for that user even from devices where this isn't a problem and from the server. We shouldn't stop push notifications/emails/analytics etc just for this one case.

2) Similar to 1 but add an attribute on our user model for users in this situation that we then pass on to the MP profile. When targeting notifications or surveys we would have to remember to set AND NOT blocked. This is not only difficult to remember for the non-technical folks configuring notifications but also requires ANDing conditions in your targeting. MP doesn't support mixing ANDs with ORs in targeting so this drastically limits the capabilities of who can be targeted.

**Comment by patedit** [comment]
Seems like decide.mixpanel.com is already part of AdAway blacklist (http://hosts-file.net/ad_servers.txt). However, it's worth to implement a fix in case some clients are using local information and/or other adblockers that use different lists where decide.mixpanel.com is not include (e.g. http://winhelp2002.mvps.org/hosts.txt)

PR #316 

@ryanjohns feel free to comment on the PR.

**Comment by ryanjohns** [comment]
@patedit Thanks so much! Good solution using `isLoopbackAddress()` combined with `isAnyLocalAddress()` as that will handle all cases on both IPv4 and IPv6.

AdAway added decide.mixpanel.com at the request of one of your support engineer back in November to help mitigate this issue which is why it is now included. Users with older block lists or other ad blockers might still be affected like you mentioned. Thanks again.

**Comment by patedit** [comment]
Issues has been merged to master. You're welcome @ryanjohns !

**Comment by patedit** [comment]
@ryanjohns This fix is included in the latest release [4.8.0](https://github.com/mixpanel/mixpanel-android/releases/tag/v4.8.0)

**Comment by ryanjohns** [comment]
@patedit Thanks so much, we will update for our next release.
