### ISSUE TITLE
A/B Testing is not activated via flip gesture on M

### ISSUE THREAD

**Issue by skyisle** [mixpanel/mixpanel-android#291]
After short investigation, calculated totalGravitySquared on FlipGesture class is always out of range.

**Comment by yinfeiru** [comment]
@skyisle Are you still observing this issue? Since the sensor we are using is `TYPE_ACCELEROMETER`, the acceleration value is used in the calculation but not the flipping angel. Can you please try to slow it down and see if it helps?

`MINIMUM_GRAVITY_FOR_FLIP` and `MAXIMUM_GRAVITY_FOR_FLIP` are just experimental values. If they bother our users a lot, we'll definitely spend more time on tuning them.

**Comment by danielgomezrico** [comment]
Same thing happens on Nexus 4 with 5.1.1 but it works with samsung galaxy s6 with 5.1.1, not sure whats happening.

**Comment by yinfeiru** [comment]
@danielgomezrico I think they have different the sensors which leads to different results. I've tried it on a Nexus 5 and it works good. Have you tried to flip the phone slower? Or it just doesn't work at all?

**Comment by patedit** [comment]
@skyisle What is the device you were using?

**Comment by danielgomezrico** [comment]
@yinfeiru it dosent work at all. is there any way to print logs?

**Comment by yinfeiru** [comment]
@danielgomezrico Hmm.. That's no good. I'll find a Nexus 4 and test it out.

**Comment by yinfeiru** [comment]
@danielgomezrico I've tested it just now on a Nexus 4 with 5.1.1 which is exactly what you had and I was able to connect to the A/B builder.
Can you send me your log? If you search for `flip` in the log, you'll see something like
```
02-03 12:11:23.668 18831-18831/com.mixpanel.example.hello V/MixpanelAPI.FlipGesture: Flip gesture begun
02-03 12:11:25.885 18831-18831/com.mixpanel.example.hello V/MixpanelAPI.FlipGesture: Flip gesture completed
02-03 12:11:27.898 18831-18831/com.mixpanel.example.hello V/MixpanelAPI.FlipGesture: Flip gesture begun
02-03 12:11:34.547 18831-18831/com.mixpanel.example.hello V/MixpanelAPI.FlipGesture: Flip gesture completed
```

**Comment by yinfeiru** [comment]
@danielgomezrico also, it'd be helpful if you print out the value of `totalGravitySquared` `smoothed[2]`
https://github.com/mixpanel/mixpanel-android/blob/master/src/main/java/com/mixpanel/android/viewcrawler/FlipGesture.java#L28

**Comment by sayoojvalsan-demandmedia** [comment]
I have the same issue with N. Glad I found this page. I am going to test on emulator now with Android 5.1

**Comment by patedit** [comment]
For future reference: if someone is experiencing this issue notice that we also take in consideration the amount of time that the gesture takes. If you do the flip too fast we won't recognize the gesture. The movement of facing the phone to the table should take around a second. You should then wait another second before flipping it back.
