### ISSUE TITLE
Android 5 permission issue (duplicate permission RECEIVE)

### ISSUE THREAD

**Issue by mlostekk** [mixpanel/mixpanel-android#296]
Hello out there, i am fine with mixpanel with each version, but not Android 5.

I am using the permissions like that (in order to get it running on 6)

    <permission android:name="com.google.android.c2dm.permission.RECEIVE"/>
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />

But here i get the following error during installation

    INSTALL_FAILED_DUPLICATE_PERMISSION perm=com.google.android.c2dm.permission.RECEIVE

Any suggestion?

**Comment by ryanseams** [comment]
hi @mlostekk thanks for writing in! it looks like [this issue](http://stackoverflow.com/questions/27043933/install-failed-duplicate-permission-c2d-message/27456355) commonly happens on Android 5.x when updating an existing app and not installing a new version of the app.

can you confirm this error is on an upgrade of the current app and not a new install? if so, do you mind going to Settings > Apps, uninstalling the app, and then installing again to see if this fixes the issue?

**Comment by mlostekk** [comment]
well, sorry for asking so fast.. 

but i played around with it and see that when i use *only* the ```<uses-permission>``` tag, then it works fine on android 4, 5 and 6.

**Comment by mlostekk** [comment]
oh, and yes i did try uninstalling, cache clearing all that stuff

**Comment by ryanseams** [comment]
no worries! the ```<permission android:name="com.google.android.c2dm.permission.RECEIVE"/>``` is for older API levels, so if you are not supporting these in your app anyways you should be fine removing this tag

**Comment by mlostekk** [comment]
ah okay. i thought its needed for the manual permission request on android 6. seems i have to read that doc :)

thanks!

**Comment by ryanseams** [comment]
feel free to let me know if you run into any problems with this approach as you implement!
