### ISSUE TITLE
Won't Compile with other 3rd Party Libraries if minSdk do not match

### ISSUE THREAD

**Issue by sushiisumii** [mixpanel/mixpanel-android#298]
By including <code>tools:ignore="GradleOverrides"</code> in the AndroidManifest.xml file, this makes the use of the <code>tools:overrideLibrary</code> attribute impossible.

For example, if another 3rd party library has a <code>android:minSdkVersion="16"</code> but our main app has a minSdk of 10, you can use

    <uses-sdk android:minSdkVersion="10"
    tools:overrideLibrary="com.example.lib" />

in the Manifest to ignore compilation failure when the Manifest files are merged. Without doing this, the entire project will not be buildable with the Manifest merger failing. 

By ignoring the GradleOverrides, it ignores all overrides for the entire project, including other library dependencies, not just the Mixpanel library.

(see <link>http://stackoverflow.com/questions/31062893/android-gradle-manifest-merger-failed</link>)

**Comment by yinfeiru** [comment]
@patedit has a pr for this at #318

**Comment by yinfeiru** [comment]
@sushiisumii the pr has been merged. it will be in the next release which is coming soon.

**Comment by patedit** [comment]
@sushiisumii Problem solved on the latest release [v4.8.0](https://github.com/mixpanel/mixpanel-android/releases/tag/v4.8.0)
