### ISSUE TITLE
Tweaks not applying if not included in Application or MainActivity classes

### ISSUE THREAD

**Issue by ryanseams** [mixpanel/mixpanel-android#299]
When Mixpanel applies a Tweak, it does so by searching only the current class. If I define my Tweak in the Application class or my MainActivity, everything works as expected and Mixpanel applies the correct value as it is automatically fetched from the server.

If I instead define my Tweak outside of these classes, for example in a new class which does not inherit MainActivity, the Tweak will be received from Mixpanel but not applied like:

```
01-15 15:52:09.515 8853-8894/com.ryanseams.mixpanel_playground V/MixpanelAPI.DChecker: {"notifications":[],"surveys":[],"variants":[{"tweaks":[{"name":"Game speed","encoding":"d","maximum":null,"value":10,"minimum":null,"type":"number"},{"minimum":null,"type":"boolean","name":"Show ads","value":false,"maximum":null}],"actions":[],"id":20367,"experiment_id":10171}]}
01-15 15:52:09.515 8853-8878/com.ryanseams.mixpanel_playground W/MixpanelAPI.Tweaks: Attempt to set a tweak "Game speed" which has never been defined.
01-15 15:52:09.515 8853-8878/com.ryanseams.mixpanel_playground W/MixpanelAPI.Tweaks: Attempt to set a tweak "Show ads" which has never been defined.
```

This logging occurs despite having the Tweak defined somewhere within my application.

In this scenario, any Tweak defined in this way will always assume the default value and will not receive the value from the experiment unless the activity is restarted (app closed and opened again).

If this is desired behavior, it can be made more clear through the docs; however, one might argue these Tweaks should be applied no matter where they are defined within the application -- this could be accomplished by re-applying the cached experiment on each new activity, for example.

**Comment by yinfeiru** [comment]
This could be an interesting feature down the road, but I don't think we are going to do it for now since:
1. there's an easy workaround
2. not an actual bug
3. not a lot of people asking for it

I've put this feature request in our internal tracking system and I'll close this for now. Please re-open if there's a bigger demand.
