### ISSUE TITLE
Be less verbose in logcat

### ISSUE THREAD

**Issue by RomainPiel** [mixpanel/mixpanel-android#319]
I can see a few logs coming in the release version of my app from Mixpanel SDK:

```
W  com.mixpanel.android.surveys.SurveyActivity is not registered as an activity in your application, so surveys can't be shown.
I  Please add the child tag <activity android:name="com.mixpanel.android.surveys.SurveyActivity" /> to your <application> tag.
```

I think this should go under a lower level like `debug`. We don't necessarily want to expose to the world that our app is not using a `SurveyActivity` :)

**Comment by patedit** [comment]
Hi @RomainPiel ! Thanks a lot for the feedback. You're completely right. I've been thinking about changing all the Log.X to a custom Logger to fix all these issues. Will keep this ticket open until this is solved. Thank you :)

**Comment by dommerq** [comment]
:+1: on that :crying_cat_face:

**Comment by dbarwacz** [comment]
Same on `W/MixpanelAPI.Tweaks: Attempt to set a tweak "X" which has never been defined.`. There is quite a few for me, each time every activity is opened.

**Comment by patedit** [comment]
Guys, we now use a custom logger `MPLog` and you can set the minimum level of logs that will be printed out. Eg: `MPLog.setLevel(MPLog.ERROR)`
