### ISSUE TITLE
SDK depends on all play-services

### ISSUE THREAD

**Issue by assiziv** [mixpanel/mixpanel-android#326]
Using the entire library adds permissions to the app (if you include play-services-wallet for example, which I assume is not needed by MP).

Can this:
`dependencies {`
`    compile "com.google.android.gms:play-services:[3.1,)"`
`}`

Be replaced with this (not sure what's the base version you need, but depending just on base and gcm):
`dependencies {`
`    compile 'com.google.android.gms:play-services-base:8.3.0+'`
`    compile 'com.google.android.gms:play-services-gcm:8.3.0+'`
`}`

**Comment by yinfeiru** [comment]
@assiziv #333 
I'll simply follow what we did before which is `[3.1,)`.
