### ISSUE TITLE
Bluetooth automatic analytics are not thread safe

### ISSUE THREAD

**Issue by joeatwork** [mixpanel/mixpanel-android#33]
Automatic bluetooth analytics don't work if track() is called from a thread other than the main thread.

**Comment by danielgomezrico** [comment]
Why does mixpanel needs the bluetooth permission? what If I don´t add it?

**Comment by jbwyme** [comment]
We use it to attach whether or not a user has bluetooth enabled on your
events (as well as which bluetooth version). Nothing will happen if you
don't add it except you won't get that data.

On Wed, Jul 29, 2015 at 2:47 PM, Daniel Gomez Rico <notifications@github.com

**Comment by danielgomezrico** [comment]
:+1: thanks
