### ISSUE TITLE
Crash in HttpService.java, SDK 4.7.0

### ISSUE THREAD

**Issue by assiziv** [mixpanel/mixpanel-android#338]
Hi,

In checkIsMixpanelBlocked(), there's a catch to UnknownHostException. A few dozen of our users crashed on SecurityException.

Thanks,
Assi

**Comment by patedit** [comment]
Hi @assiziv I have fixed the issue and it will be available on the next release.

**Comment by assiziv** [comment]
Cool. Thanks!
