### ISSUE TITLE
The GET_ACCOUNTS permission is no longer needed for GCM to work

### ISSUE THREAD

**Issue by ismaeltoe** [mixpanel/mixpanel-android#339]
The GET_ACCOUNTS permission is no longer needed for GCM to work. So why is it needed in Mixpanel? Also, GET_ACCOUNTS is a dangerous permission wich makes it hard to manage on Android 6.0+ devices since in this case, it is used for Push notifications.

**Comment by patedit** [comment]
Thanks @ismaeltoe . You're right, GET_ACCOUNTS is no longer needed. I have updated the comment on the `AndroidManifest.xml` .

**Comment by julien1619** [comment]
Hi! This permission is still in your documentation here [](https://help.mixpanel.com/hc/en-us/articles/115004730006-Android-Push-Notifications-Guide)

Can you update it? Some of your users are using this page to configure their Push Notifications.

**Comment by patedit** [comment]
@julien1619 - thanks for pointing that out! Someone from our amazing support team just updated the doc :)
