### ISSUE TITLE
Fails to find R class even when meta-data tag is provided.

### ISSUE THREAD

**Issue by anupcowkur** [mixpanel/mixpanel-android#345]
We are using a different application ID than the one used in the `package` tag in the manifest file. The fix suggested by the SDK for this is to include a `<meta-data>` tag and provide the original package name.

In spite of providing this, the SDK is failing to pick up the R class.

Here are the details:

SDK version - `4.8.5`
API level - `23`
package name in manifest - `in.cleartax`
changed package name in apk - `in.cleartax.cleartax.dev`
R class package - `in.cleartax.R`
metadata declaration :
```
<meta-data
            android:name="com.mixpanel.android.MPConfig.ResourcePackageName"
            android:value="in.cleartax"/>
```
Are we doing something wrong?

**Comment by patedit** [comment]
Hi @anupcowkur - Are you seeing this message?
`MixpanelAPI.RsrcReader: Can't load names for Android view ids from 'in.cleartax.R$id', ids by name will not be available in the events editor.`

Are you using `gradle`?

**Comment by anupcowkur** [comment]
Yes and Yes.

**Comment by patedit** [comment]
Can I see your `gradle` file?

`AndroidManifest.xml` should have something like 

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="int.cleartax"
```

And your `build.gradle` should have something like:

```
buildTypes {
        dev {
            applicationIdSuffix '.cleartax.debug'
        }
}
```

**Comment by anupcowkur** [comment]
Sure. Please find the [gradle file here](https://gist.github.com/anupcowkur/b806125683832d7ebd1b9e2a3a110ce2).

**Comment by patedit** [comment]
Thanks @anupcowkur 

There is nothing wrong with that gradle file, and the meta-data is the right one. I'm wondering if it's the proguard configuration. If you disable proguard, does it still happen?

Could you also share with me the `AndroidManifest.xml` file? Thanks!

**Comment by anupcowkur** [comment]
Yeah. It happens on debug builds too. My proguard config already has a rule to keep the R class around.

Here's the [manifest file](https://gist.github.com/anupcowkur/9c3bd3d44b56283fd8b3fe01d6df70cb).

**Comment by anupcowkur** [comment]
Ended up handling this with our own GCM receiver. Had to integrate manually integrate GCM for other reasons anyway. Thanks for your help.
