### ISSUE TITLE
Blank screen on codeless event tracking

### ISSUE THREAD

**Issue by slmyldz** [mixpanel/mixpanel-android#349]
I didn't got error from logcat. (I activated Mixpanel logs) Device connected but can't stream device screen to website.  
![indir](https://cloud.githubusercontent.com/assets/5596316/14706673/d7f6750e-07c8-11e6-9877-39ae666e50b3.png)

**Comment by patedit** [comment]
@slmyldz Is that always happening? Have you tried using a different network (wifi/3g)? Do you have an extra device you can use to test?

**Comment by slmyldz** [comment]
@patedit I always getting blank screen. I navigated other areas but it still same. I could only got psd export and it is to big to upload. I can't got png export treeview. Maybe app treeview is so complicated.

**Comment by patedit** [comment]
@slmyldz Can you try the latest release 4.8.6 and let me know if it's still happening? Thanks!

**Comment by slmyldz** [comment]
@patedit I tried 4.8.6 and it works perfect. Thank you!
