### ISSUE TITLE
Add javadoc.jar and sources.jar on bintray

### ISSUE THREAD

**Issue by mreichelt** [mixpanel/mixpanel-android#355]
For easy debugging and convenience (and also because this is one big advantage of having an open source library :)) the mixpanel SDK should provide the appropriate JavaDoc and source files on bintray.
Compare the files of these two:

Files of https://bintray.com/bintray/jcenter/com.mixpanel.android%3Amixpanel-android/4.8.6/view#files/com/mixpanel/android/mixpanel-android/4.8.6
<img width="278" src="https://cloud.githubusercontent.com/assets/400322/14868308/4089e8d6-0ccd-11e6-8e2c-4db5fbf176b8.png">

Files of https://bintray.com/mreichelt/maven/webp-backport/view#files/de/marcreichelt/webp-backport/0.4.7
<img width="236" src="https://cloud.githubusercontent.com/assets/400322/14868323/4ea455be-0ccd-11e6-98c5-657a13031468.png">

The last one uploads all necessary files to bintray, including JavaDocs and sources.

Here are the build.gradle files that should make this work:
- https://github.com/mreichelt/webp-android-backport-library/blob/master/webp-backport/build.gradle
- https://github.com/mreichelt/webp-android-backport-library/blob/master/build.gradle

**Comment by dbarwacz** [comment]
Seeing decompiled classes with opensource sdk makes using sdk harder, it would be great to have sources attached automatically.

**Comment by patedit** [comment]
Thanks guys for your patience. I'm happy to say that starting on version 4.9.4 we have sources and javadocs included in the library!
