### ISSUE TITLE
Unable to build with proguard with API target under level 23

### ISSUE THREAD

**Issue by ryanseams** [mixpanel/mixpanel-android#364]
Proguard is throwing errors when building with the newest Mixpanel library versions for API targets under 23. The error arises out of the usage of ```getColor(Context context, int id)``` for API 23+ and ```getColor(int id)``` for all API levels below 23.

Since ```getColor(Context context, int id)``` is not available in the support-v4 library until API level 23, builds below this level pick up the method from Proguard and cannot find a reference to this method:

![image](https://cloud.githubusercontent.com/assets/9201737/15333776/e8e5fbf8-1c1f-11e6-874a-af876f3f16e9.png)

Even when building with API level 23, it does appear there is still an issue with this code from the logs:
```
05-17 11:13:27.937 20455-20455/com.example.ryanseams.simpletest I/dalvikvm: Could not find method android.content.res.Resources.getColor, referenced from method com.mixpanel.android.mpmetrics.q.c
05-17 11:13:27.937 20455-20455/com.example.ryanseams.simpletest W/dalvikvm: VFY: unable to resolve virtual method 343: Landroid/content/res/Resources;.getColor (ILandroid/content/res/Resources$Theme;)I
05-17 11:13:27.937 20455-20455/com.example.ryanseams.simpletest D/dalvikvm: VFY: replacing opcode 0x6e at 0x007f
```

It would seem a potential solution to this is to create separate methods for each version of ```getColor``` and use ```@TargetApi``` to specify which version should be used (like is being done in [notifications](https://github.com/mixpanel/mixpanel-android/blob/4e447e285973623c302f4a2ed8b7e69a3ab3a237/src/main/java/com/mixpanel/android/mpmetrics/GCMReceiver.java#L206-L212)).

**Comment by gogobebe2** [comment]
Hi, did you ever solve this issue? I'm having the same issue for my app "The Day Ahead".
`08-21 19:17:14.420 3805-4280/com.gmail.gogobebe2.thedayahead I/dalvikvm: Could not find method android.content.res.Resources.getColor, referenced from method com.gmail.gogobebe2.thedayahead.timetable.Period.highlight
08-21 19:17:14.420 3805-4280/com.gmail.gogobebe2.thedayahead W/dalvikvm: VFY: unable to resolve virtual method 699: Landroid/content/res/Resources;.getColor (ILandroid/content/res/Resources$Theme;)I`

When used here:
`    private void highlight(final int COLOUR_ID) {
        int colour;

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) colour = view.getResources().getColor(
                COLOUR_ID, view.getContext().getTheme());
        else colour = view.getResources().getColor(COLOUR_ID);

        view.setBackgroundColor(colour);
    }`

**Comment by patedit** [comment]
This issue will be solved with https://github.com/mixpanel/mixpanel-android/pull/373  - It's safe to don't warn for that error since at runtime the right api is selected.

@gogobebe2 You should specify on your proguard file not to warn for the class that is using that method. Alternatively, have you given a shot `TargetApi` annotation as @ryanseams mentioned? Thanks!

**Comment by gogobebe2** [comment]
Thanks for replying! But I solved my problem :)
```
    public void highlightAsCurrentSession() {
        highlight(android.R.color.holo_blue_light);
    }

    private void highlight(final int COLOUR_ID) {
        final int COLOR = ContextCompat.getColor(timetableFragment.getContext(), COLOUR_ID);
        timetableFragment.getActivity().runOnUiThread(new Runnable() {
            @Override
            public void run() {
                view.setBackgroundColor(COLOR);
            }
        });
}
```
