### ISSUE TITLE
timeEvent timer does not necessarily persist across sessions

### ISSUE THREAD

**Issue by ryanseams** [mixpanel/mixpanel-android#365]
When a user makes a call to ```timeEvent```, the SDK is currently storing these values in a [Map](https://github.com/mixpanel/mixpanel-android/blob/master/src/main/java/com/mixpanel/android/mpmetrics/MixpanelAPI.java#L2123). Due to the way this value is stored, when the instance of Mixpanel is removed (for example, by force quitting the app or through the phone invoking ```onDestroy()```), the start time of the original ```timeEvent``` is also removed.

The issue is that this Map is stored locally in the Mixpanel instance, and not on disk. The SDK should store this value on disk in order to ensure this value persists across sessions (which it does in iOS). Based on the other values stored to disk, this could be accomplished by storing the value in device shared preferences using the ```mPersistentIdentity``` object in ```MixpanelAPI```.

**Comment by patedit** [comment]
Thanks a lot @ryanseams for pointing it out! There's a PR out that will address this issue: https://github.com/mixpanel/mixpanel-android/pull/387

**Comment by patedit** [comment]
Available in the latest release.
