### ISSUE TITLE
Use of API 14 method while minSdkVersion is 9

### ISSUE THREAD

**Issue by hidroh** [mixpanel/mixpanel-android#366]
Hello, while testing my app against API 9, the app crashed due to `MixpanelAPI`'s use of `Application.registerActivityLifecycleCallbacks()`, which is only available from API 14, while `build.gradle` specifies `minSdkVersion` as 9.

**Comment by patedit** [comment]
Hi @hidroh - I am so sorry for the inconvenience. https://github.com/mixpanel/mixpanel-android/pull/368 should fix it. Thanks for the report!

**Comment by hidroh** [comment]
Thanks! Does this have any implication on how Mixpanel gathers data? Would it still considered work for for APIs below 14 or no?

**Comment by patedit** [comment]
@hidroh It does not have any implication on Mixpanel tracking. Android SDK supports API 9 and above. Some features are only available from API 14. For example, the SDK automatically flush the queues when the app goes to the background automatically so the developer don't need to call `flush()` on `onDestroy()` if the device is running API 14 and above. If the API is below 14 the queues are not flushed automatically and they will be flushed either on the next app session or when you manually call `flush()`. Also, we can automatically show notifications, surveys or apply AB test variants when an activity starts without you having to call `showNotificationIfAvailable()`, `showSurveyIfAvailable()` and `joinExperimentIfAvailable`. Let me know if you have any other question :)

**Comment by hidroh** [comment]
Great to know, thanks! I'm closing this, looking forward to the next release.
