### ISSUE TITLE
Add setting of large icon in notifications.

### ISSUE THREAD

**Issue by RossBines** [mixpanel/mixpanel-android#367]
Currently you can only change the small icon with the json key "mp_icnm" but this only updates the small icon.  In Android 5.0+ the large icon is made to be fully white so in the app we need to replace the large icon with an alternative so clients can display the correct notification icon.

The key "mp_icnm_l" could be used to indicate large icons.

**Comment by patedit** [comment]
Thanks for your feedback @RossBines - We will work on it and update this ticket as soon as it's done!.

**Comment by patedit** [comment]
PR is out @RossBines ! https://github.com/mixpanel/mixpanel-android/pull/386

Thanks for your feedback!
