### ISSUE TITLE
Customizing notification layout / styling

### ISSUE THREAD

**Issue by JakubHolovsky** [mixpanel/mixpanel-android#379]
Hello, is there any way to override how notifications are being displayed? Setting up a custom layout / styling, etc.?
Or do I have to handle this on the lower level API? Cheers

**Comment by patedit** [comment]
Hi @JakubHolovsky - We currently offer two different themes/styles to use for your notifications: dark and light. If you want to change the layout in a different way, you'd have to fork the sdk and change it yourself. Thanks for reaching out! :)
