### ISSUE TITLE
NPE on track method MixpanelAPI

### ISSUE THREAD

**Issue by DuM4ll3** [mixpanel/mixpanel-android#385]
Hi, I think this issue is related to #211 , here is the stacktrace:

`Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sample.app/com.sample.app.activities.SampleActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mixpanel.android.mpmetrics.w.a(java.lang.String, org.json.JSONObject)' on a null object reference at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2332) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2394) at android.app.ActivityThread.access$800(ActivityThread.java:154) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:135) at android.app.ActivityThread.main(ActivityThread.java:5276) at java.lang.reflect.Method.invoke(Method.java) at java.lang.reflect.Method.invoke(Method.java:372) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703) Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mixpanel.android.mpmetrics.w.a(java.lang.String, org.json.JSONObject)' on a null object reference at com.sample.app.activities.SampleActivity.com.mixpanel.android.mpmetrics.MixpanelAPI.track(SampleActivity.java:1541) at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1239) at android.app.Activity.performStart(Activity.java:6057) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2295) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2394) at android.app.ActivityThread.access$800(ActivityThread.java:154) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:135) at android.app.ActivityThread.main(ActivityThread.java:5276) at java.lang.reflect.Method.invoke(Method.java) at java.lang.reflect.Method.invoke(Method.java:372) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)`

**Comment by patedit** [comment]
Hi @DuM4ll3 - Looking at your stack trace it seems that your Mixpanel instance is null at that point.  Notice that this is different from the other crashes since in those cases we had nullified objects in our SDK due to race conditions. In this case, it's your `SampleActivity` mixpanel instance the one that is null. I can help you debug this issue if I you are okay with uploading the code somewhere and let me take a look! 👍

**Comment by DuM4ll3** [comment]
My mistake @patedit ! Should had looked the stacktrace with more attention . Sorry and thank you for your help! Will try harder this time to figure it out myself first. :)
