### ISSUE TITLE
Persisting tweaks

### ISSUE THREAD

**Issue by RomainPiel** [mixpanel/mixpanel-android#391]
We've just integrated our first a/b tests and we noticed the values of the tweaks are not persisted. So if the user is in cohort B and then kill/restart the app, the value of the tweak will be re-fetched.
- Is that on purpose?
- If it is, is there any plan to add persistency?
- Is there any harm if we persist it ourselves?

**Comment by patedit** [comment]
Hi @RomainPiel! I can definitely see the benefit of persisting tweaks. My concern is that you may load tweaks locally that were already removed remotely. That means that after a request, those tweaks will be removed and that could be a very odd user experience.
What is your user case and why do you need to persist them? I want to understand what you are going through :)

**Comment by RomainPiel** [comment]
Ah right, I see how it could be problematic if the tweak is removed remotely. I guess instead of removing it we could return the initial default value from the server.
So my use case is that I have a A/B test on my very first screen. So it can happen and it happens quite frequently that the tweak value is initialised with some delay after the view is rendered. I don't really want to wait for it to come back so the UX is a bit odd.
Caching it fixes it for the subsequent launches (not really for the first one but that's acceptable).
Thanks for your help!

**Comment by patedit** [comment]
Setting the initial value would be an equivalent of removing/updating a tweak after another one is loaded.
For your use case, I think it'd be an improvement if we persist the tweaks. However, you'd face the same situation as soon as you remove them remotely. If that's something that does not concern you, I'd like to implement this on the SDK in such a way that loading persisted tweaks does not happen by default unless you specify so in an Activity or in the app.
Alternatively, on our latest SDK release we provide callbacks when tweaks are updated (see changelog and how to set it up https://github.com/mixpanel/mixpanel-android/releases/tag/v4.9.2). In your app, would that be a solution? I.e. render the UI after tweaks are updated from the server.

**Comment by RomainPiel** [comment]
I agree, the best solution would be to handle it in the SDK because it has full context on wether the tweak still exists or not.
We have considered using `addOnMixpanelTweaksUpdatedListener()` but it wouldn't work for us, we don't want to block the UI until we get the experiments and we don't want to alter the UI after it has been rendered.

In any case, the problem of the tweak being removed on the server side is not a massive issue.
Assuming that version 1 has a 50/50 A/B test. Then eventually maybe B wins. We can set it to 100% B for a while. Then we roll out version 2 that only has feature B with no tweak check. After some time version 1 is not much used, we can drop the tweak remotely.

Obviously it would be awesome if the SDK was handling it, it would mean less code on our end and a cleaner implementation. But the remote deletion is not a biggie.

**Comment by RomainPiel** [comment]
Something that I could do (and that the SDK could do) is to set an expiration date on that cached value. That's what Google is doing with firebase remote controls: https://firebase.google.com/docs/remote-config/android#caching

**Comment by patedit** [comment]
@RomainPiel Thanks for the link! I see a lot of benefits persisting the tweaks moving forward. I will keep this in my radar but i can't give you an ETA at this moment. In the mean time, feel free to implement it on your side and open a PR. I'll be happy to review it.

Thanks!

**Comment by RomainPiel** [comment]
Cool, I'd be happy to help but I'm not very familiar with the code. So any quick walkthrough the potential changes would be greatly appreciated.
I've had a quick look at the code and it seems that there is [some persistency happening during initialization](https://github.com/mixpanel/mixpanel-android/blob/master/src/main/java/com/mixpanel/android/viewcrawler/ViewCrawler.java#L387-L390) in `ViewCrawler`. These `mPersistentTweaks` [are applied to the shared tweaks](https://github.com/mixpanel/mixpanel-android/blob/master/src/main/java/com/mixpanel/android/viewcrawler/ViewCrawler.java#L890). I'm wondering why these values are not reused after a re-launch.

**Comment by AamirAbro** [comment]
Does mixpanel iOS sdk persists toggles? -- because I guess it does. if yes can we check how they its implemented in iOS and can get better insights?cc @asifmujteba

**Comment by athkalia** [comment]
Any updates on this?

**Comment by patedit** [comment]
Starting on the next version (5.2.0) we will start persisting tweaks https://github.com/mixpanel/mixpanel-android/pull/492
Thanks for your feedback guys!
