### ISSUE TITLE
Control automatic flush interval

### ISSUE THREAD

**Issue by fabianbergmark** [mixpanel/mixpanel-android#393]
We use the Mixpanel SDK in our app to trace events. As our app mostly runs in the background, having a low battery consumption is very important. The automatic flush interval of 60 seconds is much to low for us. For us a reasonable interval would be one hour or more. Please provide ways to control this in your SDK.

**Comment by patedit** [comment]
Hi @fabianbergmark ! Thanks for reaching out. We already provide a way to customize params on the SDK (e.g. disable/enable features, change hard-coded vars, etc..).
For your specific case, check this out: https://github.com/mixpanel/mixpanel-android/blob/master/src/main/java/com/mixpanel/android/mpmetrics/MPConfig.java#L200

You only need to add the following to your `AndroidManifest.xml` if you want a flush interval of one hour:
```
        <meta-data
            android:name="com.mixpanel.android.MPConfig.FlushInterval"
            android:value="3600000"/>
```

Let me know if you have any other questions 👍
