### ISSUE TITLE
Inconsistent behavior with com.mixpanel.android.MPConfig.EnableDebugLogging property

### ISSUE THREAD

**Issue by fcduarte** [mixpanel/mixpanel-android#402]
Hi team,

I was reading through the SDK code and found out that most of the `Log.d()` and `Log.v()` calls are wrapped into a `if (MPConfig.DEBUG) {}` check .. But there are one or two cases where you also wrap a `Log.i()` call and all others  `Log.i()` calls doesn't have that check.

Question is:

1. Should you add all `Log.i()` under that check too?
2. If not that's not the case, then should you implement a way to completely turn off logs coming from the SDK? A LogLevel implementation, for instance, common practice on [famous](https://github.com/square/okhttp/tree/master/okhttp-logging-interceptor) libs.

I'll let you guys decide if this is a bug or a feature request :D

Thanks!

**Comment by patedit** [comment]
@fcduarte This is definitely a feature request and i'd love to see it in the SDK. There have been more requests like yours, I'll keep this ticket open until it's done - or you can open a PR as well :) Thanks a lot for reaching out!

**Comment by patedit** [comment]
Hi @fcduarte ! We now use `MPLog` internally to control what we log depending on the type of build (see https://github.com/mixpanel/mixpanel-android/blob/master/src/main/java/com/mixpanel/android/util/MPLog.java#L15).
You can also customize the minimum level you want the SDK to log (https://github.com/mixpanel/mixpanel-android/blob/master/src/main/java/com/mixpanel/android/util/MPLog.java#L17)
Thanks!
