### ISSUE TITLE
Disabling ViewCrawler disables A/B developer tweaks

### ISSUE THREAD

**Issue by AntonRutkevich** [mixpanel/mixpanel-android#403]
Hi Mixpanel team!

It's totally understandable that codeless event tracking and the magical part of A/B testing, where properties of the views can be modified directly via the Mixpanel Web UI, should not work when ViewCrawler is disabled with 

```
<meta-data android:name="com.mixpanel.android.MPConfig.DisableViewCrawler"
            android:value="true" />
```

But why should the simple [Developer A/B tweaks](https://mixpanel.com/help/reference/android#tweaks) stop working when the ViewCrawler is disabled? 
Developer A/B tweaks seems to be just loading of some JSON config and exposing it to the app via Tweaks API. 

From the code I see that Tweaks are handled inside of ViewCrawler, so this seems to be the reason, but don't you find that those things should not be coupled?

The reason why we don't want to use ViewCrawler is #264 .

**Comment by artem-zinnatullin** [comment]
Any update on this issue? We would like to use Developer A/B tweaks but keep `ViewCrawler` disabled as well.
