### ISSUE TITLE
Bug in In App Notification cta_url is null

### ISSUE THREAD

**Issue by BugsBunnyBR** [mixpanel/mixpanel-android#406]
Hi,
My Android app receives the In App Notification (IAN) and displays it, but when the user clicks in "Done" no action is triggered. Debbuging the SDK It look's like `cta_url` is null.
The same IAN works fine in iOS devices.

**Comment by cassiegamm** [comment]
@BugsBunnyBR  --- could you write into support@mixpanel.com with a link to the notification you've built so that they can help debug? 

The in-app notification builder requires separate cta_url's for android and iOS. If you included a cta_url for iOS, but not Android, the result would be null.

**Comment by BugsBunnyBR** [comment]
Thanks, I wrote and solved the problem. The mixpanel dashboard interface does not help much to see that android and iOS have separate cra_urls...
