### ISSUE TITLE
Tweak value always returns the default value for the first .get()

### ISSUE THREAD

**Issue by fabiocarballo** [mixpanel/mixpanel-android#407]
Hello,

I'm having a problem getting a tweak value.

The scenario is this one:
- I launch my main activity, wait about 10 seconds (just to let mixpanel to have time to fetch the data) and then launch a service that registers as a mixpanel update listener. The listener triggers and then I try to fetch the Tweak value. And it returns the default value. However, If I go to a different screen and then go back to the previous (to trigger all this flow again), it will return the correct value. And from that moment on it always fetches the correct value.
 
The problem is that if I kill and to this again, the first .get() will always return the default value.

The logs shows that mixpanel has received the correct data, however when Im trying to fetch the value it returns badly.

```
Mixpanel decide server response was:
                         V  {"notifications":[],"surveys":[],"variants":[{"tweaks":[{"minimum":null,"type":"boolean","name":"home_labels_tweak","value":true,"maximum":null}],"action
                            s":[{"property":{"classname":"android.widget.TextView","set":{"parameters":[{"type":"java.lang.Integer"}],"selector":"setTextColor"},"name":"textColor","
                            get":{"result":{"type":"android.content.res.ColorStateList"},"parameters":[],"selector":"getTextColors"}},"path":[{"index":0,"prefix":"shortest","id":169
                            08290},{"index":0,"mp_id_name":"content"},{"index":0,"mp_id_name":"coordinator_layout"},{"index":0,"mp_id_name":"fragmentContainer"},{"index":1,"mp_id_na
                            me":"pulling_rv"},{"index":0,"view_class":"android.widget.FrameLayout"},{"index":0,"mp_id_name":"swipeRefreshLayout"},{"index":0,"mp_id_name":"recyclerVi
                            ew"},{"index":0,"mp_id_name":"card_view"},{"index":0,"view_class":"android.widget.RelativeLayout"},{"index":0,"mp_id_name":"createPostPlaceholder"}],"arg
                            s":[[4289666594,"java.lang.Integer"]],"change_type":"property","name":"c864"}],"id":58102,"experiment_id":28812}]}
````
and a bit later on 

```
invoke(19) - Mixpanel updates received
D  invoke(24) - Updating home_labels_tweak Tweak.
D  updateTweak(34) - Found value: false
```

My logging code is equivalent to this:
````
 registeredTweaks = listOf(Pair("home_labels_tweak", MixpanelApi.booleanTweak("home_labels_tweak", false))

 for (tweakData in registeredTweaks) {
            val label = tweakData.first
            val tweak: Tweak<Boolean> = tweakData.second

            log("Updating $label Tweak.")
            val value = tweak.get()
             log("Found value: $value")
        }
    }
````

Am I doing something wrong? 

Thank you.

**Comment by patedit** [comment]
Hi @fabiocarballo - this seems similar to https://github.com/mixpanel/mixpanel-android/issues/472. Hopefully the PR solves your problem. Let me know if tomorrow's release does not fix your issue :)
