### ISSUE TITLE
NPE Attempt to invoke interface method 'void com.mixpanel.android.mpmetrics.MixpanelAPI$People.append(java.lang.String, java.lang.Object)' on a null object reference

### ISSUE THREAD

**Issue by miroslavign** [mixpanel/mixpanel-android#409]
We have NPE
https://gist.github.com/miroslavign/b4002219496ff824cf2501e6323551c5

How could we resolve this, or get more information about a crash?

**Comment by miroslavign** [comment]
Just to add, we are using version 4.9.2

**Comment by patedit** [comment]
Hi @miroslavign! You need to make sure you are identifying the user on the SDK in order to be able to track people data. Are you calling `mYourMixpanelInstance.getPeople().identify(aUserId)` ?

**Comment by miroslavign** [comment]
I am attaching the screenshots from prefs, where you could check the data. For one user (Nikola) 
it is not crashing, and for the other user (Manav) it is. As you can see, both are identified, am I right ?
Anything else from prefs or logs I could catch to help resolving this one ?

![mixpanelok_manav_prod](https://cloud.githubusercontent.com/assets/1773454/21256146/e418433a-c370-11e6-995a-fffa8448a64a.jpg)
![mixpanelok_mike_prod](https://cloud.githubusercontent.com/assets/1773454/21256149/e81b55ee-c370-11e6-9ab4-5225e1726b66.jpg)

**Comment by miroslavign** [comment]
Tnx, as both you and Joey from support suggested, in parallel to providing identify 
to mixpanel instance: 
        mixpanel.identify(userId);
we should provide the same to People object:
        ......
        mixpanel.getPeople().set("name", userName);
        mixpanel.getPeople().identify(userId);    <-- THIS one did the job
        .......

Tnx for help in clearing this out.

**Comment by patedit** [comment]
Glad it worked!
