### ISSUE TITLE
Using a single project for multiple apps differing by buildType

### ISSUE THREAD

**Issue by vibinr** [mixpanel/mixpanel-android#413]
I have two buildTypes in my build.gradle - beta and release, both differ by applicationIdSuffix and versionNameSuffix. They use the same project token. I sent some events from the beta app to a people profile created using release apk, and turns out they're ignored.

Similar case with notifications. I tried uninstalling the release apk and sending notification from Mixpanel to a people profile (who has beta apk), but it didn't work.

**Comment by vibinr** [comment]
Actually event tracking works just fine....I put a wrong project token before. My bad. But is there a way to make sure both beta and release apps get the notifications?

**Comment by cassiegamm** [comment]
Hi @vibinr,

Each profile in your project can only receive a unique notification once. If your beta and release versions both route to the same project, _and each user has one profile_, then users who receive an in-app notification on the beta app won't be qualified to get it again if they upgrade to the release version.  

If you maintain separate projects for the beta and release versions, then notifications shown to beta users won't impact the notifications they are eligible for if they move to the release version. Hope this helps!

**Comment by vibinr** [comment]
Thank you! But can we know which app receives the notification, if I have both beta and release versions - with package names `com.foo.beta` and `com.foo` respectively, installed side-by-side on my device? I think this depends on whether Mixpanel sends the GCM payload to a specific package or not.

**Comment by patedit** [comment]
that is handled by FCM/GCM. when you create a new project in FCM you need to specify the package name. you technically have two different apps (i.e. you can have both apps installed at the same time and each has its own folder, own preferences, own dbs, etc...). For your `beta` type you should consider it as a different app and I'd suggest creating a new project on Mixpanel and register that app on FCM and use that different API key for push notifications.
