### ISSUE TITLE
EditBinding  update UI per minute. Where is the application scenario?

### ISSUE THREAD

**Issue by 1198681139** [mixpanel/mixpanel-android#415]
Counld you describe it ?  Thanks

**Comment by 1198681139** [comment]
@zakj  I am learning the A/B Test. I find that EditBinding update UI per minute. Could you help me describe Where is the application scenario?

**Comment by 1198681139** [comment]
sorry I find that EditBinding update UI per second

**Comment by patedit** [comment]
Hi @1198681139 ! What exactly do you want to know about this class? Notice that it's a private one. Are you having issues with it?
This class is used to bind actions to views. For example, our codeless event feature rely on this class.

**Comment by 1198681139** [comment]
Hi @patedit ! I  am having issues with it. I am studying the implementation principle of Android visualization . What happens if I update UI only once in init ?Under what circumstances need frequent updates per second?

**Comment by patedit** [comment]
We will iterate (and apply changes) through the view hierarchy every time a new activity is created, when there is a change on the global layout (and its subviews) and every second in case there are new UI elements on the screen that don't change the visibility or state of the global layout. That way, we can assure that we don't miss any new UI elements on the screen 👍
