### ISSUE TITLE
EditState.mCurrentEdits is added unlimited

### ISSUE THREAD

**Issue by haibin80s** [mixpanel/mixpanel-android#418]
1.EditState.mCurrentEdits is added unlimited before called the setEdits .
2,Multiple tasks of EditBinding will perform when activity resume-pause-resume before gc.
3.Is there a need to perform the task of EditBinding per minute?Can do it one time at onresume?

**Comment by patedit** [comment]
See https://github.com/mixpanel/mixpanel-android/issues/415 

Let me know if you are seeing any performance issues.
