### ISSUE TITLE
Tweaks values not loading until an activity is stopped and resumed

### ISSUE THREAD

**Issue by AamirAbro** [mixpanel/mixpanel-android#423]
We have a teak defined in app and on mixpanel and the experiment is joined and mixpanel lib continue to return the default value until we move app to background or open some other activity and com back to the previous activity. 
ie: until pause/stop or start/resume lifecycle events on the main activity the uses that tweak are called.

Mixpanel lib version `4.9.3`.

Let me know if you need more info.

**Comment by AamirAbro** [comment]
any update guys! let me know how can help or if you need more info/context.

**Comment by cassiegamm** [comment]
Hi @AamirAbro,

By default, applications will only attempt to join available experiments any time an activity is resumed, but you can disable this automatic behavior by adding the following tag to the in your AndroidManifest.xml
         
`<meta-data android:name="com.mixpanel.android.MPConfig.AutoShowMixpanelUpdates" android:value="false" />`

If this tag is already set to false: is your app utilizing joinExperimentIfAvailable and OnMixpanelUpdatesReceivedListener to join (or clear) existing experiments?

If it helps, there's a bit more detail here: https://github.com/mixpanel/mixpanel-android/blob/337958cb032ea96a0d29b26c243ff1a3adca6591/src/main/java/com/mixpanel/android/mpmetrics/MixpanelAPI.java#L1139-L1154

**Comment by xX7** [comment]
We are experiencing the same issue like @AamirAbro, @cassiegamm.

Pseudo - Code:
`public class MainActivity{
public static Tweak<Boolean> mABShow = MixpanelAPI.booleanTweak("Test Var 1", true);
@Override
    protected void onCreate(Bundle savedInstanceState) {
          mixpanelAPI = MixpanelAPI.getInstance(this, "XXXX");
     }

}`

Now If you start a Activity, directly from the MainActivity and check the value of mABShow, it will return the default value. You have to "restart" the Activity first in order to get the right value.

**Comment by rosconabn** [comment]
I found a solution to this issue by using the reset before each initialization (set your identity).
 Now the after join experiments is triggered quickly.

**Comment by xX7** [comment]
The Solution from @cassiegamm worked perfectly! Just in case someone reads this and has the same issue!

**Comment by AamirAbro** [comment]
But the experiment is already joined I can see that in the logs but value first time it always gives the default value and the the tweek value is not retianed, as far as I know only andorid SDK has these issues I talked to iOS developer he said they don't​ face these issues. I would suggest to keep this thread open and try to have some good default implementation.

**Comment by rosconabn** [comment]
@AamirAbro  try as I did, I use both android and ios and now all works fine.
 I also had timing issues between screens and this really fix the problem.
 Also for android when you get the value try to broadcast the value.
 but mostly use the flush! I think is the key of your issues.

**Comment by rosconabn** [comment]
@xX7  doesn't mean it works for you it works for everybody. Don't assume anything, find the solution not the party dancing.

**Comment by dinhthaidaica** [comment]
@rosconabn @xX7 could you please provide your sample? I have the same issue with @AamirAbro and still can not fix it

**Comment by Tsepaka** [comment]
I can confirm, that I have the same issue as @AamirAbro. Tweak values are not retained across app launches, and tweak.get() return the default value until activity is re-launched. However, in logs, I can see, that correct value for the experiment is retrieved from server.

**Comment by patedit** [comment]
Starting on version 5.2.0, we now persist tweak across app sessions.
@Tsepaka the logs that you see is what the server sends back, but it does not mean it's automatically applied. You'd need to go into a new activity to apply the tweaks automatically or by calling `mMixpanel.getPeople().joinExperimentsIfAvailable()`.

**Comment by rakeshostwal** [comment]
@patedit , calling a `mMixpanel.getPeople().joinExperimentsIfAvailable()` is still not working. i am using Mixpanel using Segment through MixpanelIntegration.FACTORY.

**Comment by patedit** [comment]
Can you write into support@mixpanel.com? Someone there will be able to help you with the implementation! Thanks!
