### ISSUE TITLE
Add NONE level to custom logger 

### ISSUE THREAD

**Issue by dbarwacz** [mixpanel/mixpanel-android#428]
Hey!
thanks a lot for implementing custom logger, it decreased amount of logs significantly. It would be great if you could add a level that disables every logs - something like `NONE`.  (related to #319)

**Comment by patedit** [comment]
Done https://github.com/mixpanel/mixpanel-android/commit/36da534462ee1907aff311ffd60ed1c008362e72

You can always pass an int above 6 for now 👍
