### ISSUE TITLE
InstanceProcessor is Protected to the package and cannot be copied to any other project

### ISSUE THREAD

**Issue by nalinchhajer1** [mixpanel/mixpanel-android#433]
I have seen use of 
```
 MixpanelAPI.allInstances(new InstanceProcessor() {
                @Override
                public void process(MixpanelAPI api) {
                    api.getPeople().clearPushRegistrationId();
                }
            });
```

but InstanceProcessor is protected and any other project cannot use it.

**Comment by patedit** [comment]
Hi @nalinchhajer1! You are right, not only `InstanceProcessor` is protected but also `allInstances`. That API is only meant to be used internally. Do you need to use it? What's your use case? Thanks!
