### ISSUE TITLE
SurveyActivity java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by amensia** [mixpanel/mixpanel-android#434]
Hi , 

The in-app notification is crashing on android 4.4 and lower
See the Stackstrace,

thanks 

[app_issue_1423_crash_58B6E7D4000300013F853D9EE4768F20_754b11427af04fdb8a31b4466dac6314_0_v1.txt](https://github.com/mixpanel/mixpanel-android/files/811567/app_issue_1423_crash_58B6E7D4000300013F853D9EE4768F20_754b11427af04fdb8a31b4466dac6314_0_v1.txt)

**Comment by patedit** [comment]
Hi @amensia, thank you very much for the crash report. I've fixed this issue and made a new release that is now available (4.9.7). Take care!

**Comment by amensia** [comment]
Awesome, thank you ;)

**Comment by HsuHsiaoHsuan** [comment]
Hi @patedit .Still have some issue in 4.9.7.  In-App Message can't remain on screen, it close itself automatically very soon. But I do not see any error message in Android monitor. :(

**Comment by patedit** [comment]
Hi @HsuHsiaoHauan! Can you open a new issue and describe what happens since your issue is not related to this ticket? Thank you!
