### ISSUE TITLE
In-App Message close itself automatically very soon

### ISSUE THREAD

**Issue by HsuHsiaoHsuan** [mixpanel/mixpanel-android#436]
version 4.9.7. In-App Message can't stay on screen, it close itself automatically very soon. But I do not see any error message in Android monitor. I tested on Samsung S3 (4.3), Samsung Galaxy S7 (7.0), Samsung Note5(6.0.1), HTC 10 (7.0) and LG Nexus 5X(7.1.1). But it's only correct on LG Nexus 5X(7.1.1)

**Comment by patedit** [comment]
Hi @HsuHsiaoHsuan, thanks for writing in! Do you see that behavior with take over in-app notifications (i.e. full screen) or mini in-app notifications (i.e. small toast at the bottom of the screen)? Thanks!

**Comment by HsuHsiaoHsuan** [comment]
It's full screen with default Dark theme, and the primary button is "Close the notification". Many Thanks.

**Comment by patedit** [comment]
I've certainly never seen this behavior. Have you tried debugging it? A good place to start is setting a break point on `onPause()` in `SurveyActivity.java` and see why that method is being called. 
Are you starting a new activity right after showing the in-app?
Are you showing the in-app manually (by calling `showNotificationIfAvailable()`)?

**Comment by HsuHsiaoHsuan** [comment]
I just follow the [official doc](https://mixpanel.com/help/reference/android-inapp-notifications) and let it auto check. I will do some debugging and check if I start a new activity right after showing the in-app. Many Thanks.
