### ISSUE TITLE
Changelog Release v4.9.5 unclear

### ISSUE THREAD

**Issue by awenger** [mixpanel/mixpanel-android#437]
We are planning to update the mixpanel dependency in our app. The changelog regarding v4.9.5 is unclear  about what it does:
> We now can track open push notifications (for API 14 and above). Events that will be automatically sent (like iOS):
> - $app_open will be tracked if the user taps on the push notification. campaign_id and message_id are sent as well as message_type=push.
> - $campaign_received will be tracked if the app receives a push while the app is running in the foreground. Same properties as before are sent.

Will that change trigger events automatically if we display notifications in Android (for example with `NotificationCompat.Builder`)? The ios guy on hand also couldn't help me with regards *(like iOS)*.

**Comment by patedit** [comment]
Hi @awenger! Sorry that the changelog was not clear.
Those two events will only be automatically sent if the push notification is coming from Mixpanel. That means that if you manually create your own notifications with a notification builder those two events won't be sent automatically.

**Comment by awenger** [comment]
Great! thanks for the clarification.

**Comment by patedit** [comment]
I'm closing this issue. Feel free to open if if you have more questions!
