### ISSUE TITLE
Super Properties are lost when app data is cleared

### ISSUE THREAD

**Issue by vibinr** [mixpanel/mixpanel-android#439]
Hi, after reading the source, I realized that `MixpanelAPI#getSuperProperties()` gets them from local Shared Preferences, and not from Mixpanel server. 

This obviously means when the user clears App Data, the super properties are lost. This is as opposed to People Properties, which we can continue to increment (as past value exists), even after when a past user re-installs the app.

Is there any way to get around this?

**Comment by patedit** [comment]
Hi @vibinr ! I can see the value of being able to retrieve super properties for a session even if you clear the app - however, we don't support that. A way to get around this is using people properties, as you pointed out :)
