### ISSUE TITLE
Codeless event tracking : Able to track very few elements

### ISSUE THREAD

**Issue by yashasvigirdhar** [mixpanel/mixpanel-android#442]
Hi,

I am trying to set up codeless event tracking for my app by following the steps listed here and here but facing some issues.

The `Set up tracking` page is showing very few view elements on the screen as trackable elements. There are a lot of other elements on the screens which I want to track but they are not being detected by your software/
 
PFA the images of the screens that I tried it on. As you can see, the first screen shows only one button as trackable element, but there are a lot of other buttons and views. The behaviour is same for the second screen.

Device Information :
Moto G3
Android Version : 6

Mixpanel Api Version : 4.+
Support Library version : 25.1.0
Play Services version : 9.4.0

<img width="360" alt="screen shot 2017-03-30 at 2 53 00 pm" src="https://cloud.githubusercontent.com/assets/2319525/24642552/a9f79f6a-1925-11e7-9493-c17d77842182.png">

<img width="362" alt="screen shot 2017-03-30 at 2 56 19 pm" src="https://cloud.githubusercontent.com/assets/2319525/24642496/44ccbf1c-1925-11e7-841a-38a24c48b524.png">

**Comment by patedit** [comment]
Hi @yashasvigirdhar! We currently don't have support for all the views that Android provides. We are going to expand the set of views that codeless event tracking can handle. Do you mind telling us what are the views that that particular screen is showing? Thanks!
