### ISSUE TITLE
Data not sent to MixPanel in Kiosk environment

### ISSUE THREAD

**Issue by gmale** [mixpanel/mixpanel-android#444]
We are using MixPanel on locked-down Kiosk devices in a retail store with custom Ethernet hardware. After a lot of investigation, we've found this information in the logs:

> 04-07 23:39:06.111	Flushing queue due to scheduled or forced flush (Thread 224)
04-07 23:39:06.113	ConnectivityManager says we are not online
04-07 23:39:06.114	Not flushing data to Mixpanel because the device is not connected to the internet. (Thread 224)

After inspecting the SDK source code, these checks happen in `HttpService` but there is a tiny bug that doesn't account for when `NetworkInfo` can be null. According to the documentation for [ConnectivityManager#getActiveNetworkInfo](https://developer.android.com/reference/android/net/ConnectivityManager.html#getActiveNetworkInfo()):

>This may return null when there is no default network.

Accordingly, [we're submitting the following patch, which corrected the in-store problem for us](https://github.com/mixpanel/mixpanel-android/pull/445). After weeks of investigating every networking layer and IT restriction known to man, it turned out this one line of code was the culprit. Now, MixPanel works in the store–albeit with a patched SDK.

**Comment by patedit** [comment]
Thanks again @gmale  👍
