### ISSUE TITLE
cannot gradle sync because of no resource found in mixpanel-android:5.0.2

### ISSUE THREAD

**Issue by salismt** [mixpanel/mixpanel-android#454]
Error:(78, 28) No resource found that matches the given name (at 'theme' with value '@style/com_mixpanel_android_SurveyActivityTheme').
what am I missing?

**Comment by patedit** [comment]
Hi @salismt ! We changed the name of the activity that handles in-app notifications and also the name of the theme. Open your AndroidManifest.xml file and look for `com_mixpanel_android_SurveyActivityTheme` and change it to `com_mixpanel_android_TakeoverInAppActivityTheme`. Also, make sure that you no longer have `com.mixpanel.android.surveys.SurveyActivity` but `com.mixpanel.android.takeoverinapp.TakeoverInAppActivity` instead.
