### ISSUE TITLE
Updating to 5.+ crashes Main Activity file

### ISSUE THREAD

**Issue by itaispector** [mixpanel/mixpanel-android#461]
Hey Guys,

I've recently updated Mixpanel lib to 5.+, and it seems to crash my app on startup. What I get is this:

> java.lang.RuntimeException: Unable to start activity ComponentInfo{com....MainActivity}: android.view.InflateException: Binary XML file line #23: Error inflating class fragment

When I put it back to 4.+, My App runs.

Please note: I saw your release notes for 5.0.2, and you noted to change the Survey Activity to TakeOver Activity in the Manifest file. I did so, but that still didn't help.

Looking forward to see if you guys know anything about it.

Thanks,
Itai

**Comment by patedit** [comment]
Hi @itaispector! I'd start by looking at the XML file that is being inflated in your `MainActivity` class. Are you using any fragments from Mixpanel?

**Comment by itaispector** [comment]
Hi @patedit, Thanks for replying.
I'm not using any fragments from Mixpanel.

**Comment by patedit** [comment]
Seems that in your XML you are using a fragment that can't be inflated. I'd look into your fragment code. If you don't mind sharing you could send your code to support@mixpanel.com and I can personally take a look.

**Comment by itaispector** [comment]
@patedit I sent an email to support@mixpanel.com, Please refer to it.

Thanks
