### ISSUE TITLE
MixpanelActivityLifecycleCallbacks leaks activities

### ISSUE THREAD

**Issue by mindhacker42** [mixpanel/mixpanel-android#463]
Library version: 5.1.0

LeakCanary trace:
```
In xxxxxxx.simpledemo:1.0:1.
* it.reveel.simpledemo.MainActivity has leaked:
* GC ROOT static it.reveel.sdk.internal.analytics.Analytics.mixpanelApi
* references com.mixpanel.android.mpmetrics.MixpanelAPI.mMixpanelActivityLifecycleCallbacks
* references com.mixpanel.android.mpmetrics.MixpanelActivityLifecycleCallbacks.check
* references com.mixpanel.android.mpmetrics.MixpanelActivityLifecycleCallbacks$1.val$activity (anonymous implementation of java.lang.Runnable)
* leaks xxxxxxx.simpledemo.MainActivity instance

* Retaining: 148 KB.
* Reference Key: 63546fe7-d0af-4992-a355-ca5a90e2ee4c
* Device: LGE google Nexus 5 hammerhead
* Android Version: 6.0.1 API: 23 LeakCanary: 1.5 00f37f5
* Durations: watch=5064ms, gc=130ms, heap dump=4808ms, analysis=236627ms

```

I looked at the code and I saw that you register for activity lifecycle callbacks to measure session duration and other stuff. You can disable other stuff but you can't disable measuring session duration.
Problem occurs when you capture activity object in Runnable and you retain that in variable and since MixpanelActivityLifecycleCallbacks lives forever in MixpanelAPI singleton that Runnable never gets GCed.
1. It might help to unregister for lifecycle events in onResume or somewhere since you don't need to listen for that in background. 
2. Otherwise maybe putting "check" variable to null when removing callbacks from handler will also help.

**Comment by mindhacker42** [comment]
After investigating further I saw that library version 5.0.2 does not leak and that the culprit is in the line 81 of MixpanelActivityLifecycleCallbacks. 
Because you use activity passed in onActivityPaused method to get application context you capture activity instance in Runnable named check. 

You could get minimumSessionDuration and sessionTimeoutDuration variables in MixpanelActivityLifecycleCallbacks constructor or at least use context from an instance variable or MixpanelAPI instance.

**Comment by mwolfe38** [comment]
I'm seeing this as well.  It's causing some major memory leaks in my app. Any progress on a fix?

**Comment by JasonSznol** [comment]
+1 on this leak.

**Comment by patedit** [comment]
Thanks a lot for reporting this @mindhacker42 and thanks @mwolfe38 @JasonSznol for confirming the issue!
I've fixed the issue (https://github.com/mixpanel/mixpanel-android/commit/3662663f67142b7d17f5a378cfc13680d2628664) and released version 5.1.2 just now 👍

**Comment by JasonSznol** [comment]
Have you published the updated version to a maven repository? Gradle is saying it can't be found and I did not see it in bintray last night.

**Comment by patedit** [comment]
@JasonSznol Can you try now? Thanks!

**Comment by JasonSznol** [comment]
Can confirm it is working, thanks!

**Comment by patedit** [comment]
Amazing. Thanks for your help @JasonSznol !

**Comment by fleficher** [comment]
Hi @patedit i'm having the same issue using the 5.2.1 version :

`*  xxxxxxx.MyActivity has leaked:
* GC ROOT static A4S.b
* references xxxxxxx.MyApplication.mMixpanelActivityLifecycleCallbacks
* references ArrayList.elementData
* references array Object[].[14]
* references MixpanelActivityLifecycleCallbacks.check
* references MixpanelActivityLifecycleCallbacks$1.val$activity (anonymous implementation of java.lang.Runnable)
* leaks xxxxxxx.MyActivity instance
`

**Comment by fleficher** [comment]
Oups, sorry @patedit, we had a class named 'MixpanelActivityLifecycleCallbacks' in our code too which is extremly closed to yours. So it was a problem on my side :)

Wrong alert
