### ISSUE TITLE
AB Testing Experiments

### ISSUE THREAD

**Issue by mobee-bill** [mixpanel/mixpanel-android#468]
Hello,

I am trying out the AB testing experiments but I am having trouble selecting views which are underneath other views which are not always visible to the user.  For example, I have a full screen loading view that covers everything which gets it's visibility set to GONE when the loading is done. However I am still unable to focus on any of the content which is visible in my layout.  I have other views as well which expand and collapse content on top of other views but even when collapsed I cannot select the content which is then visible.  Is there any way in which I can traverse my layout hierarchy on a connected device when using AB test experiments?

Thanks!

**Comment by patedit** [comment]
Hi @mobee-bill ! If a view is set to GONE you should still be able to select views underneath it. If the view is set to INVISIBLE then you probably want to play with `com.mixpanel.android.MPConfig.IgnoreInvisibleViewsVisualEditor` meta-tag.

For the spinner example, what are the views that are underneath it? (i.e. recycleview, textviews,...)

> Is there any way in which I can traverse my layout hierarchy on a connected device when using AB test experiments?
I'm not sure if I understand your question. You can open the visual editor on mixpanel.com with any device (connected or not) as long as you connect to the visual editor. If you are using an emulator the connection happens automatically; if you are using a device you need to trigger the connection (pointing the screen of your phone at the ground and then at the sky!).

**Comment by mobee-bill** [comment]
Hi @patedit! Thanks for your reply. I have attached some images to illustrate the issue I am seeing. I am connecting using a Samsung Galaxy S6.

Editable frames showing:
<img width="360" alt="screen shot 2017-06-20 at 10 24 38 am" src="https://user-images.githubusercontent.com/13965507/27338692-e3dc72ea-55a3-11e7-8e51-a2f9f886a42d.png">

Expanded overlaying view: (Consists of a listview and a framelayout that dims background content)
<img width="363" alt="screen shot 2017-06-20 at 10 25 20 am" src="https://user-images.githubusercontent.com/13965507/27338762-1261f4be-55a4-11e7-81a8-7b56bcd34ca4.png">

Below you can see I am only able to select 2 frames (the listview and framelayout), even though the bottom FrameLayout is set to a visibility of GONE when collapsed and the listview that has been collapsed still appears to have the same frame size. I am unable to select any of the frames below these 2, even though they are recognized in my first screenshot.

Selectable areas:
<img width="369" alt="screen shot 2017-06-20 at 10 31 38 am" src="https://user-images.githubusercontent.com/13965507/27338879-4bc3b846-55a4-11e7-9ba0-593e5f941984.png">

<img width="364" alt="screen shot 2017-06-20 at 10 31 50 am" src="https://user-images.githubusercontent.com/13965507/27338909-5f4c300a-55a4-11e7-9f0b-3b409e0be759.png">

I hope this is clear!  Thanks again for your help.

On a side note, is it possible to connect an Android and iPhone simultaneously on different machines?  It appears that the connection fails when attempting to do so.

**Comment by patedit** [comment]
For the first screenshot: If we show that those are the editable frames, can you click on one in particular and edit it (before expanding/collapsing the dropdown menu)?
For the second screenshot: Instead of selecting a view, if you show the editable content like on the first screenshot, do you see gray frames around the labels?
Third screenshot: It seems that you are selecting parent views but you should be able to select a particular child view. For example, I can see on the first screenshot that "Mobee HQ Testing" is editable so I would expect that if you click right on that label you can select that child view. If you click outside and on the parent view you will select the entire FrameLayout.

Is your app on the store so I can play with it? If not, would you mind sending an apk to support@mixpanel.com as well as the project ID you are using?

Thanks!

**Comment by Artyomcool** [comment]
Hey! We have the same issue.
Looks like our problem lies [here](https://github.com/mixpanel/mixpanel-android/blob/master/src/main/java/com/mixpanel/android/viewcrawler/ViewSnapshot.java#L132
).
`snapshotView` is traversing even views with the GONE visibility. Even if `IgnoreInvisibleViewsVisualEditor` flag is true. Would it better to ignore views with the GONE visibility? I could prepare PR.

**Comment by xylik** [comment]
We are having the same issue, when i toggle on all editable frames I see my whole screen segmented by sub views correctly but when i try to select for example item in RecyclerView which is child of FrameLayout i can only select it's parent although recycler view items are shown when editable frames switch is on!

**Comment by genxstylez** [comment]
Hi, I am experiencing the same issue, any updates here? @Artyomcool @patedit

**Comment by kceb** [comment]
Experiencing this as well..
