### ISSUE TITLE
Without Google play services

### ISSUE THREAD

**Issue by skuppa** [mixpanel/mixpanel-android#471]
We have custom built AOSP without google play services, can we use the mixpanel library without the google play services?  Is it recommended to use the `mixpanel-java` library instead of `mixpanel-android`.

Thanks,
-Kuppa

**Comment by patedit** [comment]
You can perfectly use `mixpanel-android` library without google play services. We use google play services to send push notifications so you customers won't be able to receive push notifications through our library but you can use any other features :)
