### ISSUE TITLE
OnMixpanelTweaksUpdatedListener not reflecting current value of A/B test Tweak

### ISSUE THREAD

**Issue by xylik** [mixpanel/mixpanel-android#472]
Hi, am currently running A/B test with one Tweak being set to 2 different values in variant A and B.

The issue am experiencing is that callback OnMixpanelTweaksUpdatedListener is being triggered right after i switch from variant A to variant B(from A/B visual designer on connected device with app build in debug mode) but when i try to fetch value of Tweak inside of listener i get old value set for variant A. Than, if i trigger OnResume on some screen after listener has finished and try to fetch Tweak value I get correct value(value for variant B), but isn't the purpose of TweakListener to allow Tweak updates to be intercepted?

Issue manifested on:
Google Nexus 5
Marshmallow 6.0.1
SDK version: 5.1.4

**Comment by patedit** [comment]
@xylik https://github.com/mixpanel/mixpanel-android/pull/492 will address your issue. I'll make a release tomorrow 👍

**Comment by David-Eliyahu** [comment]
hello @patedit 
currently i'm using v5.3.0 and this issue is still reproduce.. can you please help me with that one 
My scenario is exactly the same as described here. should i open a new issue ? 
thanks.
