### ISSUE TITLE
Icons are never loaded in mipmap folder

### ISSUE THREAD

**Issue by lazybee27102** [mixpanel/mixpanel-android#473]
I use `ic_launcher` for notification icon which was stored in `mipmap` folder. But it never loaded in the status bar. When I try to read your codes, then I see you never load it from mipmap folder.

This is the code of loading `drawable` resource 
```
public static class Drawables extends ResourceReader {
        protected Drawables(String resourcePackageName, Context context) {
            super(context);
            mResourcePackageName = resourcePackageName;
            initialize();
        }

        @Override
        protected Class<?> getSystemClass() {
            return android.R.drawable.class;
        }

        @Override
        protected String getLocalClassName(Context context) {
            return mResourcePackageName + ".R$drawable";
        }

        private final String mResourcePackageName;
    }
```

How about creating new class `Mipmaps` for `.R$mipmap` when resource in drawable isn't available? 

PS: I think this use-case is common, people want to see their `ic_launcher` as the notification icon. The same as `smallIcon` and `whiteIcon`.

Please take a look and give me your response. Thanks

**Comment by patedit** [comment]
Hi @lazybee27102 ! Thanks for the time you spent researching this issue. It totally makes sense and I love your idea. Thanks for sharing! Would it be possible for you to create a PR for this feature? Otherwise, I can take care of it in the coming weeks.

**Comment by lazybee27102** [comment]
Hi @patedit, I just create a pull request. It would be nice if you could take a look. 
Thank you

**Comment by patedit** [comment]
Thanks @lazybee27102 - will close this ticket on favor of the pr
