### ISSUE TITLE
My app service is running in background but I do not want mixpanel to present like the user is active in the app

### ISSUE THREAD

**Issue by miroslavign** [mixpanel/mixpanel-android#475]
It is braking some of our funnels, like, 
we see last real in-application activity was some hours ago, but, 
at the same time we see mixpanel presenting activity some minutes
ago (in this case 28 minutes).
Is there a way to temporary disable mixpanel on-demand.

We have a background service which detects app is in fore or background, 
so we could use this to manually force mixpanel to be silent.

![for_mixpanel_support](https://user-images.githubusercontent.com/1773454/28664398-aa01c66c-72c0-11e7-9eaf-d63a0152553e.jpg)

**Comment by patedit** [comment]
Hi @miroslavign - are you updating any mixpanel people properties or super properties from your background service?

**Comment by miroslavign** [comment]
No, but on each application going to background I am calling
mixpanel.flush();
(in the latest build, going through github issues for mixpanel I found
I should disable flush, so I did disable it)

We have a situation like for hours a user would not use the app, but we
see that mixpanel is active. So, not even this to-background event will fire.
Is there a way for us to check mixpanel web console what is causing it ?

**Comment by miroslavign** [comment]
Any update about this? 
Our retention numbers get all broken.

**Comment by patedit** [comment]
Hi @miroslavign ! The `last seen` property is updated when you perform an update for that user (i.e you identify the user, update a people property, send an event, etc..). So even if your app is running 24/7, the value won't be updated if you don't make any updates for that user.
Even if you call `mixpanel.flush()`, if there are no updates in the queue, nothing will happen (we don't even make the http request); so `last seen` won't be updated either in that scenario.

You said that "Not even this to-background event will fire". Do you have a background event in your app? I can't find it in your project.

I can think about two possible things that could be happening in your case:

- Your background service is updating something on your mixpanel instance. Could you double check?
- You are identifying the same user on different platforms: web, ios, etc... And indeed they are still using your product from a different platform.

If you want to make sure you are not sending any mixpanel updates when the app goes into the background, you could use our `OfflineMode` feature in the SDK. See this: https://github.com/mixpanel/mixpanel-android/blob/v5.1.4/src/main/java/com/mixpanel/android/mpmetrics/MPConfig.java#L150-L173 

Let me know how it goes!

**Comment by miroslavign** [comment]
@patedit could you please reopen this one, we are still having issues that cause the retention numbers to be wrong ?
I put a thumbsUp for detailed info what to try more, where to search.

Now, this is getting heavy for us, meaning, we are dependant on these retention numbers, how could we get to the bottom of it? Is there a way we could point you to a specific user (there are many if not all of them) and if you could check what is making they appear as "online" <- whatever this means ?

First of all, that number with the stopwatch next to the name, what does it mean? Related to what event is that time ? 
Should we schedule on some other support channel with you guys ?

![mixpanel_support](https://user-images.githubusercontent.com/1773454/29451653-bc160968-8403-11e7-9d14-6770105ff823.png)

**Comment by miroslavign** [comment]
This is the object we are sending on some web socket events, but only when the socket is open, 
and we keep it closed, But anyway, could we somehow check if really the culprit is updating people
objects, which event, what data is causing this.

```
        JSONObject forMixPanel;
        String isPayingString = "false";
        if (Heymarket.instance.getUserStatusPaying()) {
            isPayingString = "true";
        }
        forJson.put("paying", isPayingString);
        forMixPanel = new JSONObject(forJson);
        Logger.json(forMixPanel.toString());
        mixpanel.registerSuperProperties(forMixPanel);
        mixpanel.getPeople().set("paying", Heymarket.instance.getUserStatusPaying());
```

**Comment by patedit** [comment]
Hi @miroslavign - Notice this is not an issue with the SDK but an implementation problem (hence I closed the issue). I'm happy to help you figuring out what is going on.

Regarding your question: Yes, the number next to the stopwatch is `last seen` which is the last time a people update was performed.

If you have web sockets running while the app is in the background and you are making people updates then you'll be updating `last seen`. We can't sadly access people update calls.

I'd try to set breakpoints in any people update and see when they are hit when the app is running in the background. For example: what would happen if you turn airplane mode on and then turn it off again? Will the socket connection be re-established and trigger that block of code you just pasted?

**Comment by miroslavign** [comment]
Ok, will do more of that tracing.
Tnx

**Comment by patedit** [comment]
Hi @miroslavign - just pinging you again to make sure everything is good on your end. Could you find out what was the root cause?

**Comment by shiv71** [comment]
I am having the same issue in my android sdk
