### ISSUE TITLE
Tweaks from the second experiment are never applied

### ISSUE THREAD

**Issue by k-tigre** [mixpanel/mixpanel-android#478]
I have two experiments for different screens. 
Experiment A with should apply only "Tweak 1" (50% for value "0", 50% for value "1")
Experiment B with should apply only "Tweak 2" (50% for value "false", 50% for value "true")
Both experiments turn on to all users.
When I config experiment, I change only one tweak.

Logs from MixpanelAPI.DChecker:
``{"notifications": [],    "variants": [
        {
            "tweaks": [
                {
                    "name": "Tweak 1",
                    "encoding": "l",
                    "maximum": null,
                    "value": 1,
                    "minimum": null,
                    "type": "number"
                },
                {
                    "minimum": null,
                    "type": "boolean",
                    "name": "Tweak 2",
                    "value": false,
                    "maximum": null
                }
            ],
            "actions": [],
            "id": 87384,
            "experiment_id": 42316
        },
        {
            "tweaks": [
                {
                    "minimum": null,
                    "type": "boolean",
                    "name": "Tweak 2",
                    "value": true,
                    "maximum": null
                },
                {
                    "name": "Tweak 1",
                    "encoding": "l",
                    "maximum": null,
                    "value": 0,
                    "minimum": null,
                    "type": "number"
                }
            ],
            "actions": [],
            "id": 88292,
            "experiment_id": 42728
        }
    ],
    "automatic_events": false
}``

In code I always see:
`Tweak 1 = 0
 Tweak 2 = true`
But I expected: 
`Tweak 1 = 1
 Tweak 2 = true`

So, each experiments applied all available tweaks.

SDK version 5.1.4

**Comment by wgins** [comment]
@k-tigre Based on the response you passed along it looks like both experiments, 87384 and 88292 include **both** tweaks (Tweak 1 and Tweak 2). When a device connects to the A/B test designer all tweaks in the app are included in the experiment you build. If you'd like to apply multiple A/B tests without "overlapping" tweak values you'll need to ensure that when you connect your device to the A/B test designer that only the tweaks relevant to that experiment are included in the app. 

The steps you'd take would look like:

1. Include tweak for "Experiment A" in the app
2. Connect to A/B test designer, build and save experiment
3. Disconnect from designer, remove tweak for "Experiment A" from app
4. Include tweak for "Experiment B" in app
5. Repeat step (2)
6. Disconnect from designer and deploy app to app store with tweaks for both "Experiment A" and "Experiment B" included. 

Full disclosure, this is a workaround. Generally speaking, we advise against deploying multiple A/B tests at the same time as doing so may conflate experiment results.
