### ISSUE TITLE
Push Notifications from Mixpanel plugin

### ISSUE THREAD

**Issue by Allan-Nava** [mixpanel/mixpanel-android#480]
Hi,

is possible sending Android push notifications from Mixpanel?

Best regards

**Comment by cassiegamm** [comment]
Hi @Allan-Nava,

It is possible to send Android push notifications from Mixpanel. We have some public documentation explaining how to set things up available [here](https://mixpanel.com/help/reference/android-push-notifications). Hopefully, this meets your needs!
