### ISSUE TITLE
Can't send any event to mixpanel from device

### ISSUE THREAD

**Issue by malashkevich** [mixpanel/mixpanel-android#482]
Hello.
Thanks for such great service and library!
I'm stuck with such unexpected result:
Im trying to send simple event. I was able to do this using emulator, however when I deploy it to device - it not works. 
There is internet connection on device.
I do have following permissions:

```
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
    <uses-permission android:name="android.permission.GET_ACCOUNTS" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
```

I also enabled logging and got this:
```
/MixpanelAPI.Message: Attempting request to https://api.mixpanel.com/track?ip=1
/MixpanelAPI.Messages: Cannot post message to https://api.mixpanel.com/track?ip=1. (Thread 2430)
                       java.net.ConnectException: Connection refused
at java.net.PlainSocketImpl.socketConnect(Native Method)
...
```

Does anyone know how to fix this?
Thanks in advance.

**Comment by patedit** [comment]
Hi @malashkevich - this is very strange and the only thing I can think of is that you have some sort of firewall blocking the connection. Have you tried with a different device?

**Comment by malashkevich** [comment]
Oh, sorry guys.
This should be closed. Yes, that was my device.
