### ISSUE TITLE
MixpanelAPI.EProtocol Warning

### ISSUE THREAD

**Issue by itaispector** [mixpanel/mixpanel-android#486]
Hi Folks!

lib version: 5.1.4
compileSdkVersion: 26
buildToolsVersion: 26.0.1
targetSdkVersion 21

I'm getting this warning in logcat:

```
W/MixpanelAPI.EProtocol: Path element contains an id name not known to the system. 
No views will be matched. 
Make sure that you're not stripping your packages R class out with proguard. 
id name was "subProduct"
```

Could help me understand what's the source of this issue?

Thanks.

**Comment by patedit** [comment]
@itaispector it seems that you have applied a UI change to a view with id `subProduct` (i.e. `android:id="@+id/subProduct` but that id no longer exists. Maybe you have changed the name of the id in a different version of your app or you are stripping your R.class with proguard?

**Comment by itaispector** [comment]
@patedit Thanks for replying!

I don't recall that I'm stripping my R.class with proguard.. but I will surely check in those directions you've mentioned.

Best regards

**Comment by patedit** [comment]
Let me know if you need any more help!

**Comment by scott-marinoff** [comment]
For future reference, I have also seen this issue when a mobile event has been created with Autotrack but the element the event was attached to is no longer present in the app.

**Comment by itaispector** [comment]
> For future reference, I have also seen this issue when a mobile event has been created with Autotrack but the element the event was attached to is no longer present in the app.

This seems to be the issue!
