### ISSUE TITLE
HandlerThread use wrong thread priority

### ISSUE THREAD

**Issue by ryanzor** [mixpanel/mixpanel-android#487]
Reading the code it looks like the HandlerThreads use Thread.MIN_PRIORITY (IE priority 1) for the priority.

HandlerThread itself uses 

> Process.setThreadPriority(mPriority);

So I believe the correct priority to pass would be Process.THREAD_PRIORITY_LOWEST (19) or maybe something higher, but overall I think Thread.MIN_PRIORITY is a deceptive value to pass in creating the HandlerThread

I could be missing something here, but reading the code that stood out as strange to me.

**Comment by patedit** [comment]
@ryanzor thanks a lot for pointing it out. You are absolutely correct and we should be using `android.os.Process` instead of `java.lang.Thread`. I've created a PR that will be merged soon. Thanks!
