### ISSUE TITLE
Android Oreo support

### ISSUE THREAD

**Issue by fred8** [mixpanel/mixpanel-android#491]
We're on our way to target Android Oreo.
The current code doesn't seems to be compatible (notification channels, gcm changes...etc...)

Do you have any plans to support it? and when?

Thank you!

**Comment by patedit** [comment]
Hi @fred8! Thanks for writing in. I am going to make a new release this week and Android O support will be included. This is the PR to track progress: https://github.com/mixpanel/mixpanel-android/pull/495
Feel free to write any comments!

Thanks!
