### ISSUE TITLE
NPE MixpanelActivityLifecycleCallbacks

### ISSUE THREAD

**Issue by salah-ghanim** [mixpanel/mixpanel-android#493]
Mixpanel is crashing our app during debugging, not sure if its reproducible on production.
but peeking into 
https://github.com/mixpanel/mixpanel-android/blob/9457f8c44930b58eb6adf1fb409a6d22bbca7dd9/src/main/java/com/mixpanel/android/mpmetrics/MixpanelActivityLifecycleCallbacks.java

it does not check for null in intent's extra.

`com.mixpanel.android.mpmetrics.MixpanelActivityLifecycleCallbacks.onActivityStarted (MixpanelActivityLifecycleCallbacks.java:37) android.app.Application.dispatchActivityStarted (Application.java:231) android.app.Activity.onStart (Activity.java:1270) android.support.v4.app.FragmentActivity.onStart (FragmentActivity.java:544) android.support.v7.app.AppCompatActivity.onStart (AppCompatActivity.java:177) android.app.Instrumentation.callActivityOnStart (Instrumentation.java:1256) android.app.Activity.performStart (Activity.java:6959) android.app.Activity.performRestart (Activity.java:7075) android.app.Activity.performResume (Activity.java:7080) android.app.ActivityThread.performResumeActivity (ActivityThread.java:3768) android.app.ActivityThread.handleResumeActivity (ActivityThread.java:3832) android.app.ActivityThread$H.handleMessage (ActivityThread.java:1681) android.os.Handler.dispatchMessage (Handler.java:102) android.os.Looper.loop (Looper.java:154) android.app.ActivityThread.main (ActivityThread.java:6682) java.lang.reflect.Method.invoke (Method.java) com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1520) com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1410)`

what's the status here and what's the way to go about it.

**Comment by patedit** [comment]
What is the SDK version you are using?

**Comment by salah-ghanim** [comment]
5.1.4

**Comment by patedit** [comment]
This issue has been fixed on master - I'll push an update later this week!
