### ISSUE TITLE
Usage of implicit broadcast receivers in Android Oreo

### ISSUE THREAD

**Issue by maszin** [mixpanel/mixpanel-android#496]
According to Android documentation usage of Manifest's implicit broadcast receivers is deprecated in Android Oreo https://developer.android.com/about/versions/oreo/android-8.0-migration.html#rbr 

Do you have plan to reimplement/update documentation of https://mixpanel.com/help/reference/android#referrer_tracking and https://mixpanel.com/help/reference/android-push-notifications ?

**Comment by patedit** [comment]
Hi @maszin - Thanks for writing in! Notice that both receivers handle _implicit_ broadcast messages. Push notifications intents are only sent to the receiver app and `com.android.vending.INSTALL_REFERRER` is only sent to the app (on the contrary, `ACTION_PACKAGE_ADDED` is an _explicit_ broadcast message).
