### ISSUE TITLE
trackEvent does not handle null values in JSONObject

### ISSUE THREAD

**Issue by markcerqueira** [mixpanel/mixpanel-android#505]
If I call `trackEvent` in `MixPanelAPI` with a JSONObject containing a null value the method throws an exception. This is caught internally but the result is that the event is not logged to MixPanel. 

Line in question is [here][1]. `properties.get(key)` will throw a `JSONException` if the value is null. The caller to this method could validate input but it seems preferable to handle the nulls and track the event instead of swallowing the exception and not logging the event.

````
E/MixpanelAPI: Exception tracking event test-event
  org.json.JSONException: No value for key_with_null_value
  at org.json.JSONObject.get(JSONObject.java:354)
````

Oddly enough, I can only make it throw an exception on devices running Android 4.3 (I used a HTC One). Anything higher than that works, which is perplexing but maybe something changed in implementations somewhere along the way.

Thank you!

[1]: https://github.com/mixpanel/mixpanel-android/blob/master/src/main/java/com/mixpanel/android/mpmetrics/MixpanelAPI.java#L2076

**Comment by yinfeiru** [comment]
@markcerqueira Hey, sorry for the delay!!

If I understand it correctly, what you want is to skip the properties with `null`s in our library instead of filtering them out in the caller? That makes a lot of sense. I'll get it done when I get a chance!

**Comment by markcerqueira** [comment]
@yinfeiru Yep! The current behavior throws an Exception and the entire event is not logged. Unsure if the best behavior is to skip the property altogether or place in a blank String. I'll defer to you all on that call.

Thanks and cheers! 😄

**Comment by yinfeiru** [comment]
@markcerqueira To me, I feel like skipping the property is the way to go because on Mixpanel you can easily filter out `null` properties with `is not set` filter. But I'll discuss with other folks.

Cheers!

**Comment by yinfeiru** [comment]
@markcerqueira Hey, sorry for the late. The fix will be available in the next release. PR is [here](https://github.com/mixpanel/mixpanel-android/pull/522).

**Comment by markcerqueira** [comment]
@yinfeiru Awesome! Thank you!

**Comment by patedit** [comment]
This has been fixed in the latest release 👍
