### ISSUE TITLE
View Crawler crashes

### ISSUE THREAD

**Issue by gauravarora90** [mixpanel/mixpanel-android#507]
I am getting many crashes on Android version 4.1.2 (80%) and 4.1.1 (20%). I am using the following version of mixpanel library.  **com.mixpanel.android:mixpanel-android:5.+**

Here is the logcat for the crash:

[Fatal Exception: java.lang.NullPointerException
       at android.util.Pair.hashCode(Pair.java:62)
       at java.util.HashMap.put(HashMap.java:390)
       at java.util.HashSet.add(HashSet.java:95)
       at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.loadEventBindings(ViewCrawler.java:443)
       at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.loadKnownChanges(ViewCrawler.java:382)
       at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.handleMessage(ViewCrawler.java:321)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.os.HandlerThread.run(HandlerThread.java:60)](url)

Please help me with the solution ASAP.

**Comment by patedit** [comment]
Hey @gauravarora90 ! Thanks for writing in! This is a very interesting crash that will be fixed in the next release (#508).

On Jelly Bean and below, the `hashCode` method for the `com.android.util.Pair.java` class assumed the first element of the duple is never null (see here: http://androidxref.com/4.1.2/xref/frameworks/base/core/java/android/util/Pair.java#62). It was later modified in following releases and that's why it only crashes on 4.1.X.

Thanks!

**Comment by sneerin** [comment]
It's almost December and no fixes yet, we are paying customer, but this shit will make us leave your product. really.That's something not acceptable.

**Comment by patedit** [comment]
hey @sneerin! A fix was implemented last October and it's currently on master. There has not been any release since then but you can point your gradle file to master 👍

**Comment by beast-shubham** [comment]
I don't understand, @patedit how does our pointing to Master solve the issue. I request you to please make a stable (tested) release with this fix (or a Hotfix), coz our app has quite a lot users on these Android versions.

**Comment by patedit** [comment]
@beast-shubham master contained the fix and is safe to point to that branch since it's stable. You can point an SDK to his github repo using gradle. Anyway, latest release 5.2.2 contains that fix :)

**Comment by beast-shubham** [comment]
@patedit thanks for the quick reply. I appreciate it. :)

I have always been using 5.+ version in my gradle, so I assumed I was always on the latest version. Do u think changing it to 5.2.2 would fix this.?

**Comment by patedit** [comment]
You can safely leave 5.+ and next time gradle syncs it will fetch the latest version 👍
