### ISSUE TITLE
MixpanelApi.Database SqliteDatabaseException

### ISSUE THREAD

**Issue by nigelbro** [mixpanel/mixpanel-android#510]
Running a large test suite of integration tests (85) mixpanel throughs a unable to open database file: Select (*) from people.

This makes it impossible to use mixpanel and run my integration tests in a CI environment.

**Comment by patedit** [comment]
Are you running your own tests or our sdk test suite? (https://github.com/mixpanel/mixpanel-android/tree/master/src/androidTest/java/com/mixpanel/android)

**Comment by nigelbro** [comment]
Hello. I am running my own integration tests. I have 85 of them on number 55 everytime I get a crash from mixpanel. Now  my application has mixpanel track events all through so repeated integration tests will all hit these track events. But it seems that for every integration test in year down their is No way to release the mixpanel instance and stop or querying etc so each integration test mixpanel has the DB open. I also search through and it doesn't seem to be any seperation between being in debug for testing to avoid this issue with integration tests all running on their own testing threads

**Comment by nigelbro** [comment]
*In tear down there is
