### ISSUE TITLE
Name al the specific gplay services used 

### ISSUE THREAD

**Issue by caipivara** [mixpanel/mixpanel-android#513]
In docs you say that the user needs to add this to the gradle file

```
compile "com.google.android.gms:play-services:7.5.0+"
```

But it will add **all** google play services things to the apk.

Take a look to https://developers.google.com/android/guides/setup, they show which dependencies are inside of it so you can pick **just** the needed ones.

**Comment by patedit** [comment]
Thanks for reporting this @caipivara ! It was an oversight from our side. I've updated our `README` file and will soon update our official doc. Take care!
