### ISSUE TITLE
Mixpanel SDK imports android.support.v4.util.LruCache

### ISSUE THREAD

**Issue by Krillsson** [mixpanel/mixpanel-android#517]
Hi, I bumped our Mixpanel dependency to the latest version and you now seem to depend on a single class from the android.support.v4 package. We really don't want to add this dependency to our project.

com.mixpanel.android.util.ImageStore imports android.support.v4.util.LruCache.

Proposed solutions:
- Copy and paste the LruCache class to com.mixpanel.android.util (not sure if the license permits this).
- Bump your min SDK to 12 where this class became available in android.util.LruCache (probably not an option).
- Find another implementation of this data structure that suits your needs.

**Comment by alixwar** [comment]
This is still an issue in version 5.4.5

**Comment by patedit** [comment]
Hi @alixwar and @Krillsson ! We just bumped up the min SDK to 14 so I went ahead and made this change. Will be available on the next release :)

Thank you!

**Comment by alixwar** [comment]
@patedit So... 5.6.0?

**Comment by patedit** [comment]
Release 5.5.1 contains this fix :) Closing this ticket now. Thanks guys!
