### ISSUE TITLE
The RegistrationID is null and I can not deliver push notifications

### ISSUE THREAD

**Issue by takuyama29** [mixpanel/mixpanel-android#518]
I implemented it based on [reference](https://mixpanel.com/help/reference/android-push-notifications) in order to distribute push notification using Mixpanel.

I confirmed the RegistrationID as below and the result is null.

```
override fun onStart() {
    super.onStart()
    val mixpanel = MixpanelAPI.getInstance(this, "mixpanel_token")
    mixpanel.people.identify(user.username)
    mixpanel.people.initPushHandling("@integer/google_sender_id")
    Log.d("mixpanel", "RegistrationID is ${mixpanel.people.pushRegistrationId}") // RegistrationID is null
}
```

We also entered the necessary permissions and package name of the application as per [tihs comment](https://github.com/mixpanel/mixpanel-android/issues/446#issuecomment-340059902).

I want you to tell me where I am wrong.

Thank you

**Comment by takuyama29** [comment]
It seems that this method's `ret` is assigned null.
Under what conditions does this make null go into it?
```
public synchronized String getPushId() {
        String ret = null;
        try {
            final SharedPreferences prefs = mLoadStoredPreferences.get();
            ret = prefs.getString("push_id", null);
        } catch (final ExecutionException e) {
            MPLog.e(LOGTAG, "Can't write push id to shared preferences", e.getCause());
        } catch (final InterruptedException e) {
            MPLog.e(LOGTAG, "Can't write push id to shared preferences", e);
        }
        return ret;
    }
```

**Comment by patedit** [comment]
Hi @takuyama29 ! The first time you call that method it's most likely that will return `null` since the push id is set asynchronously. When you call `initPushHandling` for the first time, we will fetch the ID from Google Cloud Messaging and store it in shared preferences. We handle the registration intent here https://github.com/mixpanel/mixpanel-android/blob/master/src/main/java/com/mixpanel/android/mpmetrics/GCMReceiver.java#L270

If it always returns null it means there's something wrong elsewhere. I can help you debug your issue! After initializing mixpanel, call `MPLog.setLevel(MPLog.VERBOSE);` and see if you see any of the logs that the method I linked above throws.
Thanks for writing in!

**Comment by takuyama29** [comment]
@patedit 

Thank you for your reply!

I set `MPLog.setLevel (MPLog.VERBOSE)` and sorted the log with the `Mixpanel API 'keyword, the following log was output.

```
I/MixpanelAPI.Messages: Exception when trying to register for GCM
java.io.IOException: INVALID_SENDER
at com.google.android.gms.iid.zzl.zzb(Unknown Source)
at com.google.android.gms.iid.zzl.zza(Unknown Source)
at com.google.android.gms.iid.InstanceID.zzb(Unknown Source)
at com.google.android.gms.iid.InstanceID.getToken(Unknown Source)
at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.runGCMRegistration(AnalyticsMessages.java:419)
at com.mixpanel.android.mpmetrics.AnalyticsMessages$Worker$AnalyticsMessageHandler.handleMessage(AnalyticsMessages.java:338)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:234)
at android.os.HandlerThread.run(HandlerThread.java:61)
```

When I changed SenderID, I got Registration ID successfully and I was able to confirm receipt of push notification.

I appreciate your cooperation!

**Comment by patedit** [comment]
Amazing! That means it works now? :)

**Comment by takuyama29** [comment]
Yes, that is working!

**Comment by patedit** [comment]
Great! I'll close this issue then. Thanks for trying Mixpanel!
