### ISSUE TITLE
Switch endpoint at runtime

### ISSUE THREAD

**Issue by drauly** [mixpanel/mixpanel-android#527]
Hello,

The library allows us to change mixpanel url in configuration. We would like to be able to do it at runtime (for AB testing purpose).

The idea is to be able to do :

```java
MixpanelAPI mixpanel = MixpanelAPI.getInstance(this, projectToken, "http://my.mixpanel.proxy");
```

Would you accept any PR to achieve that ? 

Thank you

**Comment by drauly** [comment]
Hello @patedit !

PR submitted

**Comment by patedit** [comment]
Issue resolved https://github.com/mixpanel/mixpanel-android/pull/530
