### ISSUE TITLE
Make it clear in README that ACCESS_NETWORK_STATE and BLUETOOTH permissions are optional for installation

### ISSUE THREAD

**Issue by kirillzh** [mixpanel/mixpanel-android#535]
Currently `README.md` makes it looks like all three permissions (`INTERNET`, `ACCESS_NETWORK_STATE` and `BLUETOOTH`) are required. `ACCESS_NETWORK_STATE` and `BLUETOOTH` are optional, so `README.md` should make it clear that only `INTERNET` is required for installation of the SDK.

**Comment by patedit** [comment]
Done :)
