### ISSUE TITLE
Tweak value always returns the default value for the first .get()

### ISSUE THREAD

**Issue by David-Eliyahu** [mixpanel/mixpanel-android#536]
hello @patedit
currently i'm using v5.3.0 and this issue is still reproduce.. can you please help me with that one
My scenario is exactly the same as described here.

**Comment by patedit** [comment]
Hey @David-Eliyahu !

If you call `get()` before the SDK receives all the experiments/tweaks from our server, then you will get the default value. Notice that this will **only** happen the first time the app opens after an experiment is created. It does not happen any time after because we now persist tweaks so as soon as you call `get()` you will read the right value.

If you want to use the value from the server as soon as it's received, you should use `OnMixpanelTweaksUpdatedListener` and you will get a callback as soon as the server response comes back (shouldn't take too long) and call `joinExperimentsIfAvailable()` inside the callback.

Hope that helps! Let me know if you have any other questions!

**Comment by joeymalysz** [comment]
` OnMixpanelUpdatesReceivedListener listener = new OnMixpanelUpdatesReceivedListener() {
            @Override
            public void onMixpanelUpdatesReceived() {
                mixpanel.getPeople().joinExperimentIfAvailable();
                ads = showAds.get();
                Log.d("Tweak Race Condition 3 ", String.valueOf(ads));
                //get
                // get tweak
            }
        };
        mixpanel.getPeople().addOnMixpanelUpdatesReceivedListener(listener);
        OnMixpanelTweaksUpdatedListener listener2 = new OnMixpanelTweaksUpdatedListener() {
            @Override
            public void onMixpanelTweakUpdated(Set<String> updatedTweaksName) {
                    ads = showAds.get();
                    Log.d("Tweak Race Condition 2", String.valueOf(ads));

            }
        };


        mixpanel.getPeople().addOnMixpanelTweaksUpdatedListener(listener2);
        ads = showAds.get();
        Log.d("Tweak Race Condition 1 ", String.valueOf(ads));

        Timer timer = new Timer();
        timer.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                // Your database code here
                ads = showAds.get();
                Log.d("Tweak Race Condition 4", String.valueOf(ads));
            }
        },1000, 1000);`

**Comment by joeymalysz** [comment]
`        OnMixpanelUpdatesReceivedListener listener = new OnMixpanelUpdatesReceivedListener() {
            @Override
            public void onMixpanelUpdatesReceived() {
                mixpanel.getPeople().joinExperimentIfAvailable();
                ads = showAds.get();
                Log.d("Tweak Race Condition 1 ", String.valueOf(ads));
            }
        };
        mixpanel.getPeople().addOnMixpanelUpdatesReceivedListener(listener);
        OnMixpanelTweaksUpdatedListener listener2 = new OnMixpanelTweaksUpdatedListener() {
            @Override
            public void onMixpanelTweakUpdated(Set<String> updatedTweaksName) {
                    ads = showAds.get();
                    Log.d("Tweak Race Condition 2", String.valueOf(ads));

            }
        };
        mixpanel.getPeople().addOnMixpanelTweaksUpdatedListener(listener2);`

**Comment by orium-dev** [comment]
@patedit  Tried as you described but still receive default value

**Comment by patedit** [comment]
@orium-dev I've updated the comment with an example. Let me know if it works for you!

**Comment by orium-dev** [comment]
@patedit I tried your code, but still receive false from boolean tweak in onMixpanelTweakUpdated, although I created a/b experiment with 100% true value.
I ended up with polling tweak on timer, but even this not help in 100% cases
`subscription.add(Observable.interval(1200, TimeUnit.MILLISECONDS)
                        .take(5)
                        .observeOn(AndroidSchedulers.mainThread())
                        .subscribe(aLong -> {
                            boolean showBtn = readTweakValue();
                            if (showBtn && btnSkip.getVisibility() == View.GONE) {
                                UiUtil.setVisible(btn, true);
                                subscription.clear();
                            }
                        })
                );`

**Comment by patedit** [comment]
Hi @orienwu , that's def very strange. Would you mind writing into support@mixpanel.com and share some of your code? Thanks!

**Comment by patedit** [comment]
Customer was using wrong tokens. Closing this issue!
