### ISSUE TITLE
Stop using Google Cloud Messaging and use Firebase messaging Instead

### ISSUE THREAD

**Issue by heliomartins** [mixpanel/mixpanel-android#548]
Hey guys,

This is something that you guys should have a look. Google has deprecated the Google Cloud Messaging and it will be removed next year, 11/04/2019.

https://developers.google.com/cloud-messaging/faq

If need any help setting this up, let me know.

**Comment by DonalRafferty** [comment]
+1

**Comment by patedit** [comment]
Hi @heliomartins ! Sorry for the late response, we are going to work on this very soon - stay tuned :)

**Comment by heliomartins** [comment]
@patedit, really appreciate. Thanks a lot.

**Comment by sipersso** [comment]
Any updates on this?

**Comment by horaciosolorio** [comment]
@patedit  I need help , i need to use Firebase, i can´t make it work can you help me please.

**Comment by patedit** [comment]
Hey @horaciosolorio - have you tried following this tutorial https://mixpanel.com/help/reference/android-push-notifications ?

**Comment by horaciosolorio** [comment]
Yes, 
I follow the tutorial but in this tutorial in manifest need to add :

<receiver android:name="com.mixpanel.android.mpmetrics.GCMReceiver"
          android:permission="com.google.android.c2dm.permission.SEND" >
    <intent-filter>
        <action android:name="com.google.android.c2dm.intent.RECEIVE" />
        <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
        <category android:name="YOUR_PACKAGE_NAME" />
    </intent-filter>
</receiver>

But this receiver is not necessary whit FCM , because for FCM just i need to add FirebaseMessagingService , GCMReceiver just is form GCM notifications.

Please help me , maybe I'm misunderstanding the steps .

**Comment by patedit** [comment]
We do use GCM, but if you send the notification from your Firebase instance, it should work. If you are having issues can you send us an e-mail at support@mixpanel.com? Thanks!

**Comment by patedit** [comment]
A new version [v5.5.0 was just released](https://github.com/mixpanel/mixpanel-android/releases/tag/v5.5.0) with FCM support 👍
