### ISSUE TITLE
IllegalStateException: Can not perform this action after onSaveInstanceState on InAppFragment

### ISSUE THREAD

**Issue by correonano** [mixpanel/mixpanel-android#549]
Hi. We are having a crash on the first line on onSaveInstanceState  for class InAppFragment:

    @Override
    public void onSaveInstanceState(Bundle outState) {
        cleanUp();
        super.onSaveInstanceState(outState);
    }

I think you cannot call "cleanUp()" before call "super".

com.mixpanel.android.mpmetrics.InAppFragment.cleanUp (InAppFragment.java:258)
com.mixpanel.android.mpmetrics.InAppFragment.onSaveInstanceState (InAppFragment.java:240)

thanks in advance

**Comment by patedit** [comment]
hi @correonano - do you mind sharing the stack trace with us? What SDK version are you using? Thanks!
