### ISSUE TITLE
Issue in Fetching tweak value

### ISSUE THREAD

**Issue by ankit24x7** [mixpanel/mixpanel-android#551]
Always get default value of Tweak and we get fresh value if we call again MixpanelAPI.booleanTweak("enableHydra", false).get().

Also if in between we change value from mixpanel that value is not fetched unless the application is killed. Please help

Code Snippet: 
 MixpanelAPI mMixpanel = MixpanelAPI.getInstance(this, getResources().getString(R.string.mixpanel_token));
 MixpanelAPI.People people = mMixpanel.getPeople();
     people.initPushHandling(getResources().getString(R.string.project_number));
mMixpanel.getPeople().addOnMixpanelUpdatesReceivedListener(new OnMixpanelUpdatesReceivedListener() {
  @Override
 public void onMixpanelUpdatesReceived() {
  mMixpanel.getPeople().joinExperimentIfAvailable(); 
            }        });
MixpanelAPI.booleanTweak("enableHydra", false).get()

**Comment by argenisf** [comment]
Hey @ankit24x7 , we just replied to your support case regarding checking the value on the Tweak Updated receiver. Let's follow up through there.
