### ISSUE TITLE
Can not find com.mixpanel.android.mpmetrics.GCMReceiver  in 5.3.1

### ISSUE THREAD

**Issue by PenzK** [mixpanel/mixpanel-android#553]
As tutorial says it should be, but can not reach it
So couldn't update to 5.3.1 as it doesn't compile

![b02333463b](https://user-images.githubusercontent.com/4975835/40730239-dada7f0a-6436-11e8-8039-766875e7fba6.jpg)

(PS: 4.9.2 works just fine)

**Comment by patedit** [comment]
Hey @PenzK, thanks for writing in! Have you tried cleaning up your project and syncing gradle again? I just tried it myself and 5.3.1 works fine :)

**Comment by PenzK** [comment]
Seems, you are right, my fault. Now its workin' , I definitely did it earlier, but without success
Thnaks!
