### ISSUE TITLE
Removing/blacklisting default properties for events

### ISSUE THREAD

**Issue by berkeragir** [mixpanel/mixpanel-android#554]
Hello,

Currently, there is no functionality for blocking sending of some default properties to MixPanel within the Android library in a selective way (this is only possible with the Javascript library apparently: https://help.mixpanel.com/hc/en-us/articles/115004601523-Block-Default-Mixpanel-Properties).

Are there any plans to include such a functionality to the Android library as well? Currently, the existing properties (heavily related to the device) clutter the event details in Activity Feed in MixPanel, and thus, such a support for blocking a list of properties would be great.

Thanks!

**Comment by patedit** [comment]
Hi @berkeragir. This is a great suggestion - thanks for writing in! We currently have no plans to support this functionality but I'll leave this ticket open to address this issue in the future. In the meantime, feel free to create a PR for this feature and I'll be happy to take a look at it :)
