### ISSUE TITLE
Sending enums as properties fails silently

### ISSUE THREAD

**Issue by vibin** [mixpanel/mixpanel-android#559]
The SDK is using org.json for JSON processing needs and turns out on Android v4.4 and later, `org.json.JSONObject` replaces enum values in a Map with null. See https://android.googlesource.com/platform/libcore/+/690809f/json/src/main/java/org/json/JSONObject.java#786.

Specifically, I got bitten by `MixpanelAPI#registerSuperPropertiesMap(Map<String, Object>)`, which uses `org.json.JSONObject(Map)` to convert Map to a JSONObject.

**Comment by zihejia** [comment]
hi @vibin , Unfortunately, JSONObject does not support the correct serialization of enums. As a workaround, you can add getter into the enum. In the future, we might upgrade it. Sorry about the inconvenience.

**Comment by headsvk** [comment]
I also came across this issue, it's very unexpected and requires a lot of debugging.

Can you at least write in the FAQ that enums as property values don't work?

**Comment by zihejia** [comment]
hi @headsvk , sorry about the inconvenience. We will add it.
