### ISSUE TITLE
Event property limits

### ISSUE THREAD

**Issue by vibin** [mixpanel/mixpanel-android#562]
Hi, are there any undocumented limits on event property sizes? We are seeing Mixpanel library silently fail when tracking events with event properties payload of 18000+ characters (excluding super properties and default properties). 

Logcat output of `MixpanelAPI.Messages` tag doesn't help:

```
Successfully posted to https://api.mixpanel.com/track?ip=1:
{payload here}
Response was {"status": 1, "error": null} (Thread 39438)
Not retrying this batch of events, deleting them from DB. (Thread 39438)
```

**Comment by vibin** [comment]
Also, is the "255 characters per list property" limit really enforced? https://help.mixpanel.com/hc/en-us/articles/115004616466-Property-Limits

I'm able to track events with a list property containing items of 300+ characters each.

**Comment by patedit** [comment]
Hi @vibin - do you mind sending us an email at support@mixpanel.com. This issue seems unrelated to the Android sdk. Someone smarter than me will help you! Thank you!
