### ISSUE TITLE
Can't sync gradle: No resource found

### ISSUE THREAD

**Issue by leokho** [mixpanel/mixpanel-android#563]
Hey!
Seems like I'm keeping getting this error:

No resource found that matches the given name (at 'colorControlNormal' with value '@color/com_mixpanel_android_inapp_light_gray').
Message{kind=ERROR, text=No resource found that matches the given name (at 'colorControlNormal' with value '@color/com_mixpanel_android_inapp_light_gray')., sources=[.../app/build/intermediates/res/merged/production/debug/values/values.xml:3843:41-85], original message=, tool name=Optional.of(AAPT)}

Any idea what this could be?

**Comment by patedit** [comment]
Sorry for the late response! `com_mixpanel_android_inapp_light_gray` color was removed on version 4.9.4 - cleaning your project should've resolved the issue :)
