### ISSUE TITLE
No way to disable attaching exception handler from Mixpanel

### ISSUE THREAD

**Issue by josephmbeveridge** [mixpanel/mixpanel-android#565]
Similar to this issue https://github.com/mixpanel/mixpanel-iphone/issues/704 the Android sdk is causing crash loops because it tries to hook up an exception handler when I already use another library for crash tracking. This causes a loop because mix panel attaches and grabs my other lib as the default handler.

While I have a workaround, ideally we would like to specify that Mixpanel shouldn't attach an exception handler as we don't use Mixpanel for crash reporting.

**Comment by patedit** [comment]
Hi @josephmbeveridge ! What do you use for crash reporting?

**Comment by patedit** [comment]
@josephmbeveridge would love to know more about your issue, since i've not been able to reproduce it. What was the workaround you implemented?
I've added the option to disable our exception handler on https://github.com/mixpanel/mixpanel-android/pull/572
