### ISSUE TITLE
Add Mobile Network information

### ISSUE THREAD

**Issue by jnagels** [mixpanel/mixpanel-android#57]
It would be nice to add the information about whether or not the device is connected to a mobile network. Similar to the Wifi-information. Shouldn't be that hard looking at SystemInformation.java and AnalyticsMessages.java

**Comment by yinfeiru** [comment]
@jnagels I know it's been a long time.. Trying to follow up on this. Why do you think such info is useful? I might be missing something here. But, if a user is not connecting to both of wifi and mobile network, Mixpanel won't receive any data. So, if `$wifi` is false, you can assume the user is on mobile network.

**Comment by jnagels** [comment]
@yinfeiru When offline, we cache the events and send them when the device is back online. So it's interesting to see which events happen offline vs online.

**Comment by yinfeiru** [comment]
@jnagels it's legit. will do.
