### ISSUE TITLE
Carrier property incorrect when roaming

### ISSUE THREAD

**Issue by ryanseams** [mixpanel/mixpanel-android#573]
Right now the SDK uses [TelephonyManager](https://developer.android.com/reference/android/telephony/TelephonyManager) with method [`getNetworkOperatorName()`](https://developer.android.com/reference/android/telephony/TelephonyManager#getNetworkOperatorName()) to determine the `$carrier` property. This is not consistent with iOS which uses the SIM card network, and causes the `$carrier` property to change values on Android when the user is roaming.

Can this be updated to use [`getSimOperatorName()`](https://developer.android.com/reference/android/telephony/TelephonyManager#getSimOperatorName()) as this is the true `$carrier` of the SIM card in the phone? This also achieves parity with iOS SDKs.

**Comment by zihejia** [comment]
closing this one now for housekeeping. We won't change it cause it doesn't require special permissions(a big issue after android 30) to access for now.
