### ISSUE TITLE
FCM support

### ISSUE THREAD

**Issue by phicdy** [mixpanel/mixpanel-android#574]
We're using push notification in mixpanel via GCM and also normal GCM. GCM is going to be the end in next April, we're migrating GCM to replace normal GCM. However, mixpanel is still using GCM...GCM and FCM can't exist in an app, we're going to stop to use push notification in mixpanel until the release of SDK that support FCM.
Do you have the plan to release it ?

**Comment by argenisf** [comment]
hey @phicdy, we are planning to migrate to FCM (timeline not ready yet), but you can definitely migrate your project to FCM, and have a FCM receiver even when we send the payload through GCM's service. Feel free to open a support case to follow up if you have questions on how to proceed.

**Comment by phicdy** [comment]
@argenisf Thank you for the response. We already deleted all of the permissions and the library for GCM/C2DM and no plan to re-add them. Can we receive the notifiation in FCM receiver in this situation ?

**Comment by argenisf** [comment]
@phicdy you sure can. Your receiver would need to create the FCM push token, upload that token to Mixpanel, and then display the incoming intent, but it's definitely doable even if we send the intent through GCM

**Comment by phicdy** [comment]
@argenisf I think we can't receive the message without permission. Because we can't register GCM token of the device to mixpanel server. When we call `MixpanelAPI#initPushHandling()`, it failed in `ConfigurationChecker.checkPushConfiguration()`

```
2018-12-05 13:54:46.205 332-332/com.sample W/MixpanelAPI.ConfigurationChecker: Application does not define permission com.sample.permission.C2D_MESSAGE
```

**Comment by argenisf** [comment]
hey @phicdy initPushHandling() is handled by our own GCM Receiver to generate tokens. Since you are not using GCM anymore, you need to have your own receiver that generates the FCM token, [and passes it on](https://developer.mixpanel.com/docs/android-push-notifications#section-advanced-features) to Mixpanel. In case you're not sure how to proceed, please create a support request so our team can follow up

**Comment by patedit** [comment]
A new version [v5.5.0 was just released](https://github.com/mixpanel/mixpanel-android/releases/tag/v5.5.0) with FCM support 👍
