### ISSUE TITLE
Not able to send in-app message on android 8 and above

### ISSUE THREAD

**Issue by sysquare** [mixpanel/mixpanel-android#578]
We have scheduled in app messages but its not showing up on android 8 and above at all, even on other android devices its taking approx 45 min to 1 hour to display. Although its working fine in IOS.
Is there anything specific which we have to take care of ?

I have already written to support@mixpanel.com and ready to purchase your PEOPLE plan as well but want to make sure that everything works as expected.

Can someone please help on priority as we are already LIVE on app store and we have our event on 7th Feb 8 AM EST

**Comment by patedit** [comment]
Hi @sysquare ! Is it a take over in-app? If so, you need to add the activity to your `AndroidManifest.xml` file. Also, if you do not have `com.mixpanel.android.MPConfig.AutoShowMixpanelUpdates` config on your AndroidManifest.xml it should work out of the box. If you do, make sure it's set to `true` or otherwise you need to manually call `showNotificationsIfAvailable()`

There is no limitation for Android 8.0+ as far as we know. If you have a device where you can reproduce the issue, could you add the following meta-tag to your `AndroidManifest.xml` file and share any relevant logs that you see with our support team?

```
...
<application>
    <meta-data
      android:name="com.mixpanel.android.MPConfig.EnableDebugLogging"
      android:value="true" />
    ...
</application>
...
```

**Comment by sysquare** [comment]
We are on paid plan and we have written to mixpanel support as well but no response yet. Its been more than 16 hours. Below is what we using :

We are using mixpanel  android sdk in our app.
implementation 'com.mixpanel.android:mixpanel-android:5.+'

Project name : Drone Nation Dev
Account Owner email : jasonfinder@buddynation.com


We are facing issues with in-app-message it works sometimes and sometimes it doesn't.
Is there any specific conditions for in-app-message to appear on User's Device ?

However push notifications are working perfectly fine.




I'm using the below code in my app whenever sign or login happens and on app foreground launch if the user is already logged in.

public void identifyMixpanel(Context context){
    try{
        String deviceToken =  FirebaseInstanceId.getInstance().getToken();
        MixpanelAPI mixpanelAPI = MixpanelAPI.getInstance(context,context.getResources().getString(R.string.MIXPANEL_KEY_TOKEN_DEV));
        mixpanelAPI.identify(Applications.users.getUserId()+"");
        mixpanelAPI.getPeople().identify(Applications.users.userId+"");
        mixpanelAPI.getPeople().initPushHandling(context.getResources().getString(R.string.FCM_PROJECT_NUMBER_DEV));
        mixpanelAPI.getPeople().setPushRegistrationId(deviceToken);
    }catch (Exception e){

    }

}

Below code I've added into manifest file.
<activity android:name="com.mixpanel.android.takeoverinapp.TakeoverInAppActivity"
    android:theme="@style/com_mixpanel_android_TakeoverInAppActivityTheme"/>
<receiver
    android:name="com.mixpanel.android.mpmetrics.GCMReceiver"
    android:permission="com.google.android.c2dm.permission.SEND" >
    <intent-filter>
        <action
            android:name="com.google.android.c2dm.intent.RECEIVE" />
        <action
            android:name="com.google.android.c2dm.intent.REGISTRATION" />
        <category android:name="com.buddynation.DroneNation" />
    </intent-filter>
</receiver>Hi Support,

We are using mixpanel  android sdk in our app.
implementation 'com.mixpanel.android:mixpanel-android:5.+'

Project name : Drone Nation Dev
Project Token : a826082013ab22461bdac143b7a2d2dd


We are facing issues with in-app-message it works sometimes and sometimes it doesn't.
Is there any specific conditions for in-app-message to appear on User's Device ?

However push notifications are working perfectly fine.




I'm using the below code in my app whenever sign or login happens and on app foreground launch if the user is already logged in.

public void identifyMixpanel(Context context){
    try{
        String deviceToken =  FirebaseInstanceId.getInstance().getToken();
        MixpanelAPI mixpanelAPI = MixpanelAPI.getInstance(context,context.getResources().getString(R.string.MIXPANEL_KEY_TOKEN_DEV));
        mixpanelAPI.identify(Applications.users.getUserId()+"");
        mixpanelAPI.getPeople().identify(Applications.users.userId+"");
        mixpanelAPI.getPeople().initPushHandling(context.getResources().getString(R.string.FCM_PROJECT_NUMBER_DEV));
        mixpanelAPI.getPeople().setPushRegistrationId(deviceToken);
    }catch (Exception e){

    }

}

Below code I've added into manifest file.
<activity android:name="com.mixpanel.android.takeoverinapp.TakeoverInAppActivity"
    android:theme="@style/com_mixpanel_android_TakeoverInAppActivityTheme"/>
<receiver
    android:name="com.mixpanel.android.mpmetrics.GCMReceiver"
    android:permission="com.google.android.c2dm.permission.SEND" >
    <intent-filter>
        <action
            android:name="com.google.android.c2dm.intent.RECEIVE" />
        <action
            android:name="com.google.android.c2dm.intent.REGISTRATION" />
        <category android:name="com.buddynation.DroneNation" />
    </intent-filter>
</receiver>

**Comment by patedit** [comment]
Can you enable debugging and send your logs? See my first message here. Thanks!

**Comment by sysquare** [comment]
We did that but not sure what logs should I provide and how I provide as I am not getting any in-app message.
Can you please help me here

**Comment by sysquare** [comment]
Cant see nay logs as such and even for versions less than android 8, it takes too much of time . While in IOS in-app message shows in 4-5 mins max, sometimes even in 1-2 mins

**Comment by patedit** [comment]
Closing as our support team was looped in on an e-mail thread.

**Comment by alexhover** [comment]
Is there any resolution on this issue you can share with the larger Mixpanel community?
