### ISSUE TITLE
Remove default event 

### ISSUE THREAD

**Issue by abhayjaiswal** [mixpanel/mixpanel-android#580]
We need to remove "First App Open" event on dashboard  using code on mixpanel . how it will be possible ??
I have not got any way to block or predefined event  .

**Comment by patedit** [comment]
Hi @abhayjaiswal - "First App Open" is part of our Mixpanel default events. If you do not wish to collect those events,

**Comment by patedit** [comment]
Hi @abhayjaiswal ! If you want to disable automatic common mobile events tracking you should follow this steps:
1. Log in into mixpanel.com
2. Go to your project settings (click on gear icon on the right upper corner)
3. On the left panel select Autotrack
4. Disable "Automatically collect common mobile events"

Hope that helps!
