### ISSUE TITLE
Caused by java.lang.ClassNotFoundException: Didn't find class "com.mixpanel.android.mpmetrics.GCMReceiver"

### ISSUE THREAD

**Issue by gadaramaulik** [mixpanel/mixpanel-android#584]
Caused by java.lang.ClassNotFoundException: Didn't find class "com.mixpanel.android.mpmetrics.GCMReceiver" on path: DexPathList[[zip file "/data/app/com.contractorforeman-2/base.apk"],nativeLibraryDirectories=[/data/app/com.contractorforeman-2/lib/arm, /data/app/com.contractorforeman-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3285)
       at android.app.ActivityThread.-wrap20(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1715)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1534)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1424)

**Comment by gadaramaulik** [comment]
How to solve this error?

**Comment by biodunalfet** [comment]
We're experiencing same error. How do we fix this?

**Comment by patedit** [comment]
Version 5.5.0 removes Google Cloud Messaging and uses Firebase Cloud Messaging instead. Class `GCMReceiver` has been removed in v5.5.0. It's very easy to migrate, just follow [these simple steps](https://github.com/mixpanel/mixpanel-android/releases/tag/v5.5.0).

**Comment by wman1980** [comment]
why is the official documentation not updated?
see: https://developer.mixpanel.com/docs/android-push-notifications

btw: I followed there instructions https://github.com/mixpanel/mixpanel-android/releases/tag/v5.5.0, but currently my pushes don't work with mix panel. From firebase its working.

**Comment by wman1980** [comment]
ok, I solved my issue. Problem was that I still needed to update the people.setPushRegistrationId(token) after a user logged in.

**Comment by wman1980** [comment]
@patedit I have one last question.

 With the old setup (GCMReceiver) I added some default data to the intent:
`public class PushNotificationReceiver extends GCMReceiver {

    @Override
    public void onReceive(Context context, Intent intent) {
        if (intent.getExtras() == null || !intent.getExtras().containsKey("mp_icnm")) {
            intent.putExtra("mp_icnm", "ic_notification_icon");
        }

        if (intent.getExtras() == null || !intent.getExtras().containsKey("mp_color")) {
            intent.putExtra("mp_color", "#FF9ecb84");
        }
        super.onReceive(context, intent);
    }
}
`

Is something like this still possible with extending MixpanelFCMMessagingService?

Thanks!

**Comment by patedit** [comment]
Hi @wman1980 ! You'd need to override `onMessageReceived(RemoteMessage remoteMessage)`. Since that's not straight forward... I've just exposed a new method with similar signature as our old one so you can override now `onMessageReceived(Context context, Intent messageIntent)`. This will be available in the next release that is happening tomorrow.

Thank you!

**Comment by patedit** [comment]
Release [version 5.5.1](https://github.com/mixpanel/mixpanel-android/releases/tag/v5.5.1) which adds this feature @wman1980 

Also, I encourage everyone to update to that version since it also contains some other fixes with regards to FCM.
