### ISSUE TITLE
$device_id and $had_persisted_distinct_id under "Your Properties"

### ISSUE THREAD

**Issue by alixwar** [mixpanel/mixpanel-android#585]
When looking in the Live view for events that have been reported there are two properties listed that I have not defined:
- $device_id
- $had_persisted_distinct_id

I had expected these to be listed under "All Properties" but they are currently listed also under "Your Properties"

I have used Mixpanel Android version 5.5.0 to report the events.

**Comment by Bondes87** [comment]
I have a similar problem: I have not defined the $had_persisted_distinct_id, but it
is currently listed also under "Your Properties".
I have used Mixpanel Android version 5.6.3 to report the events.

**Comment by IsaiahJTurner** [comment]
Me too, minor bug but should be fixed.

**Comment by taimur113311** [comment]
@alixwar 
The issue is still occurring or Fixed?

**Comment by alixwar** [comment]
@taimur113311 it seems to work now, I'm no longer seeing these superfluous properties under "Your properties"

Using version 5.6.4 of the Android library.

**Comment by jackryan0307** [comment]
Check in a web browser on the device if the URL works. If you see **[this](https://www.wpoven.com/blog/how-to-fix-dns_probe_finished_nxdomain-error/)** then it's probably a DNS config problem on the device itself?
