### ISSUE TITLE
Multiple devices bearing the same device token

### ISSUE THREAD

**Issue by benedict-lim** [mixpanel/mixpanel-android#588]
As I login and logout of multiple accounts on my app,  and identify them as the respective Mixpanel users which have been aliased with the app-side user IDs, I realized that all of them bear the same device token.

This is undesirable as I would like to send push notifications which are meant only for the current logged in user.
If the logged out user continues to bear the same device token, push notifications would be sent if target criteria is met.

As a stop-gap measure, I made sure to delete the `$android_devices` property of the previous user, before identifying the current user.
However, as a side-effect, if the previous user is registered on multiple devices, the user would be uncoupled from the other devices as well.

I've not seen much documentation regarding device tokens, so forgive me if a solution already exists.
Please kindly point me in the right direction to solving this issue.

**Comment by patedit** [comment]
I see your problem and I'm sure many other people have the same problem. I think the following snippet would solve your issue:

```java
public void logOut() {
     String deviceToken = mMixpanel.getPeople().getPushRegistrationId();
     mMixpanel.getPeople().clearPushRegistrationId(deviceToken); 
     mMixpanel.reset();
}
```

Hope that helps!

**Comment by benedict-lim** [comment]
Thanks @patedit ! Your solution did indeed solved my issue.
I didn't realize that the device token is the GCM push registration ID itself.
Please keep up the great work!
