### ISSUE TITLE
5.5.1 not available on Maven Central

### ISSUE THREAD

**Issue by alixwar** [mixpanel/mixpanel-android#589]
I don't see 5.5.1: https://mvnrepository.com/artifact/com.mixpanel.android/mixpanel-android

**Comment by patedit** [comment]
Sorry about that @alixwar - new version 5.5.1 it's now on maven central repo http://central.maven.org/maven2/com/mixpanel/android/mixpanel-android/5.5.1/
That website might take an extra 1-2 hours to update. The library is on maven central, though. Thank you!
