### ISSUE TITLE
Feature request: "Dry run" / Testability

### ISSUE THREAD

**Issue by alixwar** [mixpanel/mixpanel-android#591]
I feel that `MixpanelAPI` is lacking in terms of testability.

**Situation right now (5.5.1)**
- `MixpanelAPI` is not `final` which is good (= Possible to mock without bytecode manipulation)
- `MixpanelAPI` does not have a public constructor (= Not possible to create dummy subclasses)
- `MixpanelAPI.getInstance()` returns `null` under Robolectric ( = Tests fail due to NPE)

**Workaround**
- Setting up a wrapper class for `MixpanelAPI` where the tests replace the "real" instance (=`null`) with a mock instance

**Suggestions (alternatives)**
- (my favourite suggestion) Make constructor public so that integrators can create their own dummy implementations of MixpanelAPI and e.g. use the [Shadow feature of Robolectric](http://robolectric.org/extending/)
- (perhaps too much....) Release a mocking-library, `mixpanel-android-mock` with an API that configures Mixpanel (["dry run"](https://developers.google.com/analytics/devguides/collection/android/v3/advanced#dryrun)) to return reasonable dummy objects. Example of such library: https://github.com/square/retrofit/tree/master/retrofit-mock

**Comment by patedit** [comment]
Thanks a lot for the suggestion! So I understand it a bit better, can you pass a mock context when creating a Mixpanel instance?

**Comment by alwa** [comment]
@patedit Yes, Robolectric can create such fake contexts

**Comment by alixwar** [comment]
@patedit Any updates on this?

**Comment by alixwar** [comment]
My workaround:

New class:
``` 
package com.mixpanel.android.mpmetrics;

// Imports...
public class StubbedMixpanelAPI extends MixpanelAPI {

    @SuppressLint("NewApi")
    public StubbedMixpanelAPI(@NonNull Context context) {
        super(context, CompletableFuture.completedFuture(
                context.getSharedPreferences("dummy", Context.MODE_PRIVATE)), "", true);
    }

}

```
In my production code:
```
...
isRoboUnitTest() ? new StubbedMixpanelAPI(context) : MixpanelAPI.getInstance(context, BuildConfig.ANALYTICS_TOKEN, false);
...
    private static boolean isRoboUnitTest() {
        return "robolectric".equals(Build.FINGERPRINT);
    }
```

**Comment by patedit** [comment]
Thanks for the snippet @alixwar. Sadly adding this feature is not on our roadmap and since there is an existing workaround, other devs will find this useful.

**Comment by alixwar** [comment]
With the new "Looper mode" in Robolectric, the workaround is now broken unfortunately
