### ISSUE TITLE
Initial App Open event missing super property

### ISSUE THREAD

**Issue by RiteshChandnani** [mixpanel/mixpanel-android#592]
We have a super property set and we have auto tracking turned on for `App Open` via app manifest but when we open the app for the very first time the super property is not being tracked.
But when we open the app second time the property is there.

**Comment by RiteshChandnani** [comment]
Aah, I feel it is happening because of - https://github.com/mixpanel/mixpanel-android/blob/master/src/main/java/com/mixpanel/android/mpmetrics/MixpanelAPI.java#L298

**Comment by patedit** [comment]
hi @RiteshChandnani - you are correct, super properties are applied to all events from the moment they are set :) Feel free to open this ticket if you have problems with the SDK

**Comment by RiteshChandnani** [comment]
Yeah this actually creates inconsistency in our tracking data

**Comment by RiteshChandnani** [comment]
@patedit Any chance of fixing this?

**Comment by headsvk** [comment]
this issue was fixed for iOS lately https://github.com/mixpanel/mixpanel-swift/issues/189

**Comment by RiteshChandnani** [comment]
Fixed in #651 🥳
Thanks @patedit.
