### ISSUE TITLE
Updating to Mixpanel Android 5.5

### ISSUE THREAD

**Issue by ChrisEdson** [mixpanel/mixpanel-android#593]
Is there any chance we could update to the latest Mixpanel Android (5.5) - so that we can get FCM support?

**Comment by patedit** [comment]
Not sure if I understand your question, you just need to update your gradle file and use whatever version you want. I recommend using the latest (5.6.0) since it includes several FCM bug fixes as well

**Comment by ChrisEdson** [comment]
Apologies - wrong repo! I meant to post this in the react-native-mixpanel repo!

**Comment by patedit** [comment]
Ah, no worries :)
