### ISSUE TITLE
Can not filter out the User

### ISSUE THREAD

**Issue by binwin20** [mixpanel/mixpanel-android#596]
I have login two accounts(Distinct ID is 146587004 and 146586004) with two devices, both device’s userLanguage is en_US, but can't filter out the user when sending a push notification.

## User Detail:
1. Distinct ID:146587004
    mailboxId: 146587004
    companyId: 146584004
    Processing Time: 1555032937306
    Device ID: b858b112-64b3-4aba-80c4-01d021c46fe3
![image](https://user-images.githubusercontent.com/3467850/56009030-e424fd00-5d10-11e9-898d-3a91edd945fb.png)

2. Distinct ID:146586004
    mailboxId: 146586004
    companyId: 146584004
    Processing Time: 1555033757770
    Device ID: 79a95120-3e65-439a-85c3-9c477562bda2
![image](https://user-images.githubusercontent.com/3467850/56009053-f30baf80-5d10-11e9-9588-33ff717dd8f8.png)

## Filter out user in (Users -> Explore)
The User was existed(companyId is 146584004, userLanguage is en_US)
![image](https://user-images.githubusercontent.com/3467850/56009094-25b5a800-5d11-11e9-9dd1-e59556a54a35.png)

## Can not filter the user in (Take Action -> message -> push notification -> Target criteria)
filter user with "userLanguage=en_US", but these two users are logined last day and companyId are not 146584004, can not filter out the user I have just login.
![image](https://user-images.githubusercontent.com/3467850/56009164-6dd4ca80-5d11-11e9-8f82-777d6c766c62.png)

**Comment by binwin20** [comment]
Found the root cause, when I logout out an account,I will call `mMixpanelAPI.getPeople().clearPushRegistrationId();`. And login to other account, RCGcmListenerService.onNewToken() will not be called, so the "$android_devices" is empty. 

I think notify user to set the token at correct time is more friendly.

**Comment by patedit** [comment]
Hi @binwin20! Once the new user logs in you probably want to assign that user a FCM token right away. You should do something like:

```
public void onUserLoggedIn() {

FirebaseInstanceId.getInstance().getInstanceId()
                        .addOnCompleteListener(new OnCompleteListener<InstanceIdResult>() {
        @Override
        public void onComplete(@NonNull Task<InstanceIdResult> task) {
            if (task.isSuccessful()) {
                String fcmToken = task.getResult().getToken();
                MixpanelAPI.getInstance(this, "token").setRegistrationId(fcmToken);
            }
        }
    });
}
```
