### ISSUE TITLE
Super properties are not sent with the common "First App Open" event

### ISSUE THREAD

**Issue by headsvk** [mixpanel/mixpanel-android#597]
I'm registering super properties right after initializing the instance, but they don't get sent for the First App Open event. All other common mobile events will include the super properties.

Would be nice if there was an option to set super properties within the initialize or if the internal First App Open event gets deferred.

This is a copy of an issue that got fixed on iOS and I expect Android to work the same.
I recently discovered the difference between the libraries and library versions and now the logged data in our Mixpanel project is a mess.
https://github.com/mixpanel/mixpanel-swift/issues/189

**Comment by PatrickGaissert** [comment]
We have the same problem in our app, could you please give an update on this?

**Comment by jwinkler92** [comment]
As we are using the super properties to distinguish between multiple white-label apps this is also a "must" for us. Anyone who could help?

**Comment by carstenhag** [comment]
This issue is also being tracked on the Mixpanel community: https://community.mixpanel.com/idea/471/initial-set-of-super-properties-for-ios-and-androi.html

>We filed a product gap on your behalf with our Engineering and Product Development team. Make sure you are following this Idea - via the button in the upper right hand corner - to get emailed updates on its progress.

**Comment by patedit** [comment]
Thanks @carstenhag for the remainder. You can now initialize the SDK by passing superproperties directly so `First App Open` will include those props.
`MixpanelAPi.getInstance(this, MY_TOKEN, superPropsJsonObject)`

Will update the community center on Monday. Thanks all!

**Comment by carstenhag** [comment]
Thanks, just updated and tried it out. Works great.

One thing I'd like to mention though, is that you could annotate the [nullability of parameters with annotations](https://www.jetbrains.com/help/idea/nullable-and-notnull-annotations.html). 

`public static MixpanelAPI getInstance(Context context, String token, JSONObject superProperties) {
` and the other constructors misses those annotations. Adding these also makes it easier to konvert to kotlin in the future.

Only looking at the source code (which is nice that it's available), I was able to tell that `superProperties` could be `@Nullable` 😄 .

**Comment by patedit** [comment]
Absolutely, it has been in the back of my mind for a long time but never had the chance to properly go through it. Having at least the public APIs with proper annotations would be super useful.. I'll see if I can spend some time on it
