### ISSUE TITLE
Push notifications improvements issue // Notification Handler 

### ISSUE THREAD

**Issue by eduardo-calzado-agentero** [mixpanel/mixpanel-android#598]
Hi guys,

Does anybody have issues with that?

I implemented this code on my android project, I'm receiving correctly the push notification but I can't handle the push from Mixpanel. I don't know why, but method is never called.

```
public class CustomMixpanelFirebaseMessaging extends MixpanelFCMMessagingService {
     @Override
     protected void onMessageReceived(Context context, Intent intent) {
         if (intent.getExtras().containsKey("mp_message")) {
             intent.putExtra("mp_message", "CUSTOM MESSAGE");
         }
         super.onMessageReceived(context, intent);
     }
}
```

Maybe someone could help me with it. Any help it'll be more than appreciate.
Regards!!!

**Comment by patedit** [comment]
Hi @eduardo-calzado-agentero - did you include `CustomMixpanelFirebaseMessaging` on your `AndroidManifest.xml` file?
