### ISSUE TITLE
`timeEvent` uses wall clock time, which can be adjusted backwards and result in weird `$duration` values

### ISSUE THREAD

**Issue by dougkeen** [mixpanel/mixpanel-android#605]
When capturing short event durations at scale, it's common to see negative `$duration` values because the device adjusted its wall time backwards while the event was being timed. It may be better to measure durations with `System.nanoTime()`.

**Comment by zihejia** [comment]
hi @dougkeen , sorry for the late response. I'm afraid `System.nanoTime()` will have the same problem if the user adjusts the wall clock time. I'm closing this one now, please feel free to reopen if needed.
