### ISSUE TITLE
MD5 is a weak hash known to have hash collisions

### ISSUE THREAD

**Issue by nielskrijger** [mixpanel/mixpanel-android#612]
The mixpanel SDK was flagged during a security scan for using MD5 (the title of this post was the message shown).
While not necessarily a concern, I did have a look at this library to see how MD5 is being used. 

From what I can see the android library uses MD5 for a websocket handshake:
https://github.com/mixpanel/mixpanel-android/blob/master/src/main/java/com/mixpanel/android/java_websocket/drafts/Draft_76.java

Initially I checked the Websocket RFC and didn't find any mention of MD5, so I'm guessing it got removed from the draft.

After that I read this codebase more carefully and it looks like Draft_76.java might not even be used, instead I only found an initialisation of Draft 17 here:
https://github.com/mixpanel/mixpanel-android/blob/master/src/main/java/com/mixpanel/android/java_websocket/client/WebSocketClient.java

Draft 17 code:
https://github.com/mixpanel/mixpanel-android/blob/master/src/main/java/com/mixpanel/android/java_websocket/drafts/Draft_17.java

Can it be made clear what version of the websocket API is being used? I don't know if Draft 17 was eventually the one that got finalized?

**Comment by patedit** [comment]
You are correct, we use use `Draft_17` as you can see here: https://github.com/mixpanel/mixpanel-android/blob/master/src/main/java/com/mixpanel/android/viewcrawler/EditorConnection.java#L71 :)

**Comment by nielskrijger** [comment]
Thanks @patedit for the confirmation! It's essentially dead code then.

I'll close the issue.
