### ISSUE TITLE
The App uses an insecure Random Number Generator.

### ISSUE THREAD

**Issue by nielskrijger** [mixpanel/mixpanel-android#613]
This library got flagged because it uses "java.util.Random()", e.g. here:
https://github.com/mixpanel/mixpanel-android/blob/a89ba15568809add9f42e7253c7f9a6a349a522e/src/main/java/com/mixpanel/android/java_websocket/drafts/Draft_10.java

java.util.Random is not cryptographically secure. The handshake should be generated using a cryptographically secure RNG, e.g.: https://docs.oracle.com/javase/8/docs/api/java/security/SecureRandom.html

The websocket protocol states:

> Clients MUST choose a new masking key for each frame, using an
   algorithm that cannot be predicted by end applications that provide
   data.  For example, each masking could be drawn from a
   cryptographically strong random number generator.

**Comment by patedit** [comment]
To add a bit of more color, we use websockets if you want to connect to our AB test editor. We will eventually remove/update java_websockets dependency but no sensitive data is transferred in that ws connection

**Comment by nielskrijger** [comment]
Thank you for the context @patedit ! That eases the mind :-)
We're not using the AB test editor.

I'm OK with it not being addressed knowing the context. I'll leave it to you guys to either close or keep the issue open.

**Comment by nielskrijger** [comment]
@patedit The report also showed a unsafe RNG here:
com/mixpanel/android/mpmetrics/SessionMetadata.java

Is that something that should be addressed?

**Comment by patedit** [comment]
That file appends internal properties to events or people updates so we can do de-duplication of data in the backend in case it's needed. I would not worry about it :)
