### ISSUE TITLE
Braze integration. getCurrentUser null pointer exception

### ISSUE THREAD

**Issue by qbikkx** [mixpanel/mixpanel-android#618]
Hi, I faced next issue: 

> Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference

`[com.mixpanel.android.mpmetrics.ConnectIntegrations.setBrazePeopleProp(ConnectIntegrations.java:83), com.mixpanel.android.mpmetrics.ConnectIntegrations.setupIntegrations(ConnectIntegrations.java:35), com.mixpanel.android.mpmetrics.MixpanelAPI$SupportedUpdatesListener.run(MixpanelAPI.java:2622), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641), java.lang.Thread.run(Thread.java:764)]`

Current Braze User is null.
This happens if I initialize Mixpanel before Braze. But when I changed order to init Braze first and then Mixpanel - user is not null.

I think this moment must be mentioned somewhere in documentation/javadoc

Mixpanel version 5.6.4
Braze version 3.5.0

**Comment by patedit** [comment]
thanks for reporting this @qbikkx ! I've just pushed a fix to master and it will be available on the next release :)
