### ISSUE TITLE
Mixpanel not able to identify JSONarray

### ISSUE THREAD

**Issue by rahulrs134** [mixpanel/mixpanel-android#640]
In the below, JSON Item ID treated as a string instead of an array.

{"Type":"type","Brands":[name],"Item ID":[835,836]}

Please help with the above.

**Comment by patedit** [comment]
hey @rahulrs134 ! does this happen when using our group analytics solution? Could you provide more context as in what APIs you are using and what information you are passing?

**Comment by patedit** [comment]
I suspect this is related to https://github.com/mixpanel/mixpanel-android/pull/649
Feel free to re-open this issue if the problem persists. Thanks!

**Comment by rahulrs134** [comment]
Hi Sergio,

Thanks for the update. Currently, i moved to another project so i will
update you once i get back to the project.

Thanks & Regards
Rahul R S
