### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method getInstanceId()Lcom/google/android/gms/tasks/Task; in class Lcom/google/firebase/iid/FirebaseInstanceId; or its super classes (declaration of 'com.google.firebase.iid.FirebaseInstanceId' appears in /data/app/com.ojaexpressdelivery.app-1/base.apk:classes89.dex)

### ISSUE THREAD

**Issue by dilawer** [mixpanel/mixpanel-android#645]
compile 'com.mixpanel.android:mixpanel-android:5.+'

 compile 'com.google.firebase:firebase-core:11.8.0'
    compile 'com.google.firebase:firebase-messaging:11.8.0'
    compile 'com.google.firebase:firebase-invites:11.8.0'
    compile 'com.google.firebase:firebase-auth:11.8.0'

 compile 'com.google.android.gms:play-services-maps:11.8.0'
    compile 'com.google.android.gms:play-services-analytics:11.8.0'
    compile 'com.google.android.gms:play-services-location:11.8.0'
    compile 'com.google.android.gms:play-services-ads:11.8.0'

when code executes this line the app got crash
**mixpanelAPI = MixpanelAPI.getInstance(getContext(), project_Token);**

the log for the crash is

**java.lang.NoSuchMethodError: No virtual method getInstanceId()Lcom/google/android/gms/tasks/Task; in class Lcom/google/firebase/iid/FirebaseInstanceId; or its super classes (declaration of 'com.google.firebase.iid.FirebaseInstanceId' appears in /data/app/com.ojaexpressdelivery.app-1/base.apk:classes89.dex)**

**Comment by patedit** [comment]
Hi @dilawer - Thanks for writing in! Please, take a look [at this release notes](https://github.com/mixpanel/mixpanel-android/releases/tag/v5.5.0). We require to have firebase 16.2.0 or above in order to use push notifications. Hope that solves your problem, feel free to re-open this issue if you are experiencing other problems
