### ISSUE TITLE
People Identify aren't posted when calling mixpanel.identify

### ISSUE THREAD

**Issue by ahaverty** [mixpanel/mixpanel-android#647]
The following code (kotlin) never makes a post to https://api.mixpanel.com/engage
```kotlin
mixpanel.people.setMap(properties)
mixpanel.identify("user-${user.id}")
```

The following code does:
```kotlin
mixpanel.people.setMap(properties)
mixpanel.people.identify("user-${user.id}")
```

I assumed mixpanel.identify was a replacement/better alternative for mixpanel.getPeople.identify, but they seem to work differently.

**Comment by ahaverty** [comment]
It looks like that identifies a user, but doesn't link their events unless you do this:
```kotlin
mixpanel.people.setMap(properties)
mixpanel.identify("user-${user.id}")
mixpanel.people.identify("user-${user.id}")
```
The guides don't make this obvious in my opinion.

**Comment by patedit** [comment]
You are right, you need to identify the people profile through `people.identify`. Please, read the following doc for more details: https://developer.mixpanel.com/docs/android#section-managing-user-identity
