### ISSUE TITLE
Migrate from InstallReferrerReceiver

### ISSUE THREAD

**Issue by arturdryomov** [mixpanel/mixpanel-android#650]
[It will stop working from March 1, 2020](https://android-developers.googleblog.com/2019/11/still-using-installbroadcast-switch-to.html).

**Comment by patedit** [comment]
@arturdryomov Thanks so much! Will leave this open until this is done.

**Comment by mohan-dev1248** [comment]
Any update on this? Like, when can we expect the next update?

**Comment by patedit** [comment]
Thanks for your patience everyone. Our latest release includes this migration [v5.8.0](https://github.com/mixpanel/mixpanel-android/releases/tag/v5.8.0). Please, read the release notes to use the new mechanism and feel free to ask any questions here you might have. Thank you!
