### ISSUE TITLE
[android] support icon for both mipmap and drawable.

### ISSUE THREAD

**Issue by darylsze** [mixpanel/mixpanel-android#654]
AFAIK, currently push notification from mixpanel supports custom icon by providing drawable resource name (e.g. ic_launcher) with `mp_icon` key in custom payload json.

However, in `ResourceReader` class, its `getLocalClassName` only handles resource from drawable directory.

It's hope that mixpanel can support retrieving resource from both mipmap and drawable folders.

**Comment by zihejia** [comment]
Mixpanel is deprecating Messaging and Mobile A/B testing features([more details](https://mixpanel.com/blog/why-were-sunsetting-messaging-and-experiments/)), please contact our [support](https://help.mixpanel.com/hc/en-us/requests/new) if you need to continue the conversation for any critical issues. Sorry for the inconvenience.
