### ISSUE TITLE
Receiving `ConcurrentModificationExceptionThrown` when `registerSuperPropertiesMap` or `track` is called from `onResume`

### ISSUE THREAD

**Issue by hakanbagci** [mixpanel/mixpanel-android#658]
Here is the related part from stack trace for this exception. It seems like `superPropertiesCache` map is somehow concurrently being modified.

`java.util.LinkedHashMap$LinkedHashIterator.nextEntry (LinkedHashMap.java:346)
java.util.LinkedHashMap$EntryIterator.next (LinkedHashMap.java:375)
java.util.LinkedHashMap$EntryIterator.next (LinkedHashMap.java:373)
org.json.JSONObject.writeTo (JSONObject.java:719)
org.json.JSONStringer.value (JSONStringer.java:237)
org.json.JSONObject.writeTo (JSONObject.java:720)
org.json.JSONObject.toString (JSONObject.java:689)
com.mixpanel.android.mpmetrics.PersistentIdentity.storeSuperProperties (PersistentIdentity.java:556)
com.mixpanel.android.mpmetrics.PersistentIdentity.registerSuperProperties (PersistentIdentity.java:244)
com.mixpanel.android.mpmetrics.MixpanelAPI.registerSuperProperties (MixpanelAPI.java:759)
com.mixpanel.android.mpmetrics.MixpanelAPI.registerSuperPropertiesMap (MixpanelAPI.java:733)
de.flixbus.analytics.mixpanel.MixpanelGuard.registerSuperProperties (MixpanelGuard.java:28)`

This is not happening all the time, but happening quite often. It is also not specific to a device family or to an android version.

**Comment by hakanbagci** [comment]
Hey Mixpanel team, did you have time to check this bug?

**Comment by hakanbagci** [comment]
Some additional context: It is only happening if `track` or `registerSuperProperties` methods of `MixpanelAPI` are called from `onResume` callback method of the first activity.

**Comment by patedit** [comment]
thanks for your patience @hakanbagci. We haven't been able to reproduce this issue (and we've tried hard). Even so, we added a lock when accessing super properties which will, hopefully, solve your crash. Feel free to take a look at the PR https://github.com/mixpanel/mixpanel-android/pull/675/files
