### ISSUE TITLE
Analytics Worker Fatal Exception: Strange Thread Crash

### ISSUE THREAD

**Issue by jsonfry** [mixpanel/mixpanel-android#66]
We're using 4.0.0 and seeing some very strange crashes in various places on certain devices, but not others.  

The most reproducible crashing device is the incredibly slow Sony Xperia U running Android 4.0.4. 

If we ever call MixpanelAPI.getInstance(context, MIXPANEL_TOKEN) then our app crashes in different places, in our network request callbacks with this:

...
FATAL EXCEPTION: com.mixpanel.android.AnalyticsWorker
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
...

An example of the rest of a stack trace is at the bottom. 

This is without ever tracking any events. As soon as we stop grabbing an instance of MixpanelAPI we don't see any crashes. 

...
E/AndroidRuntime(14649):    at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:4043)
E/AndroidRuntime(14649):    at android.view.ViewRootImpl.invalidateChild(ViewRootImpl.java:722)
E/AndroidRuntime(14649):    at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:771)
E/AndroidRuntime(14649):    at android.view.ViewGroup.invalidateChild(ViewGroup.java:4112)
E/AndroidRuntime(14649):    at android.view.View.invalidate(View.java:8639)
E/AndroidRuntime(14649):    at android.view.View.invalidate(View.java:8590)
E/AndroidRuntime(14649):    at android.widget.TextView.updateTextColors(TextView.java:2901)
E/AndroidRuntime(14649):    at android.widget.TextView.drawableStateChanged(TextView.java:2911)
E/AndroidRuntime(14649):    at android.view.View.refreshDrawableState(View.java:11695)
E/AndroidRuntime(14649):    at android.view.View.setEnabled(View.java:4711)
E/AndroidRuntime(14649):    at android.widget.TextView.setEnabled(TextView.java:1230)
[removed... our app code]
E/AndroidRuntime(14649):    at android.os.AsyncTask.finish(AsyncTask.java:602)
E/AndroidRuntime(14649):    at android.os.AsyncTask.access$600(AsyncTask.java:156)
E/AndroidRuntime(14649):    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:615)
E/AndroidRuntime(14649):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(14649):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(14649):    at android.os.HandlerThread.run(HandlerThread.java:60)
...

**Comment by bacancy-mohit** [comment]
is there any way to get crash with class name and line number?
