### ISSUE TITLE
NPE due to absent null check

### ISSUE THREAD

**Issue by AfzalivE** [mixpanel/mixpanel-android#668]
https://github.com/mixpanel/mixpanel-android/blob/master/src/main/java/com/mixpanel/android/mpmetrics/MixpanelAPI.java#L666

a null `distinctId` now causes a NPE, whereas before, it didn't use to. Would be great to either have a null check and/or document that null value is not allowed.

Thanks

**Comment by patedit** [comment]
Hi @AfzalivE this is now fixed in the latest release [v5.8.0](https://github.com/mixpanel/mixpanel-android/releases/tag/v5.8.0). Thanks!!
