### ISSUE TITLE
[Question] Is there set method for useIPAddressForGeoLocation? 

### ISSUE THREAD

**Issue by lorenc-tomasz** [mixpanel/mixpanel-android#672]
Is there set method for useIPAddressForGeoLocation?

**Comment by patedit** [comment]
@lorenc-tomasz you can check this article out: https://help.mixpanel.com/hc/en-us/articles/115004494803-Disable-Geolocation-Collection
By default, this setting is `true`.

You just need to add the following tag to your `AndroidManifest.xml` file:
```
<meta-data android:name="com.mixpanel.android.MPConfig.UseIpAddressForGeolocation"
                   android:value="false" />
```

**Comment by lorenc-tomasz** [comment]
Thank you :)
