### ISSUE TITLE
Issue when running on local machine android

### ISSUE THREAD

**Issue by ahmedsafadii** [mixpanel/mixpanel-android#673]
MixpanelAPI.EditorCnctn: Websocket Error: failed to connect to switchboard.mixpanel.com/146.148.101.9 (port 443) from /10.0.2.16 (port 36618) after 5000ms

**Comment by patedit** [comment]
Hi @ahmedsafadii! How are you running the SDK on your local machine?

**Comment by ahmedsafadii** [comment]
yes simulator

**Comment by patedit** [comment]
how are you integrating the SDK? could you share some more details?

**Comment by zihejia** [comment]
Mixpanel is deprecating Messaging and Mobile A/B testing features([more details](https://mixpanel.com/blog/why-were-sunsetting-messaging-and-experiments/)), please contact our [support](https://help.mixpanel.com/hc/en-us/requests/new) if you need to continue the conversation for any critical issues. Sorry for the inconvenience.
