### ISSUE TITLE
V2.8.1 having issue when upload to Firebase App Distribution

### ISSUE THREAD

**Issue by elye** [mixpanel/mixpanel-android#681]
V2.7.0 was fine. When upgrade to V2.8.1 and upload to Firebase App Distribution, the error below occurs

Uploading APK to Firebase App Distribution...
Getting appId from output of google services plugin
App Distribution upload finished successfully!

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:publishProductionReleaseApk'.
> com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
  {
    "code" : 403,
    "errors" : [ {
      "domain" : "androidpublisher",
      "message" : "Symbol file invalid.",
      "reason" : "invalidSymbolFile"
    } ],
    "message" : "Symbol file invalid."
  }

**Comment by patedit** [comment]
Thanks for reporting this @elye ! Do you happen to obfuscate your code? Wondering if it's related to proguard. What's the relevant content of your proguard file (if any)? (ie mixpanel related and firebase related)

**Comment by elye** [comment]
Yes, the code is obfuscated. For mixed panel, we only have 
```
# Mixpanel
-dontwarn com.mixpanel.**
```
There are quite a bit of other that is google related

```
# Crashlytics
-keep class com.crashlytics.** { *; }
-dontwarn com.crashlytics.**
-keepnames @com.google.android.gms.common.annotation.KeepName class *
-keepclassmembernames class * {
    @com.google.android.gms.common.annotation.KeepName *;
}

-keep public class com.google.android.gms.common.internal.safeparcel.SafeParcelable {
    public static final *** NULL;
}

-keep public class com.google.android.gms.* { public *; }
-dontwarn com.google.android.gms.**
```

Are you suggesting that without proguard, this crash wouldn't happen, and suspect some line of proguard causing the issue?

**Comment by zihejia** [comment]
Mixpanel is deprecating Messaging and Mobile A/B testing features([more details](https://mixpanel.com/blog/why-were-sunsetting-messaging-and-experiments/)), please contact our [support](https://help.mixpanel.com/hc/en-us/requests/new) if you need to continue the conversation for any critical issues. Sorry for the inconvenience.
