### ISSUE TITLE
[Rich Notifications] Infinite loop when opening browser

### ISSUE THREAD

**Issue by lorenc-tomasz** [mixpanel/mixpanel-android#683]
There is an issue when user taps one rich notification that should open browser when app is closed. Returning to the app (main activity) will cause opening the browser again and again, and user cannot use the app. App have to be killed to start working again.

**Comment by aecast** [comment]
Could you give a bit more information on what exactly was happening and how to reproduce this?

**Comment by lorenc-tomasz** [comment]
@aecast

I sent notification that should open browser. If app is closed and user taps on notification the app will open the browser but user cannot return to the app. 

Config: https://imgur.com/WWPaPTf
Video: https://www.youtube.com/watch?v=a8VAwdicpnU&feature=youtu.be
