### ISSUE TITLE
how we can manage mixpanel if we have already custom notification in our FirebaseMessagingService

### ISSUE THREAD

**Issue by farhansaid127** [mixpanel/mixpanel-android#685]
we have already a rich feature of custom notification in FirebaseMessagingService class, but i tried to get mixpanel notification service but is not working.

**Comment by patedit** [comment]
hi @farhansaid127 - could you write into support@mixpanel.com with your question? Seems not to be related to proper functionality of the sdk. Happy to open an issue if there is a problem with this library 🙏

**Comment by farhansaid127** [comment]
I have sorted out the issue, 
The issue was due to mixpanel service declaring in manifest file it was declared before firebase service, now i have moved it after firebase service and it is working like charm. :)
