### ISSUE TITLE
[Rich Notifications] Push Notificaion that should open browser with sent URL doesn't work on Pixel

### ISSUE THREAD

**Issue by lorenc-tomasz** [mixpanel/mixpanel-android#691]
Hi,
one more issue with Rich Notifications. When user sends push notification that should open browser with the send URL it should work on all devices. Unfortunately it doesn't work on Pixel devices (it opens "homescreen"). It works OK on e.g. Samsung phones. 

Device: Pixel 1 with Android 10 (Pixel 1 on emulator works ok, the issue is on physical device)

Bug noticed by @PetervE.

**Comment by zihejia** [comment]
Mixpanel is deprecating Messaging and Mobile A/B testing features([more details](https://mixpanel.com/blog/why-were-sunsetting-messaging-and-experiments/)), please contact our [support](https://help.mixpanel.com/hc/en-us/requests/new) if you need to continue the conversation for any critical issues. Sorry for the inconvenience.
