### ISSUE TITLE
How to identify multiple different users on the same device under the same mixpanel project token?

### ISSUE THREAD

**Issue by pikaboo** [mixpanel/mixpanel-android#703]
I need to identify multiple users that run on the same device from the same mixpanel project token.

How to correctly do that?
In iOS it is possible because the MixpanelAPI has an instance name. In Android it seems not possible to have an instance name

**Comment by zihejia** [comment]
hi @pikaboo , sorry for the late response. You can get the same instance with the same token. http://mixpanel.github.io/mixpanel-android/index.html#getInstance

**Comment by pikaboo** [comment]
@zihejia Please reopen this.

You answer is not what I was looking for.
I do not want the same instance. I want the functionality that iOS version provides.

![image](https://user-images.githubusercontent.com/3405551/115134767-bff50880-a01b-11eb-8c79-174361d3e677.png)

Where i can get an instance of Mixpanel to report on several different "users" living on the same device.

For some reason iOS does have this functionality, and android does not. In android I need to pass the "mixpanel token" each time.

I dont want 
```         
 mMixpanel = MixpanelAPI.getInstance(this, "YOUR MIXPANEL API TOKEN");
```

I want 
```
          mMixpanel = MixpanelAPI.getInstance(this, "My Local user identifier");
```

**Comment by zihejia** [comment]
hi @pikaboo ,  no worries, we will address this.

**Comment by pikaboo** [comment]
@zihejia thanks, I look forward for some news.

**Comment by zihejia** [comment]
hi @pikaboo , please try v6.4.0 which includes the feature you requested, sorry for the long waiting. Feel free to reopen if you find any issues.
