### ISSUE TITLE
Rich Push Notifications cause a crash on Android 5 devices

### ISSUE THREAD

**Issue by blazmag** [mixpanel/mixpanel-android#704]
Hi,

We've received crash reports specifically coming from Android 5 devices whenever we send out a Rich push notification which also has a Notification button configured. 

We're using Mixpanel Android SDK 5.8.3

See notification setup here:
[Image link](https://ibb.co/FnWyq3N)

It only occurs on Android 5.0 - 5.1.1 devices, anything on 6.0+ is OK.

If the same notification is sent without any Notification Buttons, there's no crash.

We've integrated MixpanelFCMMessagingService as per the documentation.

The crash report, although it's not super helpful as it's a generic "Coulnd't expand RemoteViews" but it definitely occurs whenever a PN is sent from Mixpanel:

Bad notification posted from package com.XXXX.XXXX: Couldn't expand RemoteViews for: StatusBarNotification(pkg=com.XXXX.XXXX user=UserHandle{0} id=190887337 tag=null score=0 key=0|com.XXXX.XXXX|190887337|null|10138: Notification(pri=0 contentView=com.XXXX.XXXX/0x1090079 vibrate=null sound=null defaults=0x0 flags=0x10 color=0x00000000 actions=1 vis=PRIVATE))

Any help would be appreciated,

Thanks!

**Comment by blazmag** [comment]
I've also identified an OOM crash specific to Android 5 again and Mixpanel : 
It crashes in:
com.mixpanel.android.mpmetrics.MixpanelFCMMessagingService.showPushNotification (MixpanelFCMMessagingService.java:180)

I believe its caused by the Rich PN images which mixpanel started to support.

Anyone else experiencing issues with Android 5 & Mixpanel?

**Comment by zihejia** [comment]
hi @blazmag, the fix is included in the new version https://github.com/mixpanel/mixpanel-android/releases/tag/v5.8.5 we just released. I'm closing this one now, please feel free to reopen it if the problem still exists.
