### ISSUE TITLE
android notification icon is a white circle?

### ISSUE THREAD

**Issue by aforty** [mixpanel/mixpanel-android#705]
So this is weird but when I send a notification using Mixpanel (without any customizations, only a title and body) the notification icon is simply a white circle. When I send to the same token but using firebase console the icon I've defined in AndroidManifest.xml shows correctly.

What is the cause of this?

```
<!-- AndroidManifest.xml -->

<service android:name="com.mixpanel.android.mpmetrics.MixpanelFCMMessagingService" android:enabled="true" android:exported="false">
  <intent-filter>
    <action android:name="com.google.firebase.MESSAGING_EVENT"/>
  </intent-filter>
</service>

<meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/ic_stat_notification" />
<meta-data android:name="com.google.firebase.messaging.default_notification_color" android:resource="@color/colorPrimary" />
```

![0](https://user-images.githubusercontent.com/523683/91896889-8677b480-ec67-11ea-9766-7e0edab2366f.png)

**Comment by patedit** [comment]
Hi @aforty - Thanks for writing in! Our SDK doesn't use the `com.google.firebase.messaging.default_notification_icon` meta-data param, that is only used by firebase.
Have you set up your icon resource on the web UI when sending a push notification? 
<img width="705" alt="Screen Shot 2020-09-03 at 11 18 50 AM" src="https://user-images.githubusercontent.com/1812240/92140849-40d9f980-edd7-11ea-8331-9fcc3762e537.png">

Thanks!

**Comment by aforty** [comment]
Thanks for the reply. Hmm, but don't all push notifications on android use FCM under the hood? Why do we have to explicitly set it, couldn't mixpanel be set to use that as the default icon as well if one isn't specified?

What I'm saying is that it's a confusing experience to send a notification and not have it show an icon when one is defined for the app?

**Comment by oussamakenzup** [comment]
I created a notification icon from Android studio image asset too named it '" ic_notification ", and in Mixpanel I specify ic_notification I still get notification as app icon by default, I also tried @drawable/ic_notification and it didn't work, how exactly do you specify a resource name? Am I missing a step?

**Comment by anjalsaneen** [comment]
@oussamakenzup I'm facing the same issue. I have tried to understand mixpanel code, the implementation can break due to multiple reasons

@patedit I have a couple of questions?

1. How could mixpanel able to read resource id from another package? it can break apps which are having proguard, right?
2. When I check `mDrawableIds.knownIdName(iconName)` inside mixpanel SDK it always returning false even though the resources inside mixpanel sdk module?


@aforty 

I agree with you. setting icon explicitly is a very bad idea considering the chances of failures here. there has to be a default icon option.

**Comment by zihejia** [comment]
Mixpanel is deprecating Messaging and Mobile A/B testing features([more details](https://mixpanel.com/blog/why-were-sunsetting-messaging-and-experiments/)), please contact our [support](https://help.mixpanel.com/hc/en-us/requests/new) if you need to continue the conversation for any critical issues. Sorry for the inconvenience.
