### ISSUE TITLE
Play Store App Reject becasue mixpanel contains Ads.

### ISSUE THREAD

**Issue by pramodkr123** [mixpanel/mixpanel-android#708]
i am using this version :
implementation 'com.mixpanel.android:mixpanel-android:5.8.2'

![Screenshot (62)](https://user-images.githubusercontent.com/37994302/94645298-1eb99580-0309-11eb-9450-2802bb065475.png)

**Comment by zihejia** [comment]
hi @pramodkr123 , @lorenc-tomasz , we do NOT use Advertising ID or any device level identifiers that are unique to the device in Mixpanel SDK. We will follow up on why this is happening with Google Play.

**Comment by carstenhag** [comment]
Hm I also find it strange, we have included mix panel since a year now and haven’t had those notices yet.

**Comment by zihejia** [comment]
It might be due to the indirect reference of Google Play Services from firebase cloud messaging(FCM) for the messages feature. We have released v6.0.0 which no longer contains FCM so it should be fine now. I'm closing this one now, please feel free to reopen if the problem still exists.
