### ISSUE TITLE
the purpose of endless loop 

### ISSUE THREAD

**Issue by mikeliu60** [mixpanel/mixpanel-android#710]
i find the method 'run' of EditBinding is always in running, what the purpose of doing so.
`        @Override

        public void run() {

            if (!mAlive) {
                return;
            }

            final View viewRoot = mViewRoot.get();
            if (null == viewRoot || mDying) {
                cleanUp();
                return;
            }
            // ELSE View is alive and we are alive

            mEdit.visit(viewRoot);
            mHandler.removeCallbacks(this);
            mHandler.postDelayed(this, 1000);
        }`

**Comment by zihejia** [comment]
hi @mikeliu60 , this is for A/B testing.  We will release a version without A/B testing soon as we are deprecating Messaging and Mobile A/B testing features(more details), please contact our support if you need to continue the conversation for any critical issues. Sorry for the inconvenience.
