### ISSUE TITLE
Docs out of date for multiple push provider setup

### ISSUE THREAD

**Issue by liamheneghan** [mixpanel/mixpanel-android#712]
Hi there,

Relates to https://github.com/mixpanel/mixpanel-android/issues/586. 

The documentation at https://developer.mixpanel.com/docs/android-push-notifications#setting-up-your-androidmanifestxml is out of date re: multiple push providers.

Also, can I remove the entire Mixpanel service definition from the manifest when following the GitHub changelog for 5.5.1 re: multiple providers?

Thanks

**Comment by zihejia** [comment]
Mixpanel is deprecating Messaging and Mobile A/B testing features([more details](https://mixpanel.com/blog/why-were-sunsetting-messaging-and-experiments/)), please contact our [support](https://help.mixpanel.com/hc/en-us/requests/new) if you need to continue the conversation for any critical issues. Sorry for the inconvenience.
