### ISSUE TITLE
RuntimeException: Window couldn't find content container view GestureTracker.trackGestures

### ISSUE THREAD

**Issue by shah-nishant** [mixpanel/mixpanel-android#715]
We have started getting this crash in our app
<img width="1238" alt="Screenshot 2020-11-12 at 11 03 06 AM" src="https://user-images.githubusercontent.com/7080966/98900461-d086dd00-24d7-11eb-8ab3-a9c23bbe908d.png">

All of these crashes are happening on Android 6.0 devices. We recently set target SDK to 29, not sure if it could have any issues or not

**Comment by zihejia** [comment]
hi @shah-nishant Please try the latest version https://github.com/mixpanel/mixpanel-android/releases/tag/v5.8.6. It has a fix for it. Thanks for bringing it up.

**Comment by zihejia** [comment]
I'm closing this one now, please feel free to reopen it if the problem still exists.
