### ISSUE TITLE
Not getting user data in mixpanel users dashboard in xamarin android.

### ISSUE THREAD

**Issue by differenz-system** [mixpanel/mixpanel-android#727]
I need to set user identity at app registration and login in my xamarin forms app and I have used xamarin android library for mixpanel integration.I have set user identity using this code :

```c#
_mixpanelClient.People.Identify(userID); 
_mixpanelClient.People.Set(userID, GetJSONObject(new
                {
                    DistinctId = userID,
                    FirstName = firstName,
                    LastName = lastName,
                    Email = email
                }));
```
![issue_mixpanel](https://user-images.githubusercontent.com/14726367/111760592-e4e34800-88c4-11eb-8c4b-270e3c6ec21b.png)

- In userID, user's email id is passed currently.

So, the issue is I am getting user entry at dashboard of mixpanel but as unidentified user, not getting user's email or any other data like first name, last name.
 
 So, what is issue exactly. Issue is in payload of _mixpanelClient.People.Set function or any other.
 Anyone have the solution for this?

**Comment by zihejia** [comment]
hi @differenz-system , which Mixpanel SDK are you using? we don't have official Xamarin SDK at the moment.

**Comment by zihejia** [comment]
Closing this one now cause we don't have an official Xamarin SDK.
