### ISSUE TITLE
ActivityImageUtils.getScaledScreenshot crash

### ISSUE THREAD

**Issue by matteinn** [mixpanel/mixpanel-android#728]
Hi!
I'm noticing some crashes on the 5.8.7 android sdk, mainly on Android 8 devices.

`Fatal Exception: java.lang.IllegalArgumentException
width and height must be > 0

com.mixpanel.android.util.ActivityImageUtils.getScaledScreenshot (ActivityImageUtils.java:16)`

Possibly related to https://github.com/mixpanel/mixpanel-android/issues/711

**Comment by zihejia** [comment]
hi @matteinn , sorry for the inconvenience and thanks for providing the PR. I will do a patch release for this.
