### ISSUE TITLE
How do you set com.mixpanel.android.MPConfig.EventsEndpoint at runtime

### ISSUE THREAD

**Issue by dl748** [mixpanel/mixpanel-android#730]
mixpanel-swift has a function called setServerURL but the android sdk does not provide such a method, is there a way to dynamically set this at runtime?

**Comment by zihejia** [comment]
hi @dl748 , yes, please refer to this doc https://developer.mixpanel.com/docs/self-hosted-tracking in the Android SDK section.

**Comment by dl748** [comment]
No, those instructions set the variable at COMPILE time, which is completely different.

**Comment by zihejia** [comment]
hi @dl748 , sorry about that. We will consider providing it in the next couple of versions.

**Comment by zihejia** [comment]
hi @dl748 , we just released 5.9.0, now you can use [setServerURL](http://mixpanel.github.io/mixpanel-android/com/mixpanel/android/mpmetrics/MixpanelAPI.html#setServerURL-java.lang.String-) to set it in the run time. I'm closing it now, please feel free to reopen it if you find any issues in this API.
