### ISSUE TITLE
Properties "App Version" duplicate in dashboard

### ISSUE THREAD

**Issue by Thet-Tun-Aung** [mixpanel/mixpanel-android#731]
I found default mixpanel property "App Version" is duplicated in the dashboard. How can I fix it ?
I'm using sdk "com.mixpanel.android:mixpanel-android:5.8.5" for android

![duplicate_app_version](https://user-images.githubusercontent.com/19220742/113666405-3ff2a880-96d5-11eb-879f-8c120c007cf5.PNG)

**Comment by zihejia** [comment]
Hi @Thet-Tun-Aung , you can go to Data Management - Lexicon, and hide the deprecated property. 

![image](https://user-images.githubusercontent.com/36679208/114941480-14b83980-9df8-11eb-99b8-ba3eb36c5ef8.png)
