### ISSUE TITLE
How to clear time Event? 

### ISSUE THREAD

**Issue by vinson1022** [mixpanel/mixpanel-android#740]
I try to use `timeEvent()` to record a session from start editing to submit success.
And I want to cancel `timeEvent()` tracking when users exit editing.
But I can't find any API that can solve this situation on SDK. 

P.S. I find API `clearTimeEvent()` on iOS SDK can solve this situation.

**Comment by ddk9499** [comment]
Hello @zihejia. Any news about this issue?

**Comment by zihejia** [comment]
Hi @vinson1022 @ddk9499, we have released [6.1.0](https://github.com/mixpanel/mixpanel-android/releases/tag/v6.1.0) which contains the fix. I'm closing this one now, please feel free to reopen if the problem still exists.
