### ISSUE TITLE
User profile are not showing on mixpanel dashborad

### ISSUE THREAD

**Issue by Usama75** [mixpanel/mixpanel-android#751]
Here is my code how I am sending user profile. My events are listing in live view but profile of user are not showing under user tab.

 try {
            jsonObject.put("name", currentUser.szName);
            jsonObject.put("email", currentUser.szEmail);
            jsonObject.put("phone", currentUser.szPhoneNumber);

        } catch (JSONException e) {
            AnalyticsManager.instance.Error(e);
            e.printStackTrace();
        }
        mixpanelAPI.getPeople().set(jsonObject);

**Comment by cassiegamm** [comment]
Hi @Usama75, 

Before you send profile updates, you must call [getPeople().identify](https://developer.mixpanel.com/docs/android#storing-user-profiles). The library uses a separate ID for User records, and you must set this value for profile updates to flush from the device.  

Hope this solves the problem!

**Comment by Usama75** [comment]
yeah @cassiegamm Thanks!
