### ISSUE TITLE
Crash in v5.9.1,  java.lang.AssertionError @ WebSocketImpl.java:675

### ISSUE THREAD

**Issue by MatthewWhitmer** [mixpanel/mixpanel-android#757]
I noticed an app crash in Crashlytics from the MixPanel SDK v5.9.1;

Fatal Exception: java.lang.AssertionError
com.mixpanel.android.java_websocket.WebSocketImpl.isOpen (WebSocketImpl.java:675)
com.mixpanel.android.java_websocket.client.WebSocketClient.connectBlocking (WebSocketClient.java:123)
com.mixpanel.android.viewcrawler.EditorConnection.<init> (EditorConnection.java:51)
com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.connectToEditor (ViewCrawler.java:494)
com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.handleMessage (ViewCrawler.java:333)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:223)
android.os.HandlerThread.run (HandlerThread.java:67)

**Comment by zihejia** [comment]
hi @MatthewWhitmer , the error is from the A/B testing. Are you using it right now?  We are deprecating Messaging and Mobile A/B testing features([more details](https://mixpanel.com/blog/why-were-sunsetting-messaging-and-experiments/)). It will be removed on Jan 1, 2022. 
- If you are not using Mixpanel A/B testing and messaging, we'd highly suggest you opt into our beta version `implementation "com.mixpanel.android:mixpanel-android:6.0.0-beta+"` It has the current release minus A/B Testing and Messaging and it has our full support. 
- If you are using Mixpanel A/B testing and messaging and do need this fix, please contact our [support](https://help.mixpanel.com/hc/en-us/requests/new) to help us prioritize work. Sorry for the inconvenience.
