### ISSUE TITLE
Android 4 NullPointerException

### ISSUE THREAD

**Issue by Jieun-Kim-dev** [mixpanel/mixpanel-android#763]
according to https://github.com/mixpanel/mixpanel-android/issues/744, if I do
implementation 'com.google.firebase:firebase-iid'

Android 4 occurs NullPointerException because of FirebaseInstanceId

Fatal Exception: java.lang.NullPointerException
android.util.Pair.hashCode (Pair.java:62)
androidx.collection.SimpleArrayMap.indexOfKey (SimpleArrayMap.java:322)
androidx.collection.SimpleArrayMap.get (SimpleArrayMap.java:363)
com.google.firebase.iid.zzaq.zza (zzaq.java:6)
com.google.firebase.iid.FirebaseInstanceId.zza (FirebaseInstanceId.java:154)
com.google.firebase.iid.zzn.run (zzn.java)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1076)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:569)
java.lang.Thread.run (Thread.java:856)

How can I fix it for Android 4 (API16) ?

**Comment by williambeta** [comment]
请问这个问题有修改吗？
