### ISSUE TITLE
import com.mixpanel.android.mpmetrics.Tweak is missing?

### ISSUE THREAD

**Issue by ColtonIdle** [mixpanel/mixpanel-android#777]
Upgraded to version 6 and now my IDE complains about this import `import com.mixpanel.android.mpmetrics.Tweak`.

Are there any migration guidelines? I search the release notes, but didn't find anything related to Tweak.

**Comment by zihejia** [comment]
hi @ColtonIdle , version 6.0.0 deprecated Messaging and A/B Testing features so there should be no reference to Tweak anymore. It might due to the old build cache in your system if you find this is missing.

**Comment by ColtonIdle** [comment]
It's not build cache related. I'm using this method. What is the replacement?

```
MixpanelAPI.booleanTweak(foo, bar)
```

**Comment by ColtonIdle** [comment]
Oh Tweak is AB testing related?

**Comment by zihejia** [comment]
yeah, it's supposed to be used for altering values in your user's applications through the Mixpanel UI in A/B testing feature. If you update to 6.0.0, `booleanTweak` should no longer exist.

**Comment by ColtonIdle** [comment]
gotya. thanks
