### ISSUE TITLE
OpenHarmony support

### ISSUE THREAD

**Issue by Mr-zhao-dy** [mixpanel/mixpanel-android#790]
I am developing an OpenHarmony application by JavaScript language which used your library, will your library support OpenHarmony platform by JavaScript language?If so, I want to contribute to the OpenHarmony build of this library.Expecte for your reply!

**Comment by zihejia** [comment]
Hi @Mr-zhao-dy, I apologize, but currently, we do not have any plans to support OpenHarmony.
