### ISSUE TITLE
Add an option to disable DevX tracking

### ISSUE THREAD

**Issue by ninniuz** [mixpanel/mixpanel-android#799]
Starting from SDK version 6.1.2 Mixpanel is issuing DevX events for tracking purposes. 
Such events are enabled whenever the app is debuggable, with no way for an integrator to turn the tracking off. 

Would it be possible to add a config option to disable DevX tracking altogether?

**Comment by zihejia** [comment]
hi @ninniuz , we have removed the DevX from v7.2.0. closing this one now.
