### ISSUE TITLE
MixPanel chart doesn't seem to update

### ISSUE THREAD

**Issue by neonwarge04** [mixpanel/mixpanel-android#812]
We have a concern regarding a  disconnect with the chart in MixPanel. Not entirely sure if our chart is updating or not.We find that we have at least 300+ hit on this particular screen when we checked in Firebase but MixPanel paints a different picture:
![image](https://user-images.githubusercontent.com/3163716/228446841-16398507-4a12-42ce-9d44-4bf4a9ee4a08.png)

But in Firebase we have the following:
![image](https://user-images.githubusercontent.com/3163716/228446075-f6d0084e-3d13-4e99-829b-e977a7236639.png)

The image captured in MixPanel was shot this afternoon. The firebase screen shot was captured just this morning. But the trends still 0. 

Is MixPanel dashboard realtime in update or do we have to wait until tomorrow until it all shows up? Or is this a configuration issue? The events emitted here are coming from mobile devices.

Let me know if you need more info. TIA!

**Comment by jaredmixpanel** [comment]
@neonwarge04 please email support@mixpanel.com for help troubleshooting issues like this
