### ISSUE TITLE
Mixpanel not tracked in certain country on Android

### ISSUE THREAD

**Issue by yerlansarsenov** [mixpanel/mixpanel-android#814]
We are facing the problem that mixpanel events are not tracked from users who are located in United Kingdom. Yesterday we certainly used our application and surely events must be sent, but no events with country United Kingdom or from this certain user cannot be found in boards. All other events that are tracked by developers who are located in Kazakhstan, or tracked by Google Play testers (maybe bots) who probably located in United States, can be seen in boards. For our native application on iOS this problem is not faced. On Android we implemented everything correctly as stated in Developers Documentation. Please, give any possible reasons, any suggestions. Thanks

**Comment by jaredmixpanel** [comment]
@yerlansarsenov Please contact support@mixpanel.com for help troubleshooting this issue.
