### ISSUE TITLE
The "Next" arrow should not be displayed on the last survey question

### ISSUE THREAD

**Issue by joeatwork** [mixpanel/mixpanel-android#83]
One last point about the UI of the survey. In the top corner of each survey page there are the arrow symbols to navigate between the questions. But on the last page there is still a right arrow that signals the user that there is more content.

**Comment by ansman** [comment]
It would be nicer if the arrow turned to a done button. We're getting a lot of bug reports from user's who don't understand that they first need to dismiss the keyboard and then press exit.

**Comment by patedit** [comment]
With https://github.com/mixpanel/mixpanel-android/pull/371 we will hide the arrows when there are no more questions. Also, notice that once the user answers the last question the survey is auto dismissed.

**Comment by ansman** [comment]
I think just having the Done key in the keyboard isn't enough, people don't always understand that. An explicit done button would be nice.

**Comment by patedit** [comment]
@anas-ambri Are you talking about the multiple-choice questions or the input text questions?

**Comment by ansman** [comment]
@patedit We've only had a text input question as the last question.
