### ISSUE TITLE
Build broken because of minSDK 23

### ISSUE THREAD

**Issue by vlazdra** [mixpanel/mixpanel-android#843]
Could you please explain why the minSDK for Android was changed from 17 to 23 in a minor release? Since version 21 is currently standard, this change has unfortunately caused issues with many apps.

I kindly request that you consider updating the minSDK to 21 instead of 23.

**Comment by Rashxz** [comment]
What sdk version wer you previously using?

**Comment by vlazdra** [comment]
Hey @Rashxz ! 👋 

I'm coming from the Mixpanel Flutter SDK, but since it's a problem with the Mixpanel Android SDK that the Flutter one is depending on that's why I wrote here.

Mixpanel Flutter SDK went from 2.3.1 to 2.3.2 and updated the underlying Mixpanel Android SDK from 7.5.0 to 7.5.3.

The change to a minSDK for Android occurred in the 7.5.3 release: https://github.com/mixpanel/mixpanel-android/pull/840/files#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7R34

**Comment by Rashxz** [comment]
Thanks @vlazdra for pointing it out. Was building something this morning and came to this surprise. 
This changes should be better documented in the releases, and the minSdk stated in the readme.

**Comment by vlazdra** [comment]
It's not just the documentation part @Rashxz , it's also the decision to add a breaking change of this kind in to a minor release. By specifcying this is minor, you broke everyones builds and apps because of it. Most dependency tools update their dependencies automatically to the latest bugfix and minor releases because they shouldn't have breaking changes. They can have deprecations and etc, but not breaking changes.

On the other note, changing min Android SDK to 23 is not needed, the industry standard is still 21 and this change should be reverted back to 17 and change the min SDK to 21 in a 8.0.0 Mixpanel SDK as a breaking change.

I hope the dev team will reconsider this change, and make sure that in future changes like happen in a proper way.

**Comment by zihejia** [comment]
hi @vlazdra, sorry for the inconvenience, and thank you so much for bringing this up. We will revert it back.

**Comment by jaredmixpanel** [comment]
Closing with https://github.com/mixpanel/mixpanel-android/pull/845
