### ISSUE TITLE
After upgrading to 7.5.3 TakeoverInAppActivity and TakeoverInAppActivityTheme not found

### ISSUE THREAD

**Issue by Sara-Tareq** [mixpanel/mixpanel-android#844]
My build is failing after upgrading to the latest SDK version 7.5.3 with an error :

 Android resource linking failed
ERROR: /app/src/main/AndroidManifest.xml:309:9-311:86: AAPT: error: resource style/com_mixpanel_android_TakeoverInAppActivityTheme (aka app_package:style/com_mixpanel_android_TakeoverInAppActivityTheme) not found.

**Comment by argenisf** [comment]
@Sara-Tareq as of version 6, the messaging features have been removed: [https://github.com/mixpanel/mixpanel-android/releases/tag/v6.0.0](https://github.com/mixpanel/mixpanel-android/releases/tag/v6.0.0)

The error likely comes from still having a reference to the in-app takeover activity in your manifest

**Comment by Sara-Tareq** [comment]
@argenisf thank you for clarifying, I got confused when I saw the in-app takeover activity still available in the sample app.
