### ISSUE TITLE
Hide JSONObject as implementation detail

### ISSUE THREAD

**Issue by JakeWharton** [mixpanel/mixpanel-android#96]
The `org.json.*` API is terrible to use from consumers of the library and presumably for you inside of the library. I mean a checked `JsonException` on just about every method? Please see yourself out, `org.json.*`. While everyone appreciates the lack of Gson or Jackson dependency, can we strive to kill `JSONObject` from the public API?

The offenders are `.track`, `.registerSuperProperties`, and `.registerSuperPropertiesOnce`.

From an API standpoint, I would think that the latter two should be changed such that you call each multiple times with a single key/value pair. The `People` interface exposes similar methods with the same behaviors and it should follow suit.

`track` is a bit harder since you want to encapsulate sending all the data in a single API call. Personally we only use String/String pairs so a `Map<String, String>` would be ideal. If the API actually supports complex, nested objects then perhaps a `Map<String, Object>` would be better suited.

**Comment by joeatwork** [comment]
JSONObject is the worst. Let's get this done.

**Comment by joeatwork** [comment]
Thanks @eveliotc for the pointer

**Comment by eveliotc** [comment]
Awesome! thanks @joeatwork!

![Praise the lord](http://feyworks.com/wp-content/uploads/2012/06/Praise-the-Lord.jpg)

**Comment by JakeWharton** [comment]
Yessssssssss!

**Comment by yinfeiru** [comment]
Closing as it's in the latest lib.
